// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignAccountCSM = `-- name: AssignAccountCSM :exec
UPDATE accounts SET
    assigned_csm = $1,
    backup_csm   = $2,
    updated_by   = $3,
    updated_at   = now()
WHERE id = $4 AND deleted_at IS NULL
`

type AssignAccountCSMParams struct {
	AssignedCsm *int64 `json:"assigned_csm"`
	BackupCsm   *int64 `json:"backup_csm"`
	UpdatedBy   *int64 `json:"updated_by"`
	ID          int64  `json:"id"`
}

// Penugasan CSM (binaan + cadangan) — jalur terpisah dari edit profil (§8.1).
// NULL = lepas penugasan. updated_by/at ikut agar jejaknya jelas.
func (q *Queries) AssignAccountCSM(ctx context.Context, arg AssignAccountCSMParams) error {
	_, err := q.db.Exec(ctx, assignAccountCSM,
		arg.AssignedCsm,
		arg.BackupCsm,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (
    tenant_id, entity_code, village_name, village_code, account_type,
    account_owner, assigned_csm, backup_csm,
    website, description,
    province, regency, district, village_address, postal_code, territory,
    village_status, village_classification, population, hamlets_count, village_budget,
    contact_phone, office_phone, office_email,
    created_by
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18,
    $19, $20, $21,
    $22, $23, $24,
    $25
)
RETURNING id, tenant_id, account_owner, assigned_csm, backup_csm, village_name, village_code, account_type, parent_account_id, website, description, province, regency, district, village_address, postal_code, latitude, longitude, territory, village_status, village_classification, population, hamlets_count, village_budget, contact_phone, office_phone, office_email, deleted_at, created_by, created_at, updated_by, updated_at, entity_code
`

type CreateAccountParams struct {
	TenantID              int64          `json:"tenant_id"`
	EntityCode            *string        `json:"entity_code"`
	VillageName           string         `json:"village_name"`
	VillageCode           *string        `json:"village_code"`
	AccountType           string         `json:"account_type"`
	AccountOwner          *int64         `json:"account_owner"`
	AssignedCsm           *int64         `json:"assigned_csm"`
	BackupCsm             *int64         `json:"backup_csm"`
	Website               *string        `json:"website"`
	Description           *string        `json:"description"`
	Province              *string        `json:"province"`
	Regency               *string        `json:"regency"`
	District              *string        `json:"district"`
	VillageAddress        *string        `json:"village_address"`
	PostalCode            *string        `json:"postal_code"`
	Territory             *string        `json:"territory"`
	VillageStatus         *string        `json:"village_status"`
	VillageClassification *string        `json:"village_classification"`
	Population            *int32         `json:"population"`
	HamletsCount          *int32         `json:"hamlets_count"`
	VillageBudget         pgtype.Numeric `json:"village_budget"`
	ContactPhone          *string        `json:"contact_phone"`
	OfficePhone           *string        `json:"office_phone"`
	OfficeEmail           *string        `json:"office_email"`
	CreatedBy             *int64         `json:"created_by"`
}

// accounts.sql — hub Desa (Account). Isolasi WORKSPACE ditegakkan RLS (GUC
// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
// lewat flag ownership di ListAccounts — lihat internal/db/ownership.go.
//
// entity_code (DESA-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
// dioper ke CreateAccount; village_code (Kode Kemendagri) datang dari user & boleh
// kosong. Dua kode berbeda asal, keduanya disimpan di baris.
// Buat desa. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
// entity_code sudah dirakit pemanggil (GenerateEntityCode) — INSERT-nya dijaga
// unik oleh idx_accounts_entity_code bila format diubah bertabrakan.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TenantID,
		arg.EntityCode,
		arg.VillageName,
		arg.VillageCode,
		arg.AccountType,
		arg.AccountOwner,
		arg.AssignedCsm,
		arg.BackupCsm,
		arg.Website,
		arg.Description,
		arg.Province,
		arg.Regency,
		arg.District,
		arg.VillageAddress,
		arg.PostalCode,
		arg.Territory,
		arg.VillageStatus,
		arg.VillageClassification,
		arg.Population,
		arg.HamletsCount,
		arg.VillageBudget,
		arg.ContactPhone,
		arg.OfficePhone,
		arg.OfficeEmail,
		arg.CreatedBy,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountOwner,
		&i.AssignedCsm,
		&i.BackupCsm,
		&i.VillageName,
		&i.VillageCode,
		&i.AccountType,
		&i.ParentAccountID,
		&i.Website,
		&i.Description,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.VillageAddress,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Territory,
		&i.VillageStatus,
		&i.VillageClassification,
		&i.Population,
		&i.HamletsCount,
		&i.VillageBudget,
		&i.ContactPhone,
		&i.OfficePhone,
		&i.OfficeEmail,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EntityCode,
	)
	return i, err
}

const findDuplicateAccountsByNameRegion = `-- name: FindDuplicateAccountsByNameRegion :many
SELECT id, entity_code, village_name, regency
FROM accounts
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND lower(trim(village_name)) = lower(trim($2))
  AND (
      $3::text IS NULL
      OR lower(trim(COALESCE(regency, ''))) = lower(trim($3))
  )
ORDER BY created_at DESC
LIMIT 5
`

type FindDuplicateAccountsByNameRegionParams struct {
	TenantID    int64   `json:"tenant_id"`
	VillageName string  `json:"village_name"`
	Regency     *string `json:"regency"`
}

type FindDuplicateAccountsByNameRegionRow struct {
	ID          int64   `json:"id"`
	EntityCode  *string `json:"entity_code"`
	VillageName string  `json:"village_name"`
	Regency     *string `json:"regency"`
}

// Kandidat desa dgn nama sama (case-insensitive, trim) di tenant yang sama — dipakai
// sbg soft-warning di halaman review konversi lead (M4-6, follow-up), BUKAN hard
// block: nama desa yang sama bisa valid beda dusun/kabupaten. regency opsional:
// diisi → ikut menyaring; kosong → cukup cocokkan nama. Ditopang index functional
// idx_accounts_village_name_ci (00020). Dibatasi 5 kandidat, cukup utk peringatan,
// bukan daftar lengkap.
func (q *Queries) FindDuplicateAccountsByNameRegion(ctx context.Context, arg FindDuplicateAccountsByNameRegionParams) ([]FindDuplicateAccountsByNameRegionRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateAccountsByNameRegion, arg.TenantID, arg.VillageName, arg.Regency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateAccountsByNameRegionRow{}
	for rows.Next() {
		var i FindDuplicateAccountsByNameRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityCode,
			&i.VillageName,
			&i.Regency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, account_owner, assigned_csm, backup_csm, village_name, village_code, account_type, parent_account_id, website, description, province, regency, district, village_address, postal_code, latitude, longitude, territory, village_status, village_classification, population, hamlets_count, village_budget, contact_phone, office_phone, office_email, deleted_at, created_by, created_at, updated_by, updated_at, entity_code FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

// Satu desa hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
// ter-soft-delete. Tak menerapkan ownership — pemanggil (handler) yang memutuskan
// apakah aktor boleh membuka baris ini (detail bisa dibuka lewat tautan langsung).
func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountOwner,
		&i.AssignedCsm,
		&i.BackupCsm,
		&i.VillageName,
		&i.VillageCode,
		&i.AccountType,
		&i.ParentAccountID,
		&i.Website,
		&i.Description,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.VillageAddress,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Territory,
		&i.VillageStatus,
		&i.VillageClassification,
		&i.Population,
		&i.HamletsCount,
		&i.VillageBudget,
		&i.ContactPhone,
		&i.OfficePhone,
		&i.OfficeEmail,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EntityCode,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, tenant_id, account_owner, assigned_csm, backup_csm, village_name, village_code, account_type, parent_account_id, website, description, province, regency, district, village_address, postal_code, latitude, longitude, territory, village_status, village_classification, population, hamlets_count, village_budget, contact_phone, office_phone, office_email, deleted_at, created_by, created_at, updated_by, updated_at, entity_code FROM accounts
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND account_owner = $5)
      OR ($6::boolean AND (assigned_csm = $5 OR backup_csm = $5))
  )
  AND (NOT $7::boolean OR account_owner IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListAccountsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsSales         bool               `json:"is_sales"`
	Uid             *int64             `json:"uid"`
	IsCsm           bool               `json:"is_csm"`
	Unowned         bool               `json:"unowned"`
	PageSize        int32              `json:"page_size"`
}

// Daftar desa, keyset (created_at DESC, id DESC) + filter ownership F3.
//
// Ownership dikodekan sebagai tiga flag boolean (bukan fragmen SQL dinamis) supaya
// query tetap sqlc murni & ter-scan typed. Keputusan cakupannya SATU sumber dengan
// AccountsOwnershipClause: keduanya diturunkan dari AccountsScopeFor lewat
// AccountsListFilter — diuji bersama agar tak bercabang.
//
//	scope_all → lihat semua (Admin/Manager)
//	is_sales  → hanya account_owner = uid
//	is_csm    → assigned_csm = uid ATAU backup_csm = uid
//
// Ketiganya false (Support/role kosong/liar) → OR selalu false → NOL baris
// (fail-closed, bukan bocor). uid tetap dioper walau scope_all (diabaikan).
//
// unowned = tapis SEJAJAR (tab "Belum ada Owner"): saring account_owner IS NULL
// DI ATAS blok ownership, bukan menggantinya. false → NOT false = TRUE → tak
// membatasi; true → hanya desa tanpa pemilik. Inheren cakupan-all: pemakai
// ber-scope 'own' tak pernah punya baris owner-kosong, jadi handler hanya
// menyalakannya untuk peran ScopeAll (Manager/Admin).
func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsSales,
		arg.Uid,
		arg.IsCsm,
		arg.Unowned,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountOwner,
			&i.AssignedCsm,
			&i.BackupCsm,
			&i.VillageName,
			&i.VillageCode,
			&i.AccountType,
			&i.ParentAccountID,
			&i.Website,
			&i.Description,
			&i.Province,
			&i.Regency,
			&i.District,
			&i.VillageAddress,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
			&i.Territory,
			&i.VillageStatus,
			&i.VillageClassification,
			&i.Population,
			&i.HamletsCount,
			&i.VillageBudget,
			&i.ContactPhone,
			&i.OfficePhone,
			&i.OfficeEmail,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.EntityCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE accounts SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteAccountParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
// entitas lain — deal/tiket — tak putus). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, arg.UpdatedBy, arg.ID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET
    village_name          = $1,
    account_type          = $2,
    website               = $3,
    description           = $4,
    province              = $5,
    regency               = $6,
    district              = $7,
    village_address       = $8,
    postal_code           = $9,
    territory             = $10,
    village_status        = $11,
    village_classification = $12,
    population            = $13,
    hamlets_count         = $14,
    village_budget        = $15,
    contact_phone         = $16,
    office_phone          = $17,
    office_email          = $18,
    updated_by            = $19,
    updated_at            = now()
WHERE id = $20 AND deleted_at IS NULL
RETURNING id, tenant_id, account_owner, assigned_csm, backup_csm, village_name, village_code, account_type, parent_account_id, website, description, province, regency, district, village_address, postal_code, latitude, longitude, territory, village_status, village_classification, population, hamlets_count, village_budget, contact_phone, office_phone, office_email, deleted_at, created_by, created_at, updated_by, updated_at, entity_code
`

type UpdateAccountParams struct {
	VillageName           string         `json:"village_name"`
	AccountType           string         `json:"account_type"`
	Website               *string        `json:"website"`
	Description           *string        `json:"description"`
	Province              *string        `json:"province"`
	Regency               *string        `json:"regency"`
	District              *string        `json:"district"`
	VillageAddress        *string        `json:"village_address"`
	PostalCode            *string        `json:"postal_code"`
	Territory             *string        `json:"territory"`
	VillageStatus         *string        `json:"village_status"`
	VillageClassification *string        `json:"village_classification"`
	Population            *int32         `json:"population"`
	HamletsCount          *int32         `json:"hamlets_count"`
	VillageBudget         pgtype.Numeric `json:"village_budget"`
	ContactPhone          *string        `json:"contact_phone"`
	OfficePhone           *string        `json:"office_phone"`
	OfficeEmail           *string        `json:"office_email"`
	UpdatedBy             *int64         `json:"updated_by"`
	ID                    int64          `json:"id"`
}

// Sunting profil desa. entity_code & village_code tak diubah di sini (kode identitas
// yang dikutip; village_code punya jalur khusus bila kelak perlu). Penugasan
// (owner/CSM) juga TERPISAH (AssignAccountCSM) agar perubahan wewenang terlihat
// sebagai aksi tersendiri, bukan efek samping edit profil.
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.VillageName,
		arg.AccountType,
		arg.Website,
		arg.Description,
		arg.Province,
		arg.Regency,
		arg.District,
		arg.VillageAddress,
		arg.PostalCode,
		arg.Territory,
		arg.VillageStatus,
		arg.VillageClassification,
		arg.Population,
		arg.HamletsCount,
		arg.VillageBudget,
		arg.ContactPhone,
		arg.OfficePhone,
		arg.OfficeEmail,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountOwner,
		&i.AssignedCsm,
		&i.BackupCsm,
		&i.VillageName,
		&i.VillageCode,
		&i.AccountType,
		&i.ParentAccountID,
		&i.Website,
		&i.Description,
		&i.Province,
		&i.Regency,
		&i.District,
		&i.VillageAddress,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Territory,
		&i.VillageStatus,
		&i.VillageClassification,
		&i.Population,
		&i.HamletsCount,
		&i.VillageBudget,
		&i.ContactPhone,
		&i.OfficePhone,
		&i.OfficeEmail,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.EntityCode,
	)
	return i, err
}
