// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one

INSERT INTO activities (
    tenant_id, kind, subject, target_type, target_id,
    owner_id, activity_context, status, notes,
    due_date, priority, reminder_at,
    contact_id, direction, activity_at, duration_min, call_result,
    start_at, end_at, location, meeting_type, channel,
    body,
    created_by
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17,
    $18, $19, $20,
    $21, $22,
    $23,
    $24
)
RETURNING id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at
`

type CreateActivityParams struct {
	TenantID        int64              `json:"tenant_id"`
	Kind            string             `json:"kind"`
	Subject         string             `json:"subject"`
	TargetType      string             `json:"target_type"`
	TargetID        int64              `json:"target_id"`
	OwnerID         *int64             `json:"owner_id"`
	ActivityContext *string            `json:"activity_context"`
	Status          *string            `json:"status"`
	Notes           *string            `json:"notes"`
	DueDate         pgtype.Date        `json:"due_date"`
	Priority        *string            `json:"priority"`
	ReminderAt      pgtype.Timestamptz `json:"reminder_at"`
	ContactID       *int64             `json:"contact_id"`
	Direction       *string            `json:"direction"`
	ActivityAt      pgtype.Timestamptz `json:"activity_at"`
	DurationMin     *int32             `json:"duration_min"`
	CallResult      *string            `json:"call_result"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
	Location        *string            `json:"location"`
	MeetingType     *string            `json:"meeting_type"`
	Channel         *string            `json:"channel"`
	Body            *string            `json:"body"`
	CreatedBy       *int64             `json:"created_by"`
}

// activities.sql — aktivitas polimorfik (task/call/note …). Isolasi WORKSPACE
// ditegakkan RLS (GUC app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3)
// ditegakkan di layer query lewat flag ownership di ListActivities — lihat
// ownership.go (ActivitiesListFilter, sumbu tunggal owner_id).
//
// Nama query JAMAK (Activities) — sengaja beda dari activity.sql (presence,
// 00001) agar tak bentrok di querier generated. Tabel TAK punya entity_code
// (spec §7a) → tak ada alokasi kode di create.
//
// activity_context di-set handler ('sales' untuk 4.4); target_id BUKAN FK
// (integritas target diverifikasi handler via loadOwned* sebelum insert).
// Buat aktivitas. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya =
// GUC). Kolom per-kind opsional (narg) — hanya yang relevan untuk kind terisi.
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.TenantID,
		arg.Kind,
		arg.Subject,
		arg.TargetType,
		arg.TargetID,
		arg.OwnerID,
		arg.ActivityContext,
		arg.Status,
		arg.Notes,
		arg.DueDate,
		arg.Priority,
		arg.ReminderAt,
		arg.ContactID,
		arg.Direction,
		arg.ActivityAt,
		arg.DurationMin,
		arg.CallResult,
		arg.StartAt,
		arg.EndAt,
		arg.Location,
		arg.MeetingType,
		arg.Channel,
		arg.Body,
		arg.CreatedBy,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Subject,
		&i.TargetType,
		&i.TargetID,
		&i.OwnerID,
		&i.ActivityContext,
		&i.Status,
		&i.Notes,
		&i.DueDate,
		&i.Priority,
		&i.ReminderAt,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Location,
		&i.MeetingType,
		&i.ContactID,
		&i.Direction,
		&i.ActivityAt,
		&i.DurationMin,
		&i.CallResult,
		&i.EmailFrom,
		&i.EmailTo,
		&i.EmailStatus,
		&i.Body,
		&i.EngagementType,
		&i.Frequency,
		&i.Channel,
		&i.ScheduledDate,
		&i.NextDueDate,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivity = `-- name: GetActivity :one
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE id = $1 AND deleted_at IS NULL
`

// Satu aktivitas hidup. RLS menjamin tenant_id; ownership diputuskan handler
// (ActivitiesListFilter.Allows) atas baris.
func (q *Queries) GetActivity(ctx context.Context, id int64) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Subject,
		&i.TargetType,
		&i.TargetID,
		&i.OwnerID,
		&i.ActivityContext,
		&i.Status,
		&i.Notes,
		&i.DueDate,
		&i.Priority,
		&i.ReminderAt,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Location,
		&i.MeetingType,
		&i.ContactID,
		&i.Direction,
		&i.ActivityAt,
		&i.DurationMin,
		&i.CallResult,
		&i.EmailFrom,
		&i.EmailTo,
		&i.EmailStatus,
		&i.Body,
		&i.EngagementType,
		&i.Frequency,
		&i.Channel,
		&i.ScheduledDate,
		&i.NextDueDate,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND activity_context = $1::text
  AND (created_at, id) < ($2::timestamptz, $3::bigint)
  AND (
      $4::boolean
      OR ($5::boolean AND owner_id = $6)
  )
  AND ($7::text = '' OR subject ILIKE '%' || $7 || '%')
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListActivitiesParams struct {
	ContextFilter   string             `json:"context_filter"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Daftar aktivitas (tampilan Tabel), keyset (created_at DESC, id DESC) + filter
// ownership F3 + filter context. Dua flag ownership (sumber SATU dengan
// ActivitiesListFilter): scope_all → semua; is_own → owner_id = uid; keduanya
// false → NOL baris (fail-closed). context_filter menyaring view modul
// ('sales' untuk 4.4) — pemisah dari CS 6.5 / general M7.
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership+context — tak pernah melebarkan baris (BL-6).
// Hanya subject (satu-satunya kolom teks bebas yang TAMPIL) jadi kunci cari;
// kind/status/target = enum/id (bukan teks bebas), owner = nama diresolusi handler.
func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.ContextFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesByTarget = `-- name: ListActivitiesByTarget :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND target_type = $1::text
  AND target_id   = $2::bigint
  AND (created_at, id) < ($3::timestamptz, $4::bigint)
  AND ($5::text = '' OR subject ILIKE '%' || $5 || '%')
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListActivitiesByTargetParams struct {
	TargetType      string             `json:"target_type"`
	TargetID        int64              `json:"target_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Timeline satu entitas: semua aktivitas yang terkait ke target_type+target_id ini,
// keyset (created_at DESC, id DESC). Tanpa filter context (lintas sales/cs/general)
// dan tanpa F3 ownership — siapa pun yang boleh lihat entitasnya boleh lihat
// timelinenya (gate ada di handler detail entitas masing-masing). search ” →
// tak menyaring; selain itu MEMPERSEMPIT subject (BL-6, ILIKE case-insensitive)
// di ATAS filter target — tak menembus ke entitas lain.
func (q *Queries) ListActivitiesByTarget(ctx context.Context, arg ListActivitiesByTargetParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesByTarget,
		arg.TargetType,
		arg.TargetID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesSortByDate = `-- name: ListActivitiesSortByDate :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND activity_context = $1::text
  AND (
      NOT $2::boolean
      OR ($3::text = 'asc'
          AND (created_at, id) > ($4::timestamptz, $5::bigint))
      OR ($3::text = 'desc'
          AND (created_at, id) < ($4::timestamptz, $5::bigint))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND owner_id = $8)
  )
  AND ($9::text = '' OR subject ILIKE '%' || $9 || '%')
ORDER BY
  CASE WHEN $3::text = 'asc'  THEN created_at END ASC,
  CASE WHEN $3::text = 'desc' THEN created_at END DESC,
  CASE WHEN $3::text = 'asc'  THEN id END ASC,
  CASE WHEN $3::text = 'desc' THEN id END DESC
LIMIT $10
`

type ListActivitiesSortByDateParams struct {
	ContextFilter string             `json:"context_filter"`
	HasCursor     bool               `json:"has_cursor"`
	Dir           string             `json:"dir"`
	CursorVal     pgtype.Timestamptz `json:"cursor_val"`
	CursorID      int64              `json:"cursor_id"`
	ScopeAll      bool               `json:"scope_all"`
	IsOwn         bool               `json:"is_own"`
	Uid           *int64             `json:"uid"`
	Search        string             `json:"search"`
	PageSize      int32              `json:"page_size"`
}

// BL-157j (lanjutan): sort by Tanggal (created_at) — NOT NULL, tapi BEDA dari
// ListActivities: arah DINAMIS (bisa asc, bukan desc tetap), jadi tak bisa
// pakai pageCursor/splitPage biasa (sentinel ±Infinity, arah tetap). Kolom ini
// SUDAH jadi sumbu default (created_at DESC via ListActivities) — varian ini
// HANYA menambah kemampuan flip ke ASC & jadi target klik header eksplisit;
// SAMA PERSIS filter ListActivities (context+F3+search), cuma keyset+ORDER BY
// beda arah.
func (q *Queries) ListActivitiesSortByDate(ctx context.Context, arg ListActivitiesSortByDateParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesSortByDate,
		arg.ContextFilter,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesSortByKind = `-- name: ListActivitiesSortByKind :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND activity_context = $1::text
  AND (
      NOT $2::boolean
      OR ($3::text = 'asc'
          AND (kind, id) > ($4::text, $5::bigint))
      OR ($3::text = 'desc'
          AND (kind, id) < ($4::text, $5::bigint))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND owner_id = $8)
  )
  AND ($9::text = '' OR subject ILIKE '%' || $9 || '%')
ORDER BY
  CASE WHEN $3::text = 'asc'  THEN kind END ASC,
  CASE WHEN $3::text = 'desc' THEN kind END DESC,
  CASE WHEN $3::text = 'asc'  THEN id END ASC,
  CASE WHEN $3::text = 'desc' THEN id END DESC
LIMIT $10
`

type ListActivitiesSortByKindParams struct {
	ContextFilter string `json:"context_filter"`
	HasCursor     bool   `json:"has_cursor"`
	Dir           string `json:"dir"`
	CursorVal     string `json:"cursor_val"`
	CursorID      int64  `json:"cursor_id"`
	ScopeAll      bool   `json:"scope_all"`
	IsOwn         bool   `json:"is_own"`
	Uid           *int64 `json:"uid"`
	Search        string `json:"search"`
	PageSize      int32  `json:"page_size"`
}

// BL-157j (sort per kolom Sales Activities): sort by Jenis (kind), RAW enum
// alfabetis (task/meeting/call/chat/note) — mirror keputusan "Status" Leads/
// "Tipe" Accounts: tak menduplikasi urutan tampil ke SQL. NOT NULL → kloning
// pola sederhana ListContactsSortByName (tanpa kerumitan NULL). SAMA PERSIS
// filter ListActivities (context+F3+search) — hanya ORDER BY/keyset beda.
func (q *Queries) ListActivitiesSortByKind(ctx context.Context, arg ListActivitiesSortByKindParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesSortByKind,
		arg.ContextFilter,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesSortByOwner = `-- name: ListActivitiesSortByOwner :many
SELECT activities.id, activities.tenant_id, activities.kind, activities.subject, activities.target_type, activities.target_id, activities.owner_id, activities.activity_context, activities.status, activities.notes, activities.due_date, activities.priority, activities.reminder_at, activities.start_at, activities.end_at, activities.all_day, activities.location, activities.meeting_type, activities.contact_id, activities.direction, activities.activity_at, activities.duration_min, activities.call_result, activities.email_from, activities.email_to, activities.email_status, activities.body, activities.engagement_type, activities.frequency, activities.channel, activities.scheduled_date, activities.next_due_date, activities.deleted_at, activities.created_by, activities.created_at, activities.updated_by, activities.updated_at FROM activities
LEFT JOIN users u ON u.id = owner_id
WHERE activities.deleted_at IS NULL
  AND activities.activity_context = $1::text
  AND (
      NOT $2::boolean
      OR ($3::text = 'asc' AND (
          (NOT $4::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NULL
                OR (COALESCE(NULLIF(u.name, ''), u.email), activities.id) > ($5::text, $6::bigint)))
          OR ($4::boolean
              AND COALESCE(NULLIF(u.name, ''), u.email) IS NULL AND activities.id > $6::bigint)
      ))
      OR ($3::text = 'desc' AND (
          ($4::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL OR activities.id < $6::bigint))
          OR (NOT $4::boolean AND COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL
              AND (COALESCE(NULLIF(u.name, ''), u.email), activities.id) < ($5::text, $6::bigint))
      ))
  )
  AND (
      $7::boolean
      OR ($8::boolean AND owner_id = $9)
  )
  AND ($10::text = '' OR subject ILIKE '%' || $10 || '%')
ORDER BY
  CASE WHEN $3::text = 'asc'  THEN COALESCE(NULLIF(u.name, ''), u.email) END ASC,
  CASE WHEN $3::text = 'desc' THEN COALESCE(NULLIF(u.name, ''), u.email) END DESC,
  CASE WHEN $3::text = 'asc'  THEN activities.id END ASC,
  CASE WHEN $3::text = 'desc' THEN activities.id END DESC
LIMIT $11
`

type ListActivitiesSortByOwnerParams struct {
	ContextFilter string `json:"context_filter"`
	HasCursor     bool   `json:"has_cursor"`
	Dir           string `json:"dir"`
	CursorIsNull  bool   `json:"cursor_is_null"`
	CursorVal     string `json:"cursor_val"`
	CursorID      int64  `json:"cursor_id"`
	ScopeAll      bool   `json:"scope_all"`
	IsOwn         bool   `json:"is_own"`
	Uid           *int64 `json:"uid"`
	Search        string `json:"search"`
	PageSize      int32  `json:"page_size"`
}

// BL-157j: sort by Pemilik (owner_id). Kunci sort HARUS
// COALESCE(NULLIF(u.name,”), u.email) — PERSIS logika tampil ownerName/
// memberNameMap (nama bila terisi, else email) — agar urutan tak menyimpang
// dari yang ditampilkan. NULLABLE (owner_id ON DELETE SET NULL). LEFT JOIN
// users: baris tanpa owner ATAU owner terhapus → owner_key NULL, masuk
// kelompok NULL (default Postgres). Mirror PERSIS ListDealsSortByOwner.
func (q *Queries) ListActivitiesSortByOwner(ctx context.Context, arg ListActivitiesSortByOwnerParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesSortByOwner,
		arg.ContextFilter,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesSortByStatus = `-- name: ListActivitiesSortByStatus :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND activity_context = $1::text
  AND (
      NOT $2::boolean
      OR ($3::text = 'asc' AND (
          (NOT $4::boolean
           AND (status IS NULL OR (status, id) > ($5::text, $6::bigint)))
          OR ($4::boolean AND status IS NULL AND id > $6::bigint)
      ))
      OR ($3::text = 'desc' AND (
          ($4::boolean
           AND (status IS NOT NULL OR id < $6::bigint))
          OR (NOT $4::boolean AND status IS NOT NULL
              AND (status, id) < ($5::text, $6::bigint))
      ))
  )
  AND (
      $7::boolean
      OR ($8::boolean AND owner_id = $9)
  )
  AND ($10::text = '' OR subject ILIKE '%' || $10 || '%')
ORDER BY
  CASE WHEN $3::text = 'asc'  THEN status END ASC,
  CASE WHEN $3::text = 'desc' THEN status END DESC,
  CASE WHEN $3::text = 'asc'  THEN id END ASC,
  CASE WHEN $3::text = 'desc' THEN id END DESC
LIMIT $11
`

type ListActivitiesSortByStatusParams struct {
	ContextFilter string `json:"context_filter"`
	HasCursor     bool   `json:"has_cursor"`
	Dir           string `json:"dir"`
	CursorIsNull  bool   `json:"cursor_is_null"`
	CursorVal     string `json:"cursor_val"`
	CursorID      int64  `json:"cursor_id"`
	ScopeAll      bool   `json:"scope_all"`
	IsOwn         bool   `json:"is_own"`
	Uid           *int64 `json:"uid"`
	Search        string `json:"search"`
	PageSize      int32  `json:"page_size"`
}

// BL-157j: sort by Status, RAW enum alfabetis — kolom mentah aktivitas, BUKAN
// derivasi seperti Renewals; mirror keputusan Tickets (Status sortable karena
// raw, bukan derivasi penuh). NULLABLE (call/note tanpa status) → pola
// null-aware SAMA dgn ListContactsSortByRole.
func (q *Queries) ListActivitiesSortByStatus(ctx context.Context, arg ListActivitiesSortByStatusParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesSortByStatus,
		arg.ContextFilter,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesSortBySubject = `-- name: ListActivitiesSortBySubject :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND activity_context = $1::text
  AND (
      NOT $2::boolean
      OR ($3::text = 'asc'
          AND (subject, id) > ($4::text, $5::bigint))
      OR ($3::text = 'desc'
          AND (subject, id) < ($4::text, $5::bigint))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND owner_id = $8)
  )
  AND ($9::text = '' OR subject ILIKE '%' || $9 || '%')
ORDER BY
  CASE WHEN $3::text = 'asc'  THEN subject END ASC,
  CASE WHEN $3::text = 'desc' THEN subject END DESC,
  CASE WHEN $3::text = 'asc'  THEN id END ASC,
  CASE WHEN $3::text = 'desc' THEN id END DESC
LIMIT $10
`

type ListActivitiesSortBySubjectParams struct {
	ContextFilter string `json:"context_filter"`
	HasCursor     bool   `json:"has_cursor"`
	Dir           string `json:"dir"`
	CursorVal     string `json:"cursor_val"`
	CursorID      int64  `json:"cursor_id"`
	ScopeAll      bool   `json:"scope_all"`
	IsOwn         bool   `json:"is_own"`
	Uid           *int64 `json:"uid"`
	Search        string `json:"search"`
	PageSize      int32  `json:"page_size"`
}

// BL-157j: sort by Subjek (subject), NOT NULL → kloning sederhana sama pola
// ListActivitiesSortByKind, kolom beda.
func (q *Queries) ListActivitiesSortBySubject(ctx context.Context, arg ListActivitiesSortBySubjectParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesSortBySubject,
		arg.ContextFilter,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivities = `-- name: ListAllActivities :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND owner_id = $5)
  )
  AND ($6::text = '' OR subject ILIKE '%' || $6 || '%')
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListAllActivitiesParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Daftar SEMUA aktivitas lintas-context (sales+cs+general) — untuk halaman
// "Activities" top-level (M7). Ownership F3 sama dengan ListActivities (scope_all
// atau is_own); tanpa context_filter agar semua modul terwakili. Keyset identik.
// search ” → tak menyaring; selain itu MEMPERSEMPIT subject (BL-6, ILIKE case-
// insensitive) di ATAS F3 — tak pernah melebarkan baris di luar cakupan.
func (q *Queries) ListAllActivities(ctx context.Context, arg ListAllActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivities,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivitiesSortByDate = `-- name: ListAllActivitiesSortByDate :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (created_at, id) > ($3::timestamptz, $4::bigint))
      OR ($2::text = 'desc'
          AND (created_at, id) < ($3::timestamptz, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND owner_id = $7)
  )
  AND ($8::text = '' OR subject ILIKE '%' || $8 || '%')
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN created_at END ASC,
  CASE WHEN $2::text = 'desc' THEN created_at END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $9
`

type ListAllActivitiesSortByDateParams struct {
	HasCursor bool               `json:"has_cursor"`
	Dir       string             `json:"dir"`
	CursorVal pgtype.Timestamptz `json:"cursor_val"`
	CursorID  int64              `json:"cursor_id"`
	ScopeAll  bool               `json:"scope_all"`
	IsOwn     bool               `json:"is_own"`
	Uid       *int64             `json:"uid"`
	Search    string             `json:"search"`
	PageSize  int32              `json:"page_size"`
}

// BL-157k: sort by Tanggal (created_at), arah dinamis — kloning
// ListActivitiesSortByDate TANPA context_filter. Dipakai JUGA sebagai sumbu
// DEFAULT feed terpadu (dir=desc) agar seluruh /activity-log memakai SATU
// mekanisme cursor (lihat all_activities_cursor.go) — tak ada lagi jalur
// ListAllActivities/pageCursor lama terpisah.
func (q *Queries) ListAllActivitiesSortByDate(ctx context.Context, arg ListAllActivitiesSortByDateParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivitiesSortByDate,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivitiesSortByKind = `-- name: ListAllActivitiesSortByKind :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (kind, id) > ($3::text, $4::bigint))
      OR ($2::text = 'desc'
          AND (kind, id) < ($3::text, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND owner_id = $7)
  )
  AND ($8::text = '' OR subject ILIKE '%' || $8 || '%')
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN kind END ASC,
  CASE WHEN $2::text = 'desc' THEN kind END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $9
`

type ListAllActivitiesSortByKindParams struct {
	HasCursor bool   `json:"has_cursor"`
	Dir       string `json:"dir"`
	CursorVal string `json:"cursor_val"`
	CursorID  int64  `json:"cursor_id"`
	ScopeAll  bool   `json:"scope_all"`
	IsOwn     bool   `json:"is_own"`
	Uid       *int64 `json:"uid"`
	Search    string `json:"search"`
	PageSize  int32  `json:"page_size"`
}

// BL-157k (sort per kolom Activity Log /activity-log, lengan activities): sort
// by Jenis (kind), kloning ListActivitiesSortByKind TANPA context_filter — mirror
// persis relasi ListAllActivities↔ListActivities (lintas-context, F3 sama).
func (q *Queries) ListAllActivitiesSortByKind(ctx context.Context, arg ListAllActivitiesSortByKindParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivitiesSortByKind,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivitiesSortByOwner = `-- name: ListAllActivitiesSortByOwner :many
SELECT activities.id, activities.tenant_id, activities.kind, activities.subject, activities.target_type, activities.target_id, activities.owner_id, activities.activity_context, activities.status, activities.notes, activities.due_date, activities.priority, activities.reminder_at, activities.start_at, activities.end_at, activities.all_day, activities.location, activities.meeting_type, activities.contact_id, activities.direction, activities.activity_at, activities.duration_min, activities.call_result, activities.email_from, activities.email_to, activities.email_status, activities.body, activities.engagement_type, activities.frequency, activities.channel, activities.scheduled_date, activities.next_due_date, activities.deleted_at, activities.created_by, activities.created_at, activities.updated_by, activities.updated_at FROM activities
LEFT JOIN users u ON u.id = owner_id
WHERE activities.deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NULL
                OR (COALESCE(NULLIF(u.name, ''), u.email), activities.id) > ($4::text, $5::bigint)))
          OR ($3::boolean
              AND COALESCE(NULLIF(u.name, ''), u.email) IS NULL AND activities.id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL OR activities.id < $5::bigint))
          OR (NOT $3::boolean AND COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL
              AND (COALESCE(NULLIF(u.name, ''), u.email), activities.id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND owner_id = $8)
  )
  AND ($9::text = '' OR subject ILIKE '%' || $9 || '%')
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN COALESCE(NULLIF(u.name, ''), u.email) END ASC,
  CASE WHEN $2::text = 'desc' THEN COALESCE(NULLIF(u.name, ''), u.email) END DESC,
  CASE WHEN $2::text = 'asc'  THEN activities.id END ASC,
  CASE WHEN $2::text = 'desc' THEN activities.id END DESC
LIMIT $10
`

type ListAllActivitiesSortByOwnerParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157k: sort by Pemilik, kloning ListActivitiesSortByOwner TANPA context_filter.
// Kunci sort SAMA (COALESCE(NULLIF(u.name,”), u.email)) — dipakai ownerName()
// Go-side utk aktivitas lintas-context juga (activityRowView, sama helper).
func (q *Queries) ListAllActivitiesSortByOwner(ctx context.Context, arg ListAllActivitiesSortByOwnerParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivitiesSortByOwner,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivitiesSortByStatus = `-- name: ListAllActivitiesSortByStatus :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (status IS NULL OR (status, id) > ($4::text, $5::bigint)))
          OR ($3::boolean AND status IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (status IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND status IS NOT NULL
              AND (status, id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND owner_id = $8)
  )
  AND ($9::text = '' OR subject ILIKE '%' || $9 || '%')
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN status END ASC,
  CASE WHEN $2::text = 'desc' THEN status END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $10
`

type ListAllActivitiesSortByStatusParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157k: sort by Status, kloning ListActivitiesSortByStatus TANPA context_filter.
func (q *Queries) ListAllActivitiesSortByStatus(ctx context.Context, arg ListAllActivitiesSortByStatusParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivitiesSortByStatus,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivitiesSortBySubject = `-- name: ListAllActivitiesSortBySubject :many
SELECT id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at FROM activities
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (subject, id) > ($3::text, $4::bigint))
      OR ($2::text = 'desc'
          AND (subject, id) < ($3::text, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND owner_id = $7)
  )
  AND ($8::text = '' OR subject ILIKE '%' || $8 || '%')
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN subject END ASC,
  CASE WHEN $2::text = 'desc' THEN subject END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $9
`

type ListAllActivitiesSortBySubjectParams struct {
	HasCursor bool   `json:"has_cursor"`
	Dir       string `json:"dir"`
	CursorVal string `json:"cursor_val"`
	CursorID  int64  `json:"cursor_id"`
	ScopeAll  bool   `json:"scope_all"`
	IsOwn     bool   `json:"is_own"`
	Uid       *int64 `json:"uid"`
	Search    string `json:"search"`
	PageSize  int32  `json:"page_size"`
}

// BL-157k: sort by Subjek, kloning ListActivitiesSortBySubject TANPA context_filter.
func (q *Queries) ListAllActivitiesSortBySubject(ctx context.Context, arg ListAllActivitiesSortBySubjectParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAllActivitiesSortBySubject,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Subject,
			&i.TargetType,
			&i.TargetID,
			&i.OwnerID,
			&i.ActivityContext,
			&i.Status,
			&i.Notes,
			&i.DueDate,
			&i.Priority,
			&i.ReminderAt,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.Location,
			&i.MeetingType,
			&i.ContactID,
			&i.Direction,
			&i.ActivityAt,
			&i.DurationMin,
			&i.CallResult,
			&i.EmailFrom,
			&i.EmailTo,
			&i.EmailStatus,
			&i.Body,
			&i.EngagementType,
			&i.Frequency,
			&i.Channel,
			&i.ScheduledDate,
			&i.NextDueDate,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteActivity = `-- name: SoftDeleteActivity :exec
UPDATE activities SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteActivityParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak aktivitas
// bertahan). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteActivity(ctx context.Context, arg SoftDeleteActivityParams) error {
	_, err := q.db.Exec(ctx, softDeleteActivity, arg.UpdatedBy, arg.ID)
	return err
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities SET
    subject      = $1,
    owner_id     = $2,
    notes        = $3,
    due_date     = $4,
    priority     = $5,
    reminder_at  = $6,
    contact_id   = $7,
    direction    = $8,
    activity_at  = $9,
    duration_min = $10,
    call_result  = $11,
    start_at     = $12,
    end_at       = $13,
    location     = $14,
    meeting_type = $15,
    channel      = $16,
    body         = $17,
    updated_by   = $18,
    updated_at   = now()
WHERE id = $19 AND deleted_at IS NULL
RETURNING id, tenant_id, kind, subject, target_type, target_id, owner_id, activity_context, status, notes, due_date, priority, reminder_at, start_at, end_at, all_day, location, meeting_type, contact_id, direction, activity_at, duration_min, call_result, email_from, email_to, email_status, body, engagement_type, frequency, channel, scheduled_date, next_due_date, deleted_at, created_by, created_at, updated_by, updated_at
`

type UpdateActivityParams struct {
	Subject     string             `json:"subject"`
	OwnerID     *int64             `json:"owner_id"`
	Notes       *string            `json:"notes"`
	DueDate     pgtype.Date        `json:"due_date"`
	Priority    *string            `json:"priority"`
	ReminderAt  pgtype.Timestamptz `json:"reminder_at"`
	ContactID   *int64             `json:"contact_id"`
	Direction   *string            `json:"direction"`
	ActivityAt  pgtype.Timestamptz `json:"activity_at"`
	DurationMin *int32             `json:"duration_min"`
	CallResult  *string            `json:"call_result"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	Location    *string            `json:"location"`
	MeetingType *string            `json:"meeting_type"`
	Channel     *string            `json:"channel"`
	Body        *string            `json:"body"`
	UpdatedBy   *int64             `json:"updated_by"`
	ID          int64              `json:"id"`
}

// Sunting aktivitas. kind & target TAK di sini: kind menentukan bentuk form
// (immutable saat edit), target ditetapkan saat create. status punya jalur
// khusus (UpdateActivityStatus) agar perpindahan terlihat sebagai aksi tersendiri.
func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.Subject,
		arg.OwnerID,
		arg.Notes,
		arg.DueDate,
		arg.Priority,
		arg.ReminderAt,
		arg.ContactID,
		arg.Direction,
		arg.ActivityAt,
		arg.DurationMin,
		arg.CallResult,
		arg.StartAt,
		arg.EndAt,
		arg.Location,
		arg.MeetingType,
		arg.Channel,
		arg.Body,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Subject,
		&i.TargetType,
		&i.TargetID,
		&i.OwnerID,
		&i.ActivityContext,
		&i.Status,
		&i.Notes,
		&i.DueDate,
		&i.Priority,
		&i.ReminderAt,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.Location,
		&i.MeetingType,
		&i.ContactID,
		&i.Direction,
		&i.ActivityAt,
		&i.DurationMin,
		&i.CallResult,
		&i.EmailFrom,
		&i.EmailTo,
		&i.EmailStatus,
		&i.Body,
		&i.EngagementType,
		&i.Frequency,
		&i.Channel,
		&i.ScheduledDate,
		&i.NextDueDate,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActivityStatus = `-- name: UpdateActivityStatus :exec
UPDATE activities SET
    status     = $1,
    updated_by = $2,
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateActivityStatusParams struct {
	Status    *string `json:"status"`
	UpdatedBy *int64  `json:"updated_by"`
	ID        int64   `json:"id"`
}

// Ubah status (aksi tersendiri, cermin UpdateDealStage). Validasi enum di handler
// (allowlist) + CHECK DB sebagai jaring terakhir.
func (q *Queries) UpdateActivityStatus(ctx context.Context, arg UpdateActivityStatusParams) error {
	_, err := q.db.Exec(ctx, updateActivityStatus, arg.Status, arg.UpdatedBy, arg.ID)
	return err
}
