// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAccountPrimaryContact = `-- name: ClearAccountPrimaryContact :exec
UPDATE contacts SET is_primary_contact = false, updated_by = $1, updated_at = now()
WHERE account_id = $2 AND is_primary_contact AND deleted_at IS NULL
`

type ClearAccountPrimaryContactParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	AccountID int64  `json:"account_id"`
}

// Lepas penanda utama dari SEMUA kontak hidup satu desa. Dipanggil SEBELUM
// memasang primary baru (create/update/set-primary) supaya idx_contacts_primary
// (maks 1 utama per desa) tak pernah dilanggar. Idempotent: nol baris bila belum
// ada utama.
func (q *Queries) ClearAccountPrimaryContact(ctx context.Context, arg ClearAccountPrimaryContactParams) error {
	_, err := q.db.Exec(ctx, clearAccountPrimaryContact, arg.UpdatedBy, arg.AccountID)
	return err
}

const countContactsByAccount = `-- name: CountContactsByAccount :one
SELECT COUNT(*) FROM contacts
WHERE account_id = $1 AND deleted_at IS NULL
`

// Jumlah kontak hidup satu desa — untuk badge/ringkasan di detail desa. Murah:
// idx_contacts_account (partial WHERE deleted_at IS NULL) melayaninya langsung.
func (q *Queries) CountContactsByAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countContactsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one

INSERT INTO contacts (
    tenant_id, account_id, contact_owner, reports_to_id,
    first_name, last_name, salutation, job_title, position_category, contact_role,
    is_primary_contact, is_technical_contact, term_period,
    mobile_phone, whatsapp_number, office_phone, email, preferred_channel,
    mailing_address, city, postal_code,
    email_opt_out, do_not_contact,
    created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18,
    $19, $20, $21,
    $22, $23,
    $24
)
RETURNING id, tenant_id, account_id, contact_owner, reports_to_id, first_name, last_name, salutation, job_title, position_category, contact_role, is_primary_contact, is_technical_contact, term_period, mobile_phone, whatsapp_number, office_phone, email, preferred_channel, mailing_address, city, postal_code, email_opt_out, do_not_contact, deleted_at, created_by, created_at, updated_by, updated_at
`

type CreateContactParams struct {
	TenantID           int64   `json:"tenant_id"`
	AccountID          int64   `json:"account_id"`
	ContactOwner       *int64  `json:"contact_owner"`
	ReportsToID        *int64  `json:"reports_to_id"`
	FirstName          string  `json:"first_name"`
	LastName           *string `json:"last_name"`
	Salutation         *string `json:"salutation"`
	JobTitle           *string `json:"job_title"`
	PositionCategory   *string `json:"position_category"`
	ContactRole        *string `json:"contact_role"`
	IsPrimaryContact   bool    `json:"is_primary_contact"`
	IsTechnicalContact bool    `json:"is_technical_contact"`
	TermPeriod         *string `json:"term_period"`
	MobilePhone        *string `json:"mobile_phone"`
	WhatsappNumber     *string `json:"whatsapp_number"`
	OfficePhone        *string `json:"office_phone"`
	Email              *string `json:"email"`
	PreferredChannel   *string `json:"preferred_channel"`
	MailingAddress     *string `json:"mailing_address"`
	City               *string `json:"city"`
	PostalCode         *string `json:"postal_code"`
	EmailOptOut        bool    `json:"email_opt_out"`
	DoNotContact       bool    `json:"do_not_contact"`
	CreatedBy          *int64  `json:"created_by"`
}

// contacts.sql — orang di dalam sebuah desa (Contact), 1:N ke accounts. Isolasi
// WORKSPACE ditegakkan RLS (GUC app.tenant_id di WithTenant, tenant_id di-AND-kan
// otomatis). Isolasi ANTAR-DESA (F3) TIDAK punya filter sendiri di sini: kontak
// MEWARISI kepemilikan desa induknya (docs/crm/tasks.md §Modul 3). Maka:
//   - daftar per-desa (ListContactsByAccount) tak menyaring ownership sama sekali —
//     handler sudah menjaga bahwa desa induknya boleh dilihat aktor (loadOwnedAccount);
//     begitu lolos, SEMUA kontak desa itu tampil.
//   - daftar global (ListContacts) menyaring lewat kolom ownership DESA INDUK
//     (JOIN accounts), memakai flag yang SAMA dengan ListAccounts — sumber tunggal
//     AccountsListFilter. "Kontak siapa yang tampil" = "desa siapa yang tampil".
//
// Maks 1 kontak utama per desa dijaga idx_contacts_primary (partial UNIQUE). Set-
// primary WAJIB dua langkah dalam satu tx: kosongkan primary lama dulu, baru pasang
// yang baru — kalau tidak, INSERT/UPDATE bertabrakan dengan index (satu tx, satu
// tenant, jadi tak ada balapan antar-request di jalur ini).
// Buat kontak. account_id mengikat ke desa induk (RLS memverifikasi tenant_id =
// GUC lewat FK + WITH CHECK). is_primary_contact di-set pemanggil SETELAH
// mengosongkan primary lama (ClearAccountPrimaryContact) agar tak melanggar index.
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.TenantID,
		arg.AccountID,
		arg.ContactOwner,
		arg.ReportsToID,
		arg.FirstName,
		arg.LastName,
		arg.Salutation,
		arg.JobTitle,
		arg.PositionCategory,
		arg.ContactRole,
		arg.IsPrimaryContact,
		arg.IsTechnicalContact,
		arg.TermPeriod,
		arg.MobilePhone,
		arg.WhatsappNumber,
		arg.OfficePhone,
		arg.Email,
		arg.PreferredChannel,
		arg.MailingAddress,
		arg.City,
		arg.PostalCode,
		arg.EmailOptOut,
		arg.DoNotContact,
		arg.CreatedBy,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.ContactOwner,
		&i.ReportsToID,
		&i.FirstName,
		&i.LastName,
		&i.Salutation,
		&i.JobTitle,
		&i.PositionCategory,
		&i.ContactRole,
		&i.IsPrimaryContact,
		&i.IsTechnicalContact,
		&i.TermPeriod,
		&i.MobilePhone,
		&i.WhatsappNumber,
		&i.OfficePhone,
		&i.Email,
		&i.PreferredChannel,
		&i.MailingAddress,
		&i.City,
		&i.PostalCode,
		&i.EmailOptOut,
		&i.DoNotContact,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, tenant_id, account_id, contact_owner, reports_to_id, first_name, last_name, salutation, job_title, position_category, contact_role, is_primary_contact, is_technical_contact, term_period, mobile_phone, whatsapp_number, office_phone, email, preferred_channel, mailing_address, city, postal_code, email_opt_out, do_not_contact, deleted_at, created_by, created_at, updated_by, updated_at FROM contacts
WHERE id = $1 AND deleted_at IS NULL
`

// Satu kontak hidup. RLS menjamin tenant_id; deleted_at menyembunyikan yang
// ter-soft-delete. Tak menerapkan ownership — pemanggil (handler) memutuskan lewat
// desa INDUK apakah aktor boleh membukanya (kontak mewarisi kepemilikan desa).
func (q *Queries) GetContact(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.ContactOwner,
		&i.ReportsToID,
		&i.FirstName,
		&i.LastName,
		&i.Salutation,
		&i.JobTitle,
		&i.PositionCategory,
		&i.ContactRole,
		&i.IsPrimaryContact,
		&i.IsTechnicalContact,
		&i.TermPeriod,
		&i.MobilePhone,
		&i.WhatsappNumber,
		&i.OfficePhone,
		&i.Email,
		&i.PreferredChannel,
		&i.MailingAddress,
		&i.City,
		&i.PostalCode,
		&i.EmailOptOut,
		&i.DoNotContact,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.tenant_id, c.account_id, c.contact_owner, c.reports_to_id, c.first_name, c.last_name, c.salutation, c.job_title, c.position_category, c.contact_role, c.is_primary_contact, c.is_technical_contact, c.term_period, c.mobile_phone, c.whatsapp_number, c.office_phone, c.email, c.preferred_channel, c.mailing_address, c.city, c.postal_code, c.email_opt_out, c.do_not_contact, c.deleted_at, c.created_by, c.created_at, c.updated_by, c.updated_at, a.village_name FROM contacts c
JOIN accounts a ON a.id = c.account_id AND a.deleted_at IS NULL
WHERE c.deleted_at IS NULL
  AND (c.created_at, c.id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND a.account_owner = $5)
      OR ($6::boolean AND (a.assigned_csm = $5 OR a.backup_csm = $5))
  )
  AND (
      $7::text = ''
      OR (c.first_name || ' ' || coalesce(c.last_name, '')) ILIKE '%' || $7 || '%'
      OR a.village_name ILIKE '%' || $7 || '%'
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $8
`

type ListContactsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsSales         bool               `json:"is_sales"`
	Uid             *int64             `json:"uid"`
	IsCsm           bool               `json:"is_csm"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

type ListContactsRow struct {
	ID                 int64              `json:"id"`
	TenantID           int64              `json:"tenant_id"`
	AccountID          int64              `json:"account_id"`
	ContactOwner       *int64             `json:"contact_owner"`
	ReportsToID        *int64             `json:"reports_to_id"`
	FirstName          string             `json:"first_name"`
	LastName           *string            `json:"last_name"`
	Salutation         *string            `json:"salutation"`
	JobTitle           *string            `json:"job_title"`
	PositionCategory   *string            `json:"position_category"`
	ContactRole        *string            `json:"contact_role"`
	IsPrimaryContact   bool               `json:"is_primary_contact"`
	IsTechnicalContact bool               `json:"is_technical_contact"`
	TermPeriod         *string            `json:"term_period"`
	MobilePhone        *string            `json:"mobile_phone"`
	WhatsappNumber     *string            `json:"whatsapp_number"`
	OfficePhone        *string            `json:"office_phone"`
	Email              *string            `json:"email"`
	PreferredChannel   *string            `json:"preferred_channel"`
	MailingAddress     *string            `json:"mailing_address"`
	City               *string            `json:"city"`
	PostalCode         *string            `json:"postal_code"`
	EmailOptOut        bool               `json:"email_opt_out"`
	DoNotContact       bool               `json:"do_not_contact"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy          *int64             `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedBy          *int64             `json:"updated_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	VillageName        string             `json:"village_name"`
}

// Daftar kontak LINTAS-desa, keyset + filter kepemilikan DESA INDUK (bukan filter
// kontak sendiri). JOIN accounts membawa kolom ownership desa; flag scope_all/
// is_sales/is_csm identik dengan ListAccounts (AccountsListFilter) — "kontak siapa
// yang tampil" diturunkan dari "desa siapa yang tampil", satu kebenaran.
// Ketiganya false (Support/role kosong/liar) → NOL baris (fail-closed).
// a.village_name dibawa untuk kolom "Desa" di daftar global (di daftar per-desa
// redundan — sudah di judul halaman — jadi query per-desa tak mengambilnya).
//
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership desa induk — tak pernah melebarkan baris. Nama
// kontak dirangkai (first_name + last_name; coalesce agar last_name NULL tak
// meng-NULL-kan seluruh ekspresi) → satu ekspresi mencakup nama-depan, nama-
// belakang, maupun nama lengkap; plus a.village_name (desa induk). PII (telepon/
// email) tak dijadikan kunci — search bukan jalur enumerasi data tersamar.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsSales,
		arg.Uid,
		arg.IsCsm,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsRow{}
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.ContactOwner,
			&i.ReportsToID,
			&i.FirstName,
			&i.LastName,
			&i.Salutation,
			&i.JobTitle,
			&i.PositionCategory,
			&i.ContactRole,
			&i.IsPrimaryContact,
			&i.IsTechnicalContact,
			&i.TermPeriod,
			&i.MobilePhone,
			&i.WhatsappNumber,
			&i.OfficePhone,
			&i.Email,
			&i.PreferredChannel,
			&i.MailingAddress,
			&i.City,
			&i.PostalCode,
			&i.EmailOptOut,
			&i.DoNotContact,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.VillageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByAccount = `-- name: ListContactsByAccount :many
SELECT id, tenant_id, account_id, contact_owner, reports_to_id, first_name, last_name, salutation, job_title, position_category, contact_role, is_primary_contact, is_technical_contact, term_period, mobile_phone, whatsapp_number, office_phone, email, preferred_channel, mailing_address, city, postal_code, email_opt_out, do_not_contact, deleted_at, created_by, created_at, updated_by, updated_at FROM contacts
WHERE account_id = $1
  AND deleted_at IS NULL
  AND (created_at, id) < ($2::timestamptz, $3::bigint)
ORDER BY is_primary_contact DESC, created_at DESC, id DESC
LIMIT $4
`

type ListContactsByAccountParams struct {
	AccountID       int64              `json:"account_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

// Kontak SATU desa, keyset (created_at DESC, id DESC). TANPA filter ownership:
// gerbangnya adalah desa induk (handler memvalidasi via loadOwnedAccount sebelum
// memanggil ini). Kontak utama diangkat ke atas agar penanda primary langsung
// terlihat tanpa menggeser urutan kronologis baris lainnya.
func (q *Queries) ListContactsByAccount(ctx context.Context, arg ListContactsByAccountParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByAccount,
		arg.AccountID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.ContactOwner,
			&i.ReportsToID,
			&i.FirstName,
			&i.LastName,
			&i.Salutation,
			&i.JobTitle,
			&i.PositionCategory,
			&i.ContactRole,
			&i.IsPrimaryContact,
			&i.IsTechnicalContact,
			&i.TermPeriod,
			&i.MobilePhone,
			&i.WhatsappNumber,
			&i.OfficePhone,
			&i.Email,
			&i.PreferredChannel,
			&i.MailingAddress,
			&i.City,
			&i.PostalCode,
			&i.EmailOptOut,
			&i.DoNotContact,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryContact = `-- name: SetPrimaryContact :exec
UPDATE contacts SET is_primary_contact = true, updated_by = $1, updated_at = now()
WHERE id = $2 AND account_id = $3 AND deleted_at IS NULL
`

type SetPrimaryContactParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
}

// Angkat SATU kontak jadi utama. Pemanggil WAJIB memanggil ClearAccountPrimaryContact
// lebih dulu (satu tx) — index memblokir dua utama. account_id ikut di WHERE sebagai
// sabuk pengaman: kontak yang bukan milik desa itu tak bisa diangkat lewat jalurnya.
func (q *Queries) SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error {
	_, err := q.db.Exec(ctx, setPrimaryContact, arg.UpdatedBy, arg.ID, arg.AccountID)
	return err
}

const softDeleteContact = `-- name: SoftDeleteContact :exec
UPDATE contacts SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteContactParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
// entitas lain tak putus). Idempotent: hanya baris hidup. Kontak utama yang dihapus
// membebaskan slot primary (index-nya partial WHERE deleted_at IS NULL).
func (q *Queries) SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error {
	_, err := q.db.Exec(ctx, softDeleteContact, arg.UpdatedBy, arg.ID)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET
    contact_owner        = $1,
    reports_to_id        = $2,
    first_name           = $3,
    last_name            = $4,
    salutation           = $5,
    job_title            = $6,
    position_category    = $7,
    contact_role         = $8,
    is_primary_contact   = $9,
    is_technical_contact = $10,
    term_period          = $11,
    mobile_phone         = $12,
    whatsapp_number      = $13,
    office_phone         = $14,
    email                = $15,
    preferred_channel    = $16,
    mailing_address      = $17,
    city                 = $18,
    postal_code          = $19,
    email_opt_out        = $20,
    do_not_contact       = $21,
    updated_by           = $22,
    updated_at           = now()
WHERE id = $23 AND deleted_at IS NULL
RETURNING id, tenant_id, account_id, contact_owner, reports_to_id, first_name, last_name, salutation, job_title, position_category, contact_role, is_primary_contact, is_technical_contact, term_period, mobile_phone, whatsapp_number, office_phone, email, preferred_channel, mailing_address, city, postal_code, email_opt_out, do_not_contact, deleted_at, created_by, created_at, updated_by, updated_at
`

type UpdateContactParams struct {
	ContactOwner       *int64  `json:"contact_owner"`
	ReportsToID        *int64  `json:"reports_to_id"`
	FirstName          string  `json:"first_name"`
	LastName           *string `json:"last_name"`
	Salutation         *string `json:"salutation"`
	JobTitle           *string `json:"job_title"`
	PositionCategory   *string `json:"position_category"`
	ContactRole        *string `json:"contact_role"`
	IsPrimaryContact   bool    `json:"is_primary_contact"`
	IsTechnicalContact bool    `json:"is_technical_contact"`
	TermPeriod         *string `json:"term_period"`
	MobilePhone        *string `json:"mobile_phone"`
	WhatsappNumber     *string `json:"whatsapp_number"`
	OfficePhone        *string `json:"office_phone"`
	Email              *string `json:"email"`
	PreferredChannel   *string `json:"preferred_channel"`
	MailingAddress     *string `json:"mailing_address"`
	City               *string `json:"city"`
	PostalCode         *string `json:"postal_code"`
	EmailOptOut        bool    `json:"email_opt_out"`
	DoNotContact       bool    `json:"do_not_contact"`
	UpdatedBy          *int64  `json:"updated_by"`
	ID                 int64   `json:"id"`
}

// Sunting kontak. is_primary_contact di-set pemanggil setelah mengosongkan primary
// lama (ClearAccountPrimaryContact) bila dinaikkan jadi utama. account_id TIDAK
// diubah di sini — memindahkan kontak antar-desa adalah aksi lain (belum ada).
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ContactOwner,
		arg.ReportsToID,
		arg.FirstName,
		arg.LastName,
		arg.Salutation,
		arg.JobTitle,
		arg.PositionCategory,
		arg.ContactRole,
		arg.IsPrimaryContact,
		arg.IsTechnicalContact,
		arg.TermPeriod,
		arg.MobilePhone,
		arg.WhatsappNumber,
		arg.OfficePhone,
		arg.Email,
		arg.PreferredChannel,
		arg.MailingAddress,
		arg.City,
		arg.PostalCode,
		arg.EmailOptOut,
		arg.DoNotContact,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.ContactOwner,
		&i.ReportsToID,
		&i.FirstName,
		&i.LastName,
		&i.Salutation,
		&i.JobTitle,
		&i.PositionCategory,
		&i.ContactRole,
		&i.IsPrimaryContact,
		&i.IsTechnicalContact,
		&i.TermPeriod,
		&i.MobilePhone,
		&i.WhatsappNumber,
		&i.OfficePhone,
		&i.Email,
		&i.PreferredChannel,
		&i.MailingAddress,
		&i.City,
		&i.PostalCode,
		&i.EmailOptOut,
		&i.DoNotContact,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
