// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDealsByAccount = `-- name: CountDealsByAccount :one
SELECT COUNT(*) FROM deals
WHERE account_id = $1 AND deleted_at IS NULL
`

// Jumlah deal hidup satu desa — label chip "Terkait" di detail Account. Mirror
// CountContactsByAccount.
func (q *Queries) CountDealsByAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDealsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeal = `-- name: CreateDeal :one

INSERT INTO deals (
    tenant_id, entity_code, deal_name, account_id,
    deal_owner, primary_contact_id, plan_requested_id,
    deal_type, stage, amount, probability,
    expected_close_date, forecast_category, next_step, subscription_term,
    created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13,
    $14, $15,
    $16
)
RETURNING id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at
`

type CreateDealParams struct {
	TenantID          int64          `json:"tenant_id"`
	EntityCode        *string        `json:"entity_code"`
	DealName          string         `json:"deal_name"`
	AccountID         int64          `json:"account_id"`
	DealOwner         *int64         `json:"deal_owner"`
	PrimaryContactID  *int64         `json:"primary_contact_id"`
	PlanRequestedID   *int64         `json:"plan_requested_id"`
	DealType          *string        `json:"deal_type"`
	Stage             string         `json:"stage"`
	Amount            pgtype.Numeric `json:"amount"`
	Probability       *int16         `json:"probability"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	ForecastCategory  *string        `json:"forecast_category"`
	NextStep          *string        `json:"next_step"`
	SubscriptionTerm  *string        `json:"subscription_term"`
	CreatedBy         *int64         `json:"created_by"`
}

// deals.sql — pipeline Sales (Deal). Isolasi WORKSPACE ditegakkan RLS (GUC
// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
// lewat flag ownership di ListDeals/ListDealsForPipeline — lihat ownership.go.
// Ownership deal memakai SATU kolom (deal_owner).
//
// entity_code (DEAL-001) dialokasikan di GenerateEntityCode DALAM tx create.
// account_id NN: deal selalu menempel ke satu desa. Deal hasil konversi lead dibuat
// di tx konversi (bersama account+contact) — lihat handler.
// Buat deal. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.TenantID,
		arg.EntityCode,
		arg.DealName,
		arg.AccountID,
		arg.DealOwner,
		arg.PrimaryContactID,
		arg.PlanRequestedID,
		arg.DealType,
		arg.Stage,
		arg.Amount,
		arg.Probability,
		arg.ExpectedCloseDate,
		arg.ForecastCategory,
		arg.NextStep,
		arg.SubscriptionTerm,
		arg.CreatedBy,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const dealPipelineStats = `-- name: DealPipelineStats :one
SELECT
    COALESCE(COUNT(*) FILTER (
        WHERE stage NOT IN ('Closed Won','Closed Lost')), 0)::bigint AS open_count,
    COALESCE(SUM(amount) FILTER (
        WHERE stage NOT IN ('Closed Won','Closed Lost')), 0)::numeric AS pipeline_value,
    COALESCE(COUNT(*) FILTER (WHERE stage = 'Closed Won'), 0)::bigint  AS won_count,
    COALESCE(COUNT(*) FILTER (WHERE stage = 'Closed Lost'), 0)::bigint AS lost_count
FROM deals
WHERE deleted_at IS NULL
  AND (
      $1::boolean
      OR ($2::boolean AND deal_owner = $3)
  )
`

type DealPipelineStatsParams struct {
	ScopeAll bool   `json:"scope_all"`
	IsOwn    bool   `json:"is_own"`
	Uid      *int64 `json:"uid"`
}

type DealPipelineStatsRow struct {
	OpenCount     int64          `json:"open_count"`
	PipelineValue pgtype.Numeric `json:"pipeline_value"`
	WonCount      int64          `json:"won_count"`
	LostCount     int64          `json:"lost_count"`
}

// KPI ringkas pipeline dalam cakupan ownership (satu round-trip, bukan hitung di
// Go atas seluruh baris). COALESCE(...)::bigint/::numeric membungkus agregat agar
// sqlc tak meng-emit interface{} (gotcha #14). Win rate dihitung di Go dari
// won_count/(won_count+lost_count) — pembagian nol ditangani di sana.
func (q *Queries) DealPipelineStats(ctx context.Context, arg DealPipelineStatsParams) (DealPipelineStatsRow, error) {
	row := q.db.QueryRow(ctx, dealPipelineStats, arg.ScopeAll, arg.IsOwn, arg.Uid)
	var i DealPipelineStatsRow
	err := row.Scan(
		&i.OpenCount,
		&i.PipelineValue,
		&i.WonCount,
		&i.LostCount,
	)
	return i, err
}

const getDeal = `-- name: GetDeal :one
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at FROM deals
WHERE id = $1 AND deleted_at IS NULL
`

// Satu deal hidup. RLS menjamin tenant_id; ownership diputuskan handler
// (DealsListFilter.Allows) atas baris.
func (q *Queries) GetDeal(ctx context.Context, id int64) (Deal, error) {
	row := q.db.QueryRow(ctx, getDeal, id)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestDealForAccount = `-- name: GetLatestDealForAccount :one
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at FROM deals
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Deal TERBARU satu desa (chip "Terkait" di detail Account). Tanpa filter
// ownership: gerbangnya desa induk (handler via loadOwnedAccount), pola sama
// ListContactsByAccount. pgx.ErrNoRows = desa belum punya deal sama sekali.
func (q *Queries) GetLatestDealForAccount(ctx context.Context, accountID int64) (Deal, error) {
	row := q.db.QueryRow(ctx, getLatestDealForAccount, accountID)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeals = `-- name: ListDeals :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at FROM deals
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND deal_owner = $5)
  )
  AND ($6::text = '' OR stage = $6::text)
  AND (
      $7::text = ''
      OR deal_name ILIKE '%' || $7 || '%'
      OR entity_code ILIKE '%' || $7 || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListDealsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	StageFilter     string             `json:"stage_filter"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Daftar deal (tampilan Tabel), keyset (created_at DESC, id DESC) + filter
// ownership F3 + filter stage opsional. Dua flag ownership (sumber SATU dengan
// DealsListFilter): scope_all → semua; is_own → deal_owner = uid; keduanya false
// → NOL baris (fail-closed). stage_filter ” → semua stage.
//
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership+stage — tak pernah melebarkan baris. Hanya kolom
// tak-tersamar yang tampil di tabel (deal_name + entity_code); nilai ARR tersamar
// tak dijadikan kunci cari. Papan Kanban (ListDealsForPipeline) TAK ikut — di luar
// lingkup slice ini (board terbatas LIMIT, bukan daftar berkeyset).
func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDeals,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsForPipeline = `-- name: ListDealsForPipeline :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at FROM deals
WHERE deleted_at IS NULL
  AND (
      $1::boolean
      OR ($2::boolean AND deal_owner = $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListDealsForPipelineParams struct {
	ScopeAll bool   `json:"scope_all"`
	IsOwn    bool   `json:"is_own"`
	Uid      *int64 `json:"uid"`
	PageSize int32  `json:"page_size"`
}

// Papan Kanban: seluruh deal hidup dalam cakupan ownership, diurutkan agar kartu
// rapi per-stage lalu terbaru dulu. Di-bucket per-stage di handler (bukan N query
// per kolom). LIMIT membatasi papan agar tak memuat seluruh tabel (guardrail
// pagination); deal di luar batas tetap terlihat lewat tampilan Tabel berkeyset.
func (q *Queries) ListDealsForPipeline(ctx context.Context, arg ListDealsForPipelineParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsForPipeline,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDealCreatedSubscription = `-- name: SetDealCreatedSubscription :exec
UPDATE deals SET
    created_subscription_id = $1,
    updated_by              = $2,
    updated_at              = now()
WHERE id = $3 AND deleted_at IS NULL
`

type SetDealCreatedSubscriptionParams struct {
	CreatedSubscriptionID *int64 `json:"created_subscription_id"`
	UpdatedBy             *int64 `json:"updated_by"`
	ID                    int64  `json:"id"`
}

// Tautkan deal ke langganan hasil create-from-deal (deals.created_subscription_id;
// FK ditutup di migrasi 00012). Dipanggil dalam tx yang SAMA dgn CreateSubscription
// agar deal Closed Won selalu menunjuk langganan yang lahir darinya (atomik).
func (q *Queries) SetDealCreatedSubscription(ctx context.Context, arg SetDealCreatedSubscriptionParams) error {
	_, err := q.db.Exec(ctx, setDealCreatedSubscription, arg.CreatedSubscriptionID, arg.UpdatedBy, arg.ID)
	return err
}

const softDeleteDeal = `-- name: SoftDeleteDeal :exec
UPDATE deals SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteDealParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
// leads.converted_deal_id tak putus). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) error {
	_, err := q.db.Exec(ctx, softDeleteDeal, arg.UpdatedBy, arg.ID)
	return err
}

const updateDeal = `-- name: UpdateDeal :one
UPDATE deals SET
    deal_name           = $1,
    account_id          = $2,
    deal_owner          = $3,
    primary_contact_id  = $4,
    plan_requested_id   = $5,
    deal_type           = $6,
    amount              = $7,
    probability         = $8,
    expected_close_date = $9,
    forecast_category   = $10,
    next_step           = $11,
    subscription_term   = $12,
    competitor          = $13,
    updated_by          = $14,
    updated_at          = now()
WHERE id = $15 AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at
`

type UpdateDealParams struct {
	DealName          string         `json:"deal_name"`
	AccountID         int64          `json:"account_id"`
	DealOwner         *int64         `json:"deal_owner"`
	PrimaryContactID  *int64         `json:"primary_contact_id"`
	PlanRequestedID   *int64         `json:"plan_requested_id"`
	DealType          *string        `json:"deal_type"`
	Amount            pgtype.Numeric `json:"amount"`
	Probability       *int16         `json:"probability"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	ForecastCategory  *string        `json:"forecast_category"`
	NextStep          *string        `json:"next_step"`
	SubscriptionTerm  *string        `json:"subscription_term"`
	Competitor        *string        `json:"competitor"`
	UpdatedBy         *int64         `json:"updated_by"`
	ID                int64          `json:"id"`
}

// Sunting profil deal. entity_code, stage, dan hasil (win_loss_reason/closed_date)
// TAK di sini: stage punya jalur khusus (UpdateDealStage) agar perpindahan pipeline
// terlihat sebagai aksi tersendiri, bukan efek samping edit.
func (q *Queries) UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDeal,
		arg.DealName,
		arg.AccountID,
		arg.DealOwner,
		arg.PrimaryContactID,
		arg.PlanRequestedID,
		arg.DealType,
		arg.Amount,
		arg.Probability,
		arg.ExpectedCloseDate,
		arg.ForecastCategory,
		arg.NextStep,
		arg.SubscriptionTerm,
		arg.Competitor,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDealStage = `-- name: UpdateDealStage :exec
UPDATE deals SET
    stage           = $1,
    win_loss_reason = $2,
    loss_notes      = $3,
    closed_date     = CASE
        WHEN $1 IN ('Closed Won','Closed Lost') THEN CURRENT_DATE
        ELSE NULL END,
    updated_by      = $4,
    updated_at      = now()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateDealStageParams struct {
	Stage         string  `json:"stage"`
	WinLossReason *string `json:"win_loss_reason"`
	LossNotes     *string `json:"loss_notes"`
	UpdatedBy     *int64  `json:"updated_by"`
	ID            int64   `json:"id"`
}

// Pindah stage pipeline (aksi tersendiri). closed_date/win_loss_reason/loss_notes
// diisi saat Closed Won/Lost — validasi "Closed Lost wajib win_loss_reason" di
// handler (bukan constraint DB agar pesan bisa diperbaiki user). closed_date =
// CURRENT_DATE bila stage terminal, NULL bila dibuka kembali ke stage aktif.
func (q *Queries) UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) error {
	_, err := q.db.Exec(ctx, updateDealStage,
		arg.Stage,
		arg.WinLossReason,
		arg.LossNotes,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
