// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDealsByAccount = `-- name: CountDealsByAccount :one
SELECT COUNT(*) FROM deals
WHERE account_id = $1 AND deleted_at IS NULL
`

// Jumlah deal hidup satu desa — label chip "Terkait" di detail Account. Mirror
// CountContactsByAccount.
func (q *Queries) CountDealsByAccount(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDealsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeal = `-- name: CreateDeal :one

INSERT INTO deals (
    tenant_id, entity_code, deal_name, account_id,
    deal_owner, primary_contact_id, plan_requested_id,
    deal_type, stage, amount, probability,
    expected_close_date, forecast_category, next_step, subscription_term,
    created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13,
    $14, $15,
    $16
)
RETURNING id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code
`

type CreateDealParams struct {
	TenantID          int64          `json:"tenant_id"`
	EntityCode        *string        `json:"entity_code"`
	DealName          string         `json:"deal_name"`
	AccountID         int64          `json:"account_id"`
	DealOwner         *int64         `json:"deal_owner"`
	PrimaryContactID  *int64         `json:"primary_contact_id"`
	PlanRequestedID   *int64         `json:"plan_requested_id"`
	DealType          *string        `json:"deal_type"`
	Stage             string         `json:"stage"`
	Amount            pgtype.Numeric `json:"amount"`
	Probability       *int16         `json:"probability"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	ForecastCategory  *string        `json:"forecast_category"`
	NextStep          *string        `json:"next_step"`
	SubscriptionTerm  *string        `json:"subscription_term"`
	CreatedBy         *int64         `json:"created_by"`
}

// deals.sql — pipeline Sales (Deal). Isolasi WORKSPACE ditegakkan RLS (GUC
// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
// lewat flag ownership di ListDeals/ListDealsForPipeline — lihat ownership.go.
// Ownership deal memakai SATU kolom (deal_owner).
//
// entity_code (DEAL-001) dialokasikan di GenerateEntityCode DALAM tx create.
// account_id NN: deal selalu menempel ke satu desa. Deal hasil konversi lead dibuat
// di tx konversi (bersama account+contact) — lihat handler.
// Buat deal. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.TenantID,
		arg.EntityCode,
		arg.DealName,
		arg.AccountID,
		arg.DealOwner,
		arg.PrimaryContactID,
		arg.PlanRequestedID,
		arg.DealType,
		arg.Stage,
		arg.Amount,
		arg.Probability,
		arg.ExpectedCloseDate,
		arg.ForecastCategory,
		arg.NextStep,
		arg.SubscriptionTerm,
		arg.CreatedBy,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.LossReasonCode,
	)
	return i, err
}

const dealPipelineStats = `-- name: DealPipelineStats :one
SELECT
    COALESCE(COUNT(*) FILTER (
        WHERE stage NOT IN ('Closed Won','Closed Lost')), 0)::bigint AS open_count,
    COALESCE(SUM(amount) FILTER (
        WHERE stage NOT IN ('Closed Won','Closed Lost')), 0)::numeric AS pipeline_value,
    COALESCE(COUNT(*) FILTER (WHERE stage = 'Closed Won'), 0)::bigint  AS won_count,
    COALESCE(COUNT(*) FILTER (WHERE stage = 'Closed Lost'), 0)::bigint AS lost_count
FROM deals
WHERE deleted_at IS NULL
  AND (
      $1::boolean
      OR ($2::boolean AND deal_owner = $3)
  )
  AND (NOT $4::boolean OR deal_owner = $3)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at < $6)
  AND ($7::bigint IS NULL OR deal_owner = $7)
`

type DealPipelineStatsParams struct {
	ScopeAll    bool               `json:"scope_all"`
	IsOwn       bool               `json:"is_own"`
	Uid         *int64             `json:"uid"`
	MineOnly    bool               `json:"mine_only"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	OwnerFilter *int64             `json:"owner_filter"`
}

type DealPipelineStatsRow struct {
	OpenCount     int64          `json:"open_count"`
	PipelineValue pgtype.Numeric `json:"pipeline_value"`
	WonCount      int64          `json:"won_count"`
	LostCount     int64          `json:"lost_count"`
}

// KPI ringkas pipeline dalam cakupan ownership (satu round-trip, bukan hitung di
// Go atas seluruh baris). COALESCE(...)::bigint/::numeric membungkus agregat agar
// sqlc tak meng-emit interface{} (gotcha #14). Win rate dihitung di Go dari
// won_count/(won_count+lost_count) — pembagian nol ditangani di sana.
// BL-49: filter opsional Periode (created_at) + Owner (deal_owner) untuk Sales
// Report — guard NULL = tak menyaring (perilaku papan Kanban tak berubah, memang
// oper nil). owner_filter di-AND DI ATAS predikat scope: hanya bisa MENYEMPIT
// dalam cakupan yang diizinkan (sales own-scope pilih owner lain → nol baris).
func (q *Queries) DealPipelineStats(ctx context.Context, arg DealPipelineStatsParams) (DealPipelineStatsRow, error) {
	row := q.db.QueryRow(ctx, dealPipelineStats,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.OwnerFilter,
	)
	var i DealPipelineStatsRow
	err := row.Scan(
		&i.OpenCount,
		&i.PipelineValue,
		&i.WonCount,
		&i.LostCount,
	)
	return i, err
}

const getDeal = `-- name: GetDeal :one
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE id = $1 AND deleted_at IS NULL
`

// Satu deal hidup. RLS menjamin tenant_id; ownership diputuskan handler
// (DealsListFilter.Allows) atas baris.
func (q *Queries) GetDeal(ctx context.Context, id int64) (Deal, error) {
	row := q.db.QueryRow(ctx, getDeal, id)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.LossReasonCode,
	)
	return i, err
}

const getLatestDealForAccount = `-- name: GetLatestDealForAccount :one
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Deal TERBARU satu desa (chip "Terkait" di detail Account). Tanpa filter
// ownership: gerbangnya desa induk (handler via loadOwnedAccount), pola sama
// ListContactsByAccount. pgx.ErrNoRows = desa belum punya deal sama sekali.
func (q *Queries) GetLatestDealForAccount(ctx context.Context, accountID int64) (Deal, error) {
	row := q.db.QueryRow(ctx, getLatestDealForAccount, accountID)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.LossReasonCode,
	)
	return i, err
}

const listDeals = `-- name: ListDeals :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND deal_owner = $5)
  )
  AND (NOT $6::boolean OR deal_owner = $5)
  AND ($7::text = '' OR stage = $7::text)
  AND (
      $8::text = ''
      OR deal_name ILIKE '%' || $8 || '%'
      OR entity_code ILIKE '%' || $8 || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListDealsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	MineOnly        bool               `json:"mine_only"`
	StageFilter     string             `json:"stage_filter"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Daftar deal (tampilan Tabel), keyset (created_at DESC, id DESC) + filter
// ownership F3 + filter stage opsional. Dua flag ownership (sumber SATU dengan
// DealsListFilter): scope_all → semua; is_own → deal_owner = uid; keduanya false
// → NOL baris (fail-closed). stage_filter ” → semua stage.
//
// Filter tambahan (ortogonal dari ownership, BL-10):
//
//	mine_only → paksa deal_owner = uid (toggle "Deal Saya", walau aktor scope_all).
//
// Cermin mine_only di ListLeads; menyempitkan, tak pernah melebarkan.
//
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership+stage — tak pernah melebarkan baris. Hanya kolom
// tak-tersamar yang tampil di tabel (deal_name + entity_code); nilai ARR tersamar
// tak dijadikan kunci cari.
func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDeals,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsForPipeline = `-- name: ListDealsForPipeline :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      $1::boolean
      OR ($2::boolean AND deal_owner = $3)
  )
  AND (NOT $4::boolean OR deal_owner = $3)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListDealsForPipelineParams struct {
	ScopeAll bool   `json:"scope_all"`
	IsOwn    bool   `json:"is_own"`
	Uid      *int64 `json:"uid"`
	MineOnly bool   `json:"mine_only"`
	PageSize int32  `json:"page_size"`
}

// Papan Kanban: seluruh deal hidup dalam cakupan ownership, diurutkan agar kartu
// rapi per-stage lalu terbaru dulu. Di-bucket per-stage di handler (bukan N query
// per kolom). LIMIT membatasi papan agar tak memuat seluruh tabel (guardrail
// pagination); deal di luar batas tetap terlihat lewat tampilan Tabel berkeyset.
// mine_only (BL-10) menyaring papan ke deal_owner = uid saat toggle "Deal Saya"
// aktif — KPI (DealPipelineStats) ikut tersaring agar papan & ringkasan seiring.
func (q *Queries) ListDealsForPipeline(ctx context.Context, arg ListDealsForPipelineParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsForPipeline,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByAmount = `-- name: ListDealsSortByAmount :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (amount IS NULL OR (amount, id) > ($4::numeric, $5::bigint)))
          OR ($3::boolean AND amount IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (amount IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND amount IS NOT NULL
              AND (amount, id) < ($4::numeric, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND deal_owner = $8)
  )
  AND (NOT $9::boolean OR deal_owner = $8)
  AND ($10::text = '' OR stage = $10::text)
  AND (
      $11::text = ''
      OR deal_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN amount END ASC,
  CASE WHEN $2::text = 'desc' THEN amount END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListDealsSortByAmountParams struct {
	HasCursor    bool           `json:"has_cursor"`
	Dir          string         `json:"dir"`
	CursorIsNull bool           `json:"cursor_is_null"`
	CursorVal    pgtype.Numeric `json:"cursor_val"`
	CursorID     int64          `json:"cursor_id"`
	ScopeAll     bool           `json:"scope_all"`
	IsOwn        bool           `json:"is_own"`
	Uid          *int64         `json:"uid"`
	MineOnly     bool           `json:"mine_only"`
	StageFilter  string         `json:"stage_filter"`
	Search       string         `json:"search"`
	PageSize     int32          `json:"page_size"`
}

// BL-157e: sort by amount ("Nilai"). NULLABLE numeric. Kunci sort memakai
// nilai ASLI (tak ter-mask) — F4 (maskARR) hanya menyamarkan TAMPILAN di
// handler, mirror presedan Estimasi Leads (ListLeadsSortByValue). Pola
// null-aware SAMA dgn ListDealsSortByCode, tipe kolom numeric bukan text.
func (q *Queries) ListDealsSortByAmount(ctx context.Context, arg ListDealsSortByAmountParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByAmount,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByCloseDate = `-- name: ListDealsSortByCloseDate :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (expected_close_date IS NULL OR (expected_close_date, id) > ($4::date, $5::bigint)))
          OR ($3::boolean AND expected_close_date IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (expected_close_date IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND expected_close_date IS NOT NULL
              AND (expected_close_date, id) < ($4::date, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND deal_owner = $8)
  )
  AND (NOT $9::boolean OR deal_owner = $8)
  AND ($10::text = '' OR stage = $10::text)
  AND (
      $11::text = ''
      OR deal_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN expected_close_date END ASC,
  CASE WHEN $2::text = 'desc' THEN expected_close_date END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListDealsSortByCloseDateParams struct {
	HasCursor    bool        `json:"has_cursor"`
	Dir          string      `json:"dir"`
	CursorIsNull bool        `json:"cursor_is_null"`
	CursorVal    pgtype.Date `json:"cursor_val"`
	CursorID     int64       `json:"cursor_id"`
	ScopeAll     bool        `json:"scope_all"`
	IsOwn        bool        `json:"is_own"`
	Uid          *int64      `json:"uid"`
	MineOnly     bool        `json:"mine_only"`
	StageFilter  string      `json:"stage_filter"`
	Search       string      `json:"search"`
	PageSize     int32       `json:"page_size"`
}

// BL-157e: sort by expected_close_date ("Perkiraan Tutup"). NULLABLE date
// (belum tentu diisi saat deal dibuat). Pola null-aware SAMA dgn
// ListDealsSortByCode, tipe kolom date — kloning PERSIS
// ListSubscriptionsSortByRenewal.
func (q *Queries) ListDealsSortByCloseDate(ctx context.Context, arg ListDealsSortByCloseDateParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByCloseDate,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByCode = `-- name: ListDealsSortByCode :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (entity_code IS NULL OR (entity_code, id) > ($4::text, $5::bigint)))
          OR ($3::boolean AND entity_code IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (entity_code IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND entity_code IS NOT NULL
              AND (entity_code, id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND deal_owner = $8)
  )
  AND (NOT $9::boolean OR deal_owner = $8)
  AND ($10::text = '' OR stage = $10::text)
  AND (
      $11::text = ''
      OR deal_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN entity_code END ASC,
  CASE WHEN $2::text = 'desc' THEN entity_code END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListDealsSortByCodeParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StageFilter  string `json:"stage_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157e (fondasi sort per kolom Deals): SAMA PERSIS filter ListDeals
// (ownership F3 + mine_only + stage_filter + search) — hanya ORDER BY/keyset
// yang beda, diurut entity_code (bukan created_at). entity_code NULLABLE
// (diisi GenerateEntityCode saat create, tapi kolom tetap nullable di skema)
// → kloning PERSIS pola ListLeadsSortByCode. NULLS default Postgres
// (ASC=LAST, DESC=FIRST).
func (q *Queries) ListDealsSortByCode(ctx context.Context, arg ListDealsSortByCodeParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByCode,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByName = `-- name: ListDealsSortByName :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (deal_name, id) > ($3::text, $4::bigint))
      OR ($2::text = 'desc'
          AND (deal_name, id) < ($3::text, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND deal_owner = $7)
  )
  AND (NOT $8::boolean OR deal_owner = $7)
  AND ($9::text = '' OR stage = $9::text)
  AND (
      $10::text = ''
      OR deal_name ILIKE '%' || $10 || '%'
      OR entity_code ILIKE '%' || $10 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN deal_name END ASC,
  CASE WHEN $2::text = 'desc' THEN deal_name END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $11
`

type ListDealsSortByNameParams struct {
	HasCursor   bool   `json:"has_cursor"`
	Dir         string `json:"dir"`
	CursorVal   string `json:"cursor_val"`
	CursorID    int64  `json:"cursor_id"`
	ScopeAll    bool   `json:"scope_all"`
	IsOwn       bool   `json:"is_own"`
	Uid         *int64 `json:"uid"`
	MineOnly    bool   `json:"mine_only"`
	StageFilter string `json:"stage_filter"`
	Search      string `json:"search"`
	PageSize    int32  `json:"page_size"`
}

// BL-157e: sort by deal_name ("Deal"). deal_name TIDAK NULLABLE → kloning pola
// ListLeadsSortByName (tanpa kerumitan NULL).
func (q *Queries) ListDealsSortByName(ctx context.Context, arg ListDealsSortByNameParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByName,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByOwner = `-- name: ListDealsSortByOwner :many
SELECT deals.id, deals.tenant_id, deals.entity_code, deals.deal_owner, deals.account_id, deals.primary_contact_id, deals.plan_requested_id, deals.deal_name, deals.deal_type, deals.stage, deals.amount, deals.probability, deals.expected_close_date, deals.forecast_category, deals.next_step, deals.closed_date, deals.win_loss_reason, deals.competitor, deals.loss_notes, deals.subscription_term, deals.created_subscription_id, deals.deleted_at, deals.created_by, deals.created_at, deals.updated_by, deals.updated_at, deals.loss_reason_code FROM deals
LEFT JOIN users u ON u.id = deal_owner
WHERE deals.deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NULL
                OR (COALESCE(NULLIF(u.name, ''), u.email), deals.id) > ($4::text, $5::bigint)))
          OR ($3::boolean
              AND COALESCE(NULLIF(u.name, ''), u.email) IS NULL AND deals.id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL OR deals.id < $5::bigint))
          OR (NOT $3::boolean AND COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL
              AND (COALESCE(NULLIF(u.name, ''), u.email), deals.id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND deal_owner = $8)
  )
  AND (NOT $9::boolean OR deal_owner = $8)
  AND ($10::text = '' OR stage = $10::text)
  AND (
      $11::text = ''
      OR deal_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN COALESCE(NULLIF(u.name, ''), u.email) END ASC,
  CASE WHEN $2::text = 'desc' THEN COALESCE(NULLIF(u.name, ''), u.email) END DESC,
  CASE WHEN $2::text = 'asc'  THEN deals.id END ASC,
  CASE WHEN $2::text = 'desc' THEN deals.id END DESC
LIMIT $12
`

type ListDealsSortByOwnerParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StageFilter  string `json:"stage_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157e: sort by Pemilik (deal_owner). Kunci sort HARUS
// COALESCE(NULLIF(u.name,”), u.email) — PERSIS logika tampil ownerName/
// memberNameMap (nama bila terisi, else email) — agar urutan tak menyimpang
// dari yang ditampilkan. NULLABLE (deal_owner ON DELETE SET NULL). LEFT JOIN
// users: baris tanpa owner ATAU owner terhapus → owner_key NULL, masuk
// kelompok NULL (default Postgres). Mirror PERSIS ListLeadsSortByOwner.
func (q *Queries) ListDealsSortByOwner(ctx context.Context, arg ListDealsSortByOwnerParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByOwner,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByProbability = `-- name: ListDealsSortByProbability :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (probability IS NULL OR (probability, id) > ($4::smallint, $5::bigint)))
          OR ($3::boolean AND probability IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (probability IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND probability IS NOT NULL
              AND (probability, id) < ($4::smallint, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND deal_owner = $8)
  )
  AND (NOT $9::boolean OR deal_owner = $8)
  AND ($10::text = '' OR stage = $10::text)
  AND (
      $11::text = ''
      OR deal_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN probability END ASC,
  CASE WHEN $2::text = 'desc' THEN probability END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListDealsSortByProbabilityParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    int16  `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StageFilter  string `json:"stage_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157e: sort by probability ("Peluang", %). NULLABLE smallint. Pola
// null-aware SAMA dgn ListDealsSortByAmount, tipe kolom smallint.
func (q *Queries) ListDealsSortByProbability(ctx context.Context, arg ListDealsSortByProbabilityParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByProbability,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsSortByStage = `-- name: ListDealsSortByStage :many
SELECT id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code FROM deals
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (stage, id) > ($3::text, $4::bigint))
      OR ($2::text = 'desc'
          AND (stage, id) < ($3::text, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND deal_owner = $7)
  )
  AND (NOT $8::boolean OR deal_owner = $7)
  AND ($9::text = '' OR stage = $9::text)
  AND (
      $10::text = ''
      OR deal_name ILIKE '%' || $10 || '%'
      OR entity_code ILIKE '%' || $10 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN stage END ASC,
  CASE WHEN $2::text = 'desc' THEN stage END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $11
`

type ListDealsSortByStageParams struct {
	HasCursor   bool   `json:"has_cursor"`
	Dir         string `json:"dir"`
	CursorVal   string `json:"cursor_val"`
	CursorID    int64  `json:"cursor_id"`
	ScopeAll    bool   `json:"scope_all"`
	IsOwn       bool   `json:"is_own"`
	Uid         *int64 `json:"uid"`
	MineOnly    bool   `json:"mine_only"`
	StageFilter string `json:"stage_filter"`
	Search      string `json:"search"`
	PageSize    int32  `json:"page_size"`
}

// BL-157e: sort by stage ("Tahap" — RAW enum Prospecting/Qualification/…,
// alfabetis; tak menduplikasi urutan pipeline ke SQL, mirror keputusan
// "Status" Leads BL-157b). stage NOT NULL → kloning PERSIS pola
// ListDealsSortByName.
func (q *Queries) ListDealsSortByStage(ctx context.Context, arg ListDealsSortByStageParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsSortByStage,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StageFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.DealOwner,
			&i.AccountID,
			&i.PrimaryContactID,
			&i.PlanRequestedID,
			&i.DealName,
			&i.DealType,
			&i.Stage,
			&i.Amount,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ForecastCategory,
			&i.NextStep,
			&i.ClosedDate,
			&i.WinLossReason,
			&i.Competitor,
			&i.LossNotes,
			&i.SubscriptionTerm,
			&i.CreatedSubscriptionID,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.LossReasonCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDealCreatedSubscription = `-- name: SetDealCreatedSubscription :exec
UPDATE deals SET
    created_subscription_id = $1,
    updated_by              = $2,
    updated_at              = now()
WHERE id = $3 AND deleted_at IS NULL
`

type SetDealCreatedSubscriptionParams struct {
	CreatedSubscriptionID *int64 `json:"created_subscription_id"`
	UpdatedBy             *int64 `json:"updated_by"`
	ID                    int64  `json:"id"`
}

// Tautkan deal ke langganan hasil create-from-deal (deals.created_subscription_id;
// FK ditutup di migrasi 00012). Dipanggil dalam tx yang SAMA dgn CreateSubscription
// agar deal Closed Won selalu menunjuk langganan yang lahir darinya (atomik).
func (q *Queries) SetDealCreatedSubscription(ctx context.Context, arg SetDealCreatedSubscriptionParams) error {
	_, err := q.db.Exec(ctx, setDealCreatedSubscription, arg.CreatedSubscriptionID, arg.UpdatedBy, arg.ID)
	return err
}

const setDealRecognizedValue = `-- name: SetDealRecognizedValue :exec
UPDATE deals SET
    amount     = $1,
    updated_by = $2,
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type SetDealRecognizedValueParams struct {
	Amount    pgtype.Numeric `json:"amount"`
	UpdatedBy *int64         `json:"updated_by"`
	ID        int64          `json:"id"`
}

// BL-88 (quote otoritatif): salin grand_total quote yang BARU di-Accept ke deal.amount
// sebagai NILAI DIAKUI (revenue MRR/ARR laporan). Menggantikan nilai perkiraan manual;
// jalur tersendiri (bukan UpdateDeal, itu jalur form) agar terlihat sebagai efek Accept.
// Tak menyentuh baris terhapus.
func (q *Queries) SetDealRecognizedValue(ctx context.Context, arg SetDealRecognizedValueParams) error {
	_, err := q.db.Exec(ctx, setDealRecognizedValue, arg.Amount, arg.UpdatedBy, arg.ID)
	return err
}

const setDealRequestedPlan = `-- name: SetDealRequestedPlan :exec
UPDATE deals SET
    plan_requested_id = $1,
    updated_by        = $2,
    updated_at        = now()
WHERE id = $3 AND deleted_at IS NULL
`

type SetDealRequestedPlanParams struct {
	PlanRequestedID *int64 `json:"plan_requested_id"`
	UpdatedBy       *int64 `json:"updated_by"`
	ID              int64  `json:"id"`
}

// BL-100 (Fix B): backfill paket deal dari quote yang BARU di-Accept, agar Closed Won
// bisa membuat langganan (subscriptionFromWonDeal membaca deals.plan_requested_id yang
// tak pernah diisi jalur UI). Timpa nilai lama (accept terakhir menang). Tak menyentuh
// baris terhapus.
func (q *Queries) SetDealRequestedPlan(ctx context.Context, arg SetDealRequestedPlanParams) error {
	_, err := q.db.Exec(ctx, setDealRequestedPlan, arg.PlanRequestedID, arg.UpdatedBy, arg.ID)
	return err
}

const softDeleteDeal = `-- name: SoftDeleteDeal :exec
UPDATE deals SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteDealParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
// leads.converted_deal_id tak putus). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) error {
	_, err := q.db.Exec(ctx, softDeleteDeal, arg.UpdatedBy, arg.ID)
	return err
}

const updateDeal = `-- name: UpdateDeal :one
UPDATE deals SET
    deal_name           = $1,
    account_id          = $2,
    deal_owner          = $3,
    primary_contact_id  = $4,
    plan_requested_id   = $5,
    deal_type           = $6,
    amount              = $7,
    probability         = $8,
    expected_close_date = $9,
    forecast_category   = $10,
    next_step           = $11,
    subscription_term   = $12,
    competitor          = $13,
    updated_by          = $14,
    updated_at          = now()
WHERE id = $15 AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, deal_owner, account_id, primary_contact_id, plan_requested_id, deal_name, deal_type, stage, amount, probability, expected_close_date, forecast_category, next_step, closed_date, win_loss_reason, competitor, loss_notes, subscription_term, created_subscription_id, deleted_at, created_by, created_at, updated_by, updated_at, loss_reason_code
`

type UpdateDealParams struct {
	DealName          string         `json:"deal_name"`
	AccountID         int64          `json:"account_id"`
	DealOwner         *int64         `json:"deal_owner"`
	PrimaryContactID  *int64         `json:"primary_contact_id"`
	PlanRequestedID   *int64         `json:"plan_requested_id"`
	DealType          *string        `json:"deal_type"`
	Amount            pgtype.Numeric `json:"amount"`
	Probability       *int16         `json:"probability"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	ForecastCategory  *string        `json:"forecast_category"`
	NextStep          *string        `json:"next_step"`
	SubscriptionTerm  *string        `json:"subscription_term"`
	Competitor        *string        `json:"competitor"`
	UpdatedBy         *int64         `json:"updated_by"`
	ID                int64          `json:"id"`
}

// Sunting profil deal. entity_code, stage, dan hasil (win_loss_reason/closed_date)
// TAK di sini: stage punya jalur khusus (UpdateDealStage) agar perpindahan pipeline
// terlihat sebagai aksi tersendiri, bukan efek samping edit.
func (q *Queries) UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDeal,
		arg.DealName,
		arg.AccountID,
		arg.DealOwner,
		arg.PrimaryContactID,
		arg.PlanRequestedID,
		arg.DealType,
		arg.Amount,
		arg.Probability,
		arg.ExpectedCloseDate,
		arg.ForecastCategory,
		arg.NextStep,
		arg.SubscriptionTerm,
		arg.Competitor,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.DealOwner,
		&i.AccountID,
		&i.PrimaryContactID,
		&i.PlanRequestedID,
		&i.DealName,
		&i.DealType,
		&i.Stage,
		&i.Amount,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ForecastCategory,
		&i.NextStep,
		&i.ClosedDate,
		&i.WinLossReason,
		&i.Competitor,
		&i.LossNotes,
		&i.SubscriptionTerm,
		&i.CreatedSubscriptionID,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.LossReasonCode,
	)
	return i, err
}

const updateDealStage = `-- name: UpdateDealStage :exec
UPDATE deals SET
    stage           = $1,
    win_loss_reason = $2,
    loss_reason_code = $3,
    loss_notes      = $4,
    closed_date     = CASE
        WHEN $1 IN ('Closed Won','Closed Lost') THEN CURRENT_DATE
        ELSE NULL END,
    updated_by      = $5,
    updated_at      = now()
WHERE id = $6 AND deleted_at IS NULL
`

type UpdateDealStageParams struct {
	Stage          string  `json:"stage"`
	WinLossReason  *string `json:"win_loss_reason"`
	LossReasonCode *string `json:"loss_reason_code"`
	LossNotes      *string `json:"loss_notes"`
	UpdatedBy      *int64  `json:"updated_by"`
	ID             int64   `json:"id"`
}

// Pindah stage pipeline (aksi tersendiri). closed_date/win_loss_reason/loss_notes
// diisi saat Closed Won/Lost — validasi "Closed Lost wajib win_loss_reason" di
// handler (bukan constraint DB agar pesan bisa diperbaiki user). closed_date =
// CURRENT_DATE bila stage terminal, NULL bila dibuka kembali ke stage aktif.
func (q *Queries) UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) error {
	_, err := q.db.Exec(ctx, updateDealStage,
		arg.Stage,
		arg.WinLossReason,
		arg.LossReasonCode,
		arg.LossNotes,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
