// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health_score.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHealthScoreKPIs = `-- name: CountHealthScoreKPIs :one
SELECT
    COUNT(*)                                                        AS total,
    COUNT(*) FILTER (WHERE cs.health_status = 'Healthy')           AS healthy,
    COUNT(*) FILTER (WHERE cs.health_status = 'At-Risk')           AS at_risk,
    COUNT(*) FILTER (WHERE cs.health_status = 'Critical')          AS critical,
    COUNT(*) FILTER (WHERE cs.overall_health_score IS NOT NULL)     AS scored
FROM accounts a
LEFT JOIN customer_success cs
       ON cs.account_id = a.id AND cs.tenant_id = a.tenant_id
WHERE a.deleted_at IS NULL
  AND (
      $1::boolean
      OR ($2::boolean
          AND (a.assigned_csm = $3 OR a.backup_csm = $3))
      OR ($4::boolean
          AND a.account_owner = $3)
  )
`

type CountHealthScoreKPIsParams struct {
	ScopeAll bool   `json:"scope_all"`
	IsCsm    bool   `json:"is_csm"`
	Uid      *int64 `json:"uid"`
	IsSales  bool   `json:"is_sales"`
}

type CountHealthScoreKPIsRow struct {
	Total    int64 `json:"total"`
	Healthy  int64 `json:"healthy"`
	AtRisk   int64 `json:"at_risk"`
	Critical int64 `json:"critical"`
	Scored   int64 `json:"scored"`
}

// KPI agregat untuk header: total desa (dalam scope), sehat/berisiko/kritis,
// dan rata-rata skor (NULL bila semua skor belum diisi).
// Ownership clause SAMA PERSIS dengan ListHealthScores agar konsisten.
func (q *Queries) CountHealthScoreKPIs(ctx context.Context, arg CountHealthScoreKPIsParams) (CountHealthScoreKPIsRow, error) {
	row := q.db.QueryRow(ctx, countHealthScoreKPIs,
		arg.ScopeAll,
		arg.IsCsm,
		arg.Uid,
		arg.IsSales,
	)
	var i CountHealthScoreKPIsRow
	err := row.Scan(
		&i.Total,
		&i.Healthy,
		&i.AtRisk,
		&i.Critical,
		&i.Scored,
	)
	return i, err
}

const listHealthScores = `-- name: ListHealthScores :many

SELECT
    a.id,
    a.village_name           AS account_name,
    cs.overall_health_score,
    cs.health_status,
    cs.adoption_score,
    cs.engagement_score,
    cs.support_score,
    cs.sentiment_score,
    cs.score_trend,
    cs.lifecycle_stage,
    cs.stage_entry_date,
    a.created_at
FROM accounts a
LEFT JOIN customer_success cs
       ON cs.account_id = a.id AND cs.tenant_id = a.tenant_id
WHERE a.deleted_at IS NULL
  AND (
      $1::boolean
      OR ($2::boolean
          AND (a.assigned_csm = $3 OR a.backup_csm = $3))
      OR ($4::boolean
          AND a.account_owner = $3)
  )
  AND ($5 = ''
       OR COALESCE(cs.health_status, '') = $5)
  AND (a.created_at, a.id) < ($6::timestamptz,
                               $7::bigint)
  AND ($8::text = ''
       OR a.village_name ILIKE '%' || $8 || '%')
ORDER BY a.created_at DESC, a.id DESC
LIMIT $9
`

type ListHealthScoresParams struct {
	ScopeAll        bool               `json:"scope_all"`
	IsCsm           bool               `json:"is_csm"`
	Uid             *int64             `json:"uid"`
	IsSales         bool               `json:"is_sales"`
	FilterStatus    interface{}        `json:"filter_status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

type ListHealthScoresRow struct {
	ID                 int64              `json:"id"`
	AccountName        string             `json:"account_name"`
	OverallHealthScore *int16             `json:"overall_health_score"`
	HealthStatus       *string            `json:"health_status"`
	AdoptionScore      *int16             `json:"adoption_score"`
	EngagementScore    *int16             `json:"engagement_score"`
	SupportScore       *int16             `json:"support_score"`
	SentimentScore     *int16             `json:"sentiment_score"`
	ScoreTrend         *string            `json:"score_trend"`
	LifecycleStage     *string            `json:"lifecycle_stage"`
	StageEntryDate     pgtype.Date        `json:"stage_entry_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// health_score.sql — workspace-level Health Score listing (Modul 6 slice C1).
// Data sumber: customer_success (1:1 dengan accounts). Tidak ada tabel baru.
// F3 ownership: scope_all (admin/manager) / is_csm / is_sales — pola SAMA
// dengan ListAccounts agar tidak divergen. Support (ScopeNone) → semua flag
// false → 0 baris (fail-closed, bukan error).
// Workspace-level listing akun + data health score.
// Keyset (created_at DESC, id DESC), filter_status ” = semua.
// uid dioper walau scope_all (diabaikan di klausa).
func (q *Queries) ListHealthScores(ctx context.Context, arg ListHealthScoresParams) ([]ListHealthScoresRow, error) {
	rows, err := q.db.Query(ctx, listHealthScores,
		arg.ScopeAll,
		arg.IsCsm,
		arg.Uid,
		arg.IsSales,
		arg.FilterStatus,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHealthScoresRow{}
	for rows.Next() {
		var i ListHealthScoresRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.OverallHealthScore,
			&i.HealthStatus,
			&i.AdoptionScore,
			&i.EngagementScore,
			&i.SupportScore,
			&i.SentimentScore,
			&i.ScoreTrend,
			&i.LifecycleStage,
			&i.StageEntryDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
