// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE invites SET accepted_at = now()
WHERE token = $1 AND accepted_at IS NULL AND expires_at > now()
`

// Tandai terpakai (one-time). Guard accepted_at IS NULL → race dua klik tak
// menghasilkan dua membership (UNIQUE di memberships jadi jaring kedua).
func (q *Queries) AcceptInvite(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, acceptInvite, token)
	return err
}

const countPendingInvitesByEmail = `-- name: CountPendingInvitesByEmail :one
SELECT count(*)::bigint FROM invites
WHERE lower(email) = $1 AND accepted_at IS NULL AND expires_at > now()
`

// Bagian "perlu tindakan" dari badge. Undangan pending SENGAJA tak pernah
// ter-auto-read: ia tugas, bukan kabar — lihat MarkNotificationsRead.
func (q *Queries) CountPendingInvitesByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitesByEmail, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (tenant_id, email, role, token, invited_by, expires_at, business_role, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, email, role, token, invited_by, accepted_at, expires_at, created_at, business_role, kind
`

type CreateInviteParams struct {
	TenantID     int64              `json:"tenant_id"`
	Email        string             `json:"email"`
	Role         string             `json:"role"`
	Token        string             `json:"token"`
	InvitedBy    *int64             `json:"invited_by"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	BusinessRole *string            `json:"business_role"`
	Kind         string             `json:"kind"`
}

// Undangan bergabung ke workspace. token = rahasia URL (crypto/rand hex via
// oauth.NewState). email boleh milik orang yang BELUM punya akun. business_role
// (nullable, BL-170) = Peran CRM yang sudah ditentukan admin di muka, diterapkan
// otomatis saat invite diterima; kind = Jenis Anggota (internal/eksternal),
// dipakai memfilter business_role yang valid di form Undang.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.BusinessRole,
		arg.Kind,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.BusinessRole,
		&i.Kind,
	)
	return i, err
}

const declineInvite = `-- name: DeclineInvite :exec
DELETE FROM invites
WHERE token = $1 AND lower(email) = $2 AND accepted_at IS NULL
`

type DeclineInviteParams struct {
	Token string `json:"token"`
	Email string `json:"email"`
}

// Tolak undangan (sisi PENERIMA). Kunci ganda token + email: penerima tak punya
// scope ke workspace pengundang, jadi DeleteInvite (yang butuh tenant_id) tak
// bisa dipakai. Mencocokkan email mencegah pemegang token menolak undangan
// milik orang lain.
func (q *Queries) DeclineInvite(ctx context.Context, arg DeclineInviteParams) error {
	_, err := q.db.Exec(ctx, declineInvite, arg.Token, arg.Email)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1 AND tenant_id = $2
`

type DeleteInviteParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

// Batalkan undangan yang belum diterima (sisi PENGUNDANG, di panel anggota).
func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.TenantID)
	return err
}

const deletePendingInviteByEmail = `-- name: DeletePendingInviteByEmail :execrows
DELETE FROM invites
WHERE tenant_id = $1 AND lower(email) = lower($2) AND accepted_at IS NULL
`

type DeletePendingInviteByEmailParams struct {
	TenantID int64  `json:"tenant_id"`
	Lower    string `json:"lower"`
}

// Hapus undangan PENDING existing utk email yang sama di tenant ini (BL-170,
// pola upsert-by-replace §c): dipanggil InviteCreate SEBELUM insert baru, agar
// re-undang dengan field terbaru menggantikan yang lama alih-alih ditolak
// bentrok atau menumpuk duplikat. :execrows (bukan :exec) agar pemanggil tahu
// apakah ini undangan BARU atau KIRIM ULANG (>0 baris terhapus) — dipakai
// memilih pesan sukses yang tepat (toast harus selalu tampil, lihat InviteCreate).
func (q *Queries) DeletePendingInviteByEmail(ctx context.Context, arg DeletePendingInviteByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingInviteByEmail, arg.TenantID, arg.Lower)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT i.id, i.tenant_id, i.email, i.role, i.token, i.invited_by, i.accepted_at, i.expires_at, i.created_at, i.business_role, i.kind, t.name AS tenant_name, t.slug AS tenant_slug
FROM invites i
JOIN tenants t ON t.id = i.tenant_id
WHERE i.token = $1
`

type GetInviteByTokenRow struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Email        string             `json:"email"`
	Role         string             `json:"role"`
	Token        string             `json:"token"`
	InvitedBy    *int64             `json:"invited_by"`
	AcceptedAt   pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	BusinessRole *string            `json:"business_role"`
	Kind         string             `json:"kind"`
	TenantName   string             `json:"tenant_name"`
	TenantSlug   string             `json:"tenant_slug"`
}

// Jalur PUBLIK (/invite/{token}) — penerima belum tentu login/anggota. Validasi
// kedaluwarsa & sudah-dipakai dilakukan di handler agar pesannya spesifik.
func (q *Queries) GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.BusinessRole,
		&i.Kind,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const listInvitesByTenant = `-- name: ListInvitesByTenant :many
SELECT id, tenant_id, email, role, token, invited_by, accepted_at, expires_at, created_at, business_role, kind FROM invites
WHERE tenant_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

// Undangan PENDING satu workspace (panel anggota) — yang sudah diterima disaring.
func (q *Queries) ListInvitesByTenant(ctx context.Context, tenantID int64) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.AcceptedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.BusinessRole,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitesByEmail = `-- name: ListPendingInvitesByEmail :many
SELECT i.id, i.tenant_id, i.email, i.role, i.token, i.invited_by, i.accepted_at, i.expires_at, i.created_at, i.business_role, i.kind, t.name AS tenant_name
FROM invites i
JOIN tenants t ON t.id = i.tenant_id
WHERE lower(i.email) = $1 AND i.accepted_at IS NULL AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type ListPendingInvitesByEmailRow struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Email        string             `json:"email"`
	Role         string             `json:"role"`
	Token        string             `json:"token"`
	InvitedBy    *int64             `json:"invited_by"`
	AcceptedAt   pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	BusinessRole *string            `json:"business_role"`
	Kind         string             `json:"kind"`
	TenantName   string             `json:"tenant_name"`
}

// Undangan yang ditujukan ke SATU ORANG (halaman notifikasi). Dicari per-email,
// bukan user_id: saat diundang penerima belum tentu punya akun.
//
// lower(email) = $1 — pemanggil WAJIB mengirim email yang sudah di-lowercase
// (pola auth.go/invite.go). Ditopang index partial idx_invites_email.
func (q *Queries) ListPendingInvitesByEmail(ctx context.Context, email string) ([]ListPendingInvitesByEmailRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesByEmailRow{}
	for rows.Next() {
		var i ListPendingInvitesByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.AcceptedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.BusinessRole,
			&i.Kind,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberExistsByEmail = `-- name: MemberExistsByEmail :one
SELECT EXISTS (
    SELECT 1 FROM memberships m
    JOIN users u ON u.id = m.user_id
    WHERE m.tenant_id = $1 AND lower(u.email) = lower($2)
)
`

type MemberExistsByEmailParams struct {
	TenantID int64  `json:"tenant_id"`
	Lower    string `json:"lower"`
}

// Guard InviteCreate (BL-170 §b): true bila email sudah jadi anggota tenant ini.
// Query TARGETED (JOIN memberships+users), BUKAN scan ListMembersByTenant penuh
// — dipanggil tiap submit form Undang.
func (q *Queries) MemberExistsByEmail(ctx context.Context, arg MemberExistsByEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberExistsByEmail, arg.TenantID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
