// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kb_articles.sql

package db

import (
	"context"
)

const createKBArticle = `-- name: CreateKBArticle :one
INSERT INTO kb_articles (
    tenant_id, article_title, article_body, category, keywords,
    status, visibility, author_id, created_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, tenant_id, article_title, article_body, category, keywords, status, visibility, author_id, view_count, helpful_votes, created_by, created_at, updated_by, updated_at
`

type CreateKBArticleParams struct {
	TenantID     int64   `json:"tenant_id"`
	ArticleTitle string  `json:"article_title"`
	ArticleBody  *string `json:"article_body"`
	Category     *string `json:"category"`
	Keywords     *string `json:"keywords"`
	Status       string  `json:"status"`
	Visibility   string  `json:"visibility"`
	AuthorID     *int64  `json:"author_id"`
	CreatedBy    *int64  `json:"created_by"`
}

// Buat artikel. tenant_id eksplisit (RLS WITH CHECK memverifikasinya = GUC).
// author_id = created_by (penulis awal; slice ini tak sediakan picker
// reassign penulis — lihat komentar migrasi 00018).
func (q *Queries) CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, createKBArticle,
		arg.TenantID,
		arg.ArticleTitle,
		arg.ArticleBody,
		arg.Category,
		arg.Keywords,
		arg.Status,
		arg.Visibility,
		arg.AuthorID,
		arg.CreatedBy,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ArticleTitle,
		&i.ArticleBody,
		&i.Category,
		&i.Keywords,
		&i.Status,
		&i.Visibility,
		&i.AuthorID,
		&i.ViewCount,
		&i.HelpfulVotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBArticle = `-- name: GetKBArticle :one
SELECT id, tenant_id, article_title, article_body, category, keywords, status, visibility, author_id, view_count, helpful_votes, created_by, created_at, updated_by, updated_at FROM kb_articles
WHERE id = $1
`

// Satu artikel (baca detail/isi). RLS menjamin tenant_id.
func (q *Queries) GetKBArticle(ctx context.Context, id int64) (KbArticle, error) {
	row := q.db.QueryRow(ctx, getKBArticle, id)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ArticleTitle,
		&i.ArticleBody,
		&i.Category,
		&i.Keywords,
		&i.Status,
		&i.Visibility,
		&i.AuthorID,
		&i.ViewCount,
		&i.HelpfulVotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listKBArticlesAll = `-- name: ListKBArticlesAll :many

SELECT id, tenant_id, article_title, article_body, category, keywords, status, visibility, author_id, view_count, helpful_votes, created_by, created_at, updated_by, updated_at FROM kb_articles
ORDER BY updated_at DESC, id DESC
`

// kb_articles.sql — katalog master (Knowledge Base), Modul 6 Customer
// Success slice A3. Isolasi WORKSPACE ditegakkan RLS (GUC app.tenant_id di
// WithTenant); tak ada filter tenant_id manual. kb_articles TANPA
// soft-delete: status='Draft' = draf, bukan terhapus. Meniru pola
// playbooks.sql (A2), status 3-nilai (bukan is_active boolean) meniru
// leads_status_chk/subs_status_chk.
// Seluruh katalog untuk tampilan kelola (semua status). Terbaru diperbarui
// dulu — perilaku umum KB admin view. Bounded katalog master per-workspace
// → tanpa keyset.
func (q *Queries) ListKBArticlesAll(ctx context.Context) ([]KbArticle, error) {
	rows, err := q.db.Query(ctx, listKBArticlesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbArticle{}
	for rows.Next() {
		var i KbArticle
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ArticleTitle,
			&i.ArticleBody,
			&i.Category,
			&i.Keywords,
			&i.Status,
			&i.Visibility,
			&i.AuthorID,
			&i.ViewCount,
			&i.HelpfulVotes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKBArticleStatus = `-- name: SetKBArticleStatus :exec
UPDATE kb_articles SET
    status     = $1,
    updated_by = $2,
    updated_at = now()
WHERE id = $3
`

type SetKBArticleStatusParams struct {
	Status    string `json:"status"`
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Transisi status (Draft/Review/Published — CHECK di DB menegakkan domain
// nilai). Handler yang memutuskan transisi mana yang ditawarkan per baris.
func (q *Queries) SetKBArticleStatus(ctx context.Context, arg SetKBArticleStatusParams) error {
	_, err := q.db.Exec(ctx, setKBArticleStatus, arg.Status, arg.UpdatedBy, arg.ID)
	return err
}

const updateKBArticle = `-- name: UpdateKBArticle :one
UPDATE kb_articles SET
    article_title = $1,
    article_body  = $2,
    category      = $3,
    keywords      = $4,
    visibility    = $5,
    updated_by    = $6,
    updated_at    = now()
WHERE id = $7
RETURNING id, tenant_id, article_title, article_body, category, keywords, status, visibility, author_id, view_count, helpful_votes, created_by, created_at, updated_by, updated_at
`

type UpdateKBArticleParams struct {
	ArticleTitle string  `json:"article_title"`
	ArticleBody  *string `json:"article_body"`
	Category     *string `json:"category"`
	Keywords     *string `json:"keywords"`
	Visibility   string  `json:"visibility"`
	UpdatedBy    *int64  `json:"updated_by"`
	ID           int64   `json:"id"`
}

// Sunting profil/isi artikel. status TAK di sini (SetKBArticleStatus) —
// transisi status adalah aksi tersendiri, bukan efek samping edit.
func (q *Queries) UpdateKBArticle(ctx context.Context, arg UpdateKBArticleParams) (KbArticle, error) {
	row := q.db.QueryRow(ctx, updateKBArticle,
		arg.ArticleTitle,
		arg.ArticleBody,
		arg.Category,
		arg.Keywords,
		arg.Visibility,
		arg.UpdatedBy,
		arg.ID,
	)
	var i KbArticle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ArticleTitle,
		&i.ArticleBody,
		&i.Category,
		&i.Keywords,
		&i.Status,
		&i.Visibility,
		&i.AuthorID,
		&i.ViewCount,
		&i.HelpfulVotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
