// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLead = `-- name: CreateLead :one

INSERT INTO leads (
    tenant_id, entity_code, lead_name, lead_owner,
    contact_person, job_title, lead_source,
    lead_status, rating, unqualified_reason, estimated_value,
    district_id, mobile_phone, whatsapp, email,
    created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11,
    $12,
    $13, $14, $15,
    $16
)
RETURNING id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id
`

type CreateLeadParams struct {
	TenantID          int64          `json:"tenant_id"`
	EntityCode        *string        `json:"entity_code"`
	LeadName          string         `json:"lead_name"`
	LeadOwner         *int64         `json:"lead_owner"`
	ContactPerson     *string        `json:"contact_person"`
	JobTitle          *string        `json:"job_title"`
	LeadSource        *string        `json:"lead_source"`
	LeadStatus        string         `json:"lead_status"`
	Rating            *string        `json:"rating"`
	UnqualifiedReason *string        `json:"unqualified_reason"`
	EstimatedValue    pgtype.Numeric `json:"estimated_value"`
	DistrictID        *int64         `json:"district_id"`
	MobilePhone       *string        `json:"mobile_phone"`
	Whatsapp          *string        `json:"whatsapp"`
	Email             *string        `json:"email"`
	CreatedBy         *int64         `json:"created_by"`
}

// leads.sql — funnel Sales (Lead). Isolasi WORKSPACE ditegakkan RLS (GUC
// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
// lewat flag ownership di ListLeads — lihat internal/db/ownership.go. Ownership
// lead memakai SATU kolom (lead_owner), beda dari accounts yang tiga kolom.
//
// entity_code (LEAD-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
// dioper ke CreateLead. Field region/kontak mentah (province/mobile_phone/dst)
// karena lead belum jadi account — konversi yang memindahkannya.
// Buat lead. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
// entity_code sudah dirakit pemanggil (GenerateEntityCode).
func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.TenantID,
		arg.EntityCode,
		arg.LeadName,
		arg.LeadOwner,
		arg.ContactPerson,
		arg.JobTitle,
		arg.LeadSource,
		arg.LeadStatus,
		arg.Rating,
		arg.UnqualifiedReason,
		arg.EstimatedValue,
		arg.DistrictID,
		arg.MobilePhone,
		arg.Whatsapp,
		arg.Email,
		arg.CreatedBy,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.LeadOwner,
		&i.LeadName,
		&i.ContactPerson,
		&i.JobTitle,
		&i.LeadSource,
		&i.LeadStatus,
		&i.Rating,
		&i.UnqualifiedReason,
		&i.EstimatedValue,
		&i.ProvinceLegacy,
		&i.RegencyLegacy,
		&i.DistrictLegacy,
		&i.MobilePhone,
		&i.Whatsapp,
		&i.Email,
		&i.Converted,
		&i.ConvertedAccountID,
		&i.ConvertedContactID,
		&i.ConvertedDealID,
		&i.ConvertedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DistrictID,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE id = $1 AND deleted_at IS NULL
`

// Satu lead hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
// ter-soft-delete. Ownership diputuskan handler (LeadsListFilter.Allows) atas baris.
func (q *Queries) GetLead(ctx context.Context, id int64) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.LeadOwner,
		&i.LeadName,
		&i.ContactPerson,
		&i.JobTitle,
		&i.LeadSource,
		&i.LeadStatus,
		&i.Rating,
		&i.UnqualifiedReason,
		&i.EstimatedValue,
		&i.ProvinceLegacy,
		&i.RegencyLegacy,
		&i.DistrictLegacy,
		&i.MobilePhone,
		&i.Whatsapp,
		&i.Email,
		&i.Converted,
		&i.ConvertedAccountID,
		&i.ConvertedContactID,
		&i.ConvertedDealID,
		&i.ConvertedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DistrictID,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND lead_owner = $5)
  )
  AND (NOT $6::boolean OR lead_owner = $5)
  AND ($7::text = '' OR lead_status = $7::text)
  AND (
      $8::text = ''
      OR lead_name ILIKE '%' || $8 || '%'
      OR entity_code ILIKE '%' || $8 || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListLeadsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	MineOnly        bool               `json:"mine_only"`
	StatusFilter    string             `json:"status_filter"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Daftar lead, keyset (created_at DESC, id DESC) + filter ownership F3 + tab.
//
// Ownership sebagai dua flag boolean (bukan SQL dinamis) supaya query tetap sqlc
// murni & ter-scan typed — sumber SATU dengan LeadsListFilter (ownership.go):
//
//	scope_all → lihat semua (Admin/Manager)
//	is_own    → hanya lead_owner = uid (Sales)
//
// Keduanya false (Support/role kosong/liar) → NOL baris (fail-closed).
//
// Tab tambahan (ortogonal dari ownership):
//
//	mine_only  → paksa lead_owner = uid (tab "My Leads", walau aktor scope_all)
//	status_filter '' → semua status; selain itu = filter satu status ("Unqualified")
//
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership+tab — tak pernah melebarkan baris yang boleh
// dilihat aktor. Hanya kolom yang DITAMPILKAN tak-tersamar di daftar (lead_name +
// entity_code); PII (telepon/email) tak ikut agar search bukan jalur enumerasi
// data tersamar. Tetap keyset+LIMIT. Trigram/index ditunda (dataset kecil).
func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByNameDistrictCI = `-- name: ListLeadsByNameDistrictCI :many
SELECT lower(trim(lead_name))::text AS name_ci, district_id FROM leads
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND lower(trim(lead_name)) = ANY($2::text[])
  AND district_id = ANY($3::bigint[])
`

type ListLeadsByNameDistrictCIParams struct {
	TenantID    int64    `json:"tenant_id"`
	Names       []string `json:"names"`
	DistrictIds []int64  `json:"district_ids"`
}

type ListLeadsByNameDistrictCIRow struct {
	NameCi     string `json:"name_ci"`
	DistrictID *int64 `json:"district_id"`
}

// BL-133 follow-up — cek KOMBINASI lead_name + district_id sekaligus
// (pratinjau impor CSV, hindari N+1 Rule 13, mirror pola batch
// ListAccountsByVillageCodes). SOFT-WARNING saja (leadImportRowWarnings,
// sales_leads_import_warn.go): satu peringatan gabungan HANYA muncul bila
// nama DAN kecamatan baris CSV itu SAMA-SAMA cocok dgn satu lead lain yang
// hidup di tenant ini — nama-sama-saja atau kecamatan-sama-saja TIDAK
// cukup (revisi user 16 Sep: bukan dua peringatan independen). Filter
// `= ANY(names)` DAN `= ANY(district_ids)` sekadar MEMPERSEMPIT baris
// kandidat lewat kedua index (idx_leads_name_ci migrasi 00048 +
// idx_leads_district migrasi 00027) — HASIL BUKAN cross-product, tiap baris
// balikan adalah kombinasi ASLI yang benar-benar tersimpan bersama di satu
// baris `leads`; pencocokan kombinasi PERSIS per baris CSV dilakukan ULANG
// di Go. Pemanggil mengoper `names` yang SUDAH dinormalisasi (lower+trim
// di Go).
func (q *Queries) ListLeadsByNameDistrictCI(ctx context.Context, arg ListLeadsByNameDistrictCIParams) ([]ListLeadsByNameDistrictCIRow, error) {
	rows, err := q.db.Query(ctx, listLeadsByNameDistrictCI, arg.TenantID, arg.Names, arg.DistrictIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadsByNameDistrictCIRow{}
	for rows.Next() {
		var i ListLeadsByNameDistrictCIRow
		if err := rows.Scan(&i.NameCi, &i.DistrictID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortByCode = `-- name: ListLeadsSortByCode :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (entity_code IS NULL OR (entity_code, id) > ($4::text, $5::bigint)))
          OR ($3::boolean AND entity_code IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (entity_code IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND entity_code IS NOT NULL
              AND (entity_code, id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND lead_owner = $8)
  )
  AND (NOT $9::boolean OR lead_owner = $8)
  AND ($10::text = '' OR lead_status = $10::text)
  AND (
      $11::text = ''
      OR lead_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN entity_code END ASC,
  CASE WHEN $2::text = 'desc' THEN entity_code END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListLeadsSortByCodeParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157b: sort by entity_code ("Kode"). NULLABLE (entity_code diisi
// GenerateEntityCode saat create, tapi kolom tetap nullable di skema). Pola
// null-aware SAMA dgn ListSubscriptionsSortByPlan — cursor_is_null menandai
// kelompok NULL/non-NULL lintas-request; NULLS default Postgres (ASC=LAST,
// DESC=FIRST).
func (q *Queries) ListLeadsSortByCode(ctx context.Context, arg ListLeadsSortByCodeParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortByCode,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortByName = `-- name: ListLeadsSortByName :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (lead_name, id) > ($3::text, $4::bigint))
      OR ($2::text = 'desc'
          AND (lead_name, id) < ($3::text, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND lead_owner = $7)
  )
  AND (NOT $8::boolean OR lead_owner = $7)
  AND ($9::text = '' OR lead_status = $9::text)
  AND (
      $10::text = ''
      OR lead_name ILIKE '%' || $10 || '%'
      OR entity_code ILIKE '%' || $10 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN lead_name END ASC,
  CASE WHEN $2::text = 'desc' THEN lead_name END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $11
`

type ListLeadsSortByNameParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157b (fondasi sort per kolom Leads): SAMA PERSIS filter ListLeads
// (ownership F3 + mine_only + status_filter + search) — hanya ORDER BY/keyset
// yang beda, diurut lead_name (bukan created_at). lead_name TIDAK NULLABLE →
// kloning pola ListSubscriptionsSortByVillage (tanpa kerumitan NULL). Sort
// HANYA berdasar lead_name (baris bold di sel), BUKAN gabungan dgn
// contact_person (subteks) — mirror keputusan "Desa" BL-157a.
func (q *Queries) ListLeadsSortByName(ctx context.Context, arg ListLeadsSortByNameParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortByName,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortByOwner = `-- name: ListLeadsSortByOwner :many
SELECT leads.id, leads.tenant_id, leads.entity_code, leads.lead_owner, leads.lead_name, leads.contact_person, leads.job_title, leads.lead_source, leads.lead_status, leads.rating, leads.unqualified_reason, leads.estimated_value, leads.province_legacy, leads.regency_legacy, leads.district_legacy, leads.mobile_phone, leads.whatsapp, leads.email, leads.converted, leads.converted_account_id, leads.converted_contact_id, leads.converted_deal_id, leads.converted_at, leads.deleted_at, leads.created_by, leads.created_at, leads.updated_by, leads.updated_at, leads.district_id FROM leads
LEFT JOIN users u ON u.id = lead_owner
WHERE leads.deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NULL
                OR (COALESCE(NULLIF(u.name, ''), u.email), leads.id) > ($4::text, $5::bigint)))
          OR ($3::boolean
              AND COALESCE(NULLIF(u.name, ''), u.email) IS NULL AND leads.id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL OR leads.id < $5::bigint))
          OR (NOT $3::boolean AND COALESCE(NULLIF(u.name, ''), u.email) IS NOT NULL
              AND (COALESCE(NULLIF(u.name, ''), u.email), leads.id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND lead_owner = $8)
  )
  AND (NOT $9::boolean OR lead_owner = $8)
  AND ($10::text = '' OR lead_status = $10::text)
  AND (
      $11::text = ''
      OR lead_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN COALESCE(NULLIF(u.name, ''), u.email) END ASC,
  CASE WHEN $2::text = 'desc' THEN COALESCE(NULLIF(u.name, ''), u.email) END DESC,
  CASE WHEN $2::text = 'asc'  THEN leads.id END ASC,
  CASE WHEN $2::text = 'desc' THEN leads.id END DESC
LIMIT $12
`

type ListLeadsSortByOwnerParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157b: sort by CSM Pemilik (lead_owner). Kunci sort HARUS
// COALESCE(NULLIF(u.name,”), u.email) — PERSIS logika tampil ownerName/
// memberNameMap (sales_leads_detail.go: nama bila terisi, else email) — agar
// urutan tak menyimpang dari yang ditampilkan. NULLABLE (lead_owner ON DELETE
// SET NULL). LEFT JOIN users: baris tanpa owner ATAU owner terhapus →
// owner_key NULL, masuk kelompok NULL (default Postgres). Mirror PERSIS
// ListSubscriptionsSortByCsm.
func (q *Queries) ListLeadsSortByOwner(ctx context.Context, arg ListLeadsSortByOwnerParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortByOwner,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortByRating = `-- name: ListLeadsSortByRating :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (rating IS NULL OR (rating, id) > ($4::text, $5::bigint)))
          OR ($3::boolean AND rating IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (rating IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND rating IS NOT NULL
              AND (rating, id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND lead_owner = $8)
  )
  AND (NOT $9::boolean OR lead_owner = $8)
  AND ($10::text = '' OR lead_status = $10::text)
  AND (
      $11::text = ''
      OR lead_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN rating END ASC,
  CASE WHEN $2::text = 'desc' THEN rating END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListLeadsSortByRatingParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157b: sort by rating ("Rating" — RAW enum Cold/Hot/Warm, alfabetis;
// keputusan user: BUKAN urutan tingkat Hot→Warm→Cold, mirror keputusan
// "Masa Berlaku" BL-157a — tak menduplikasi logika prioritas ke SQL).
// NULLABLE. Pola null-aware PERSIS ListLeadsSortByCode.
func (q *Queries) ListLeadsSortByRating(ctx context.Context, arg ListLeadsSortByRatingParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortByRating,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortBySource = `-- name: ListLeadsSortBySource :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (lead_source IS NULL OR (lead_source, id) > ($4::text, $5::bigint)))
          OR ($3::boolean AND lead_source IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (lead_source IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND lead_source IS NOT NULL
              AND (lead_source, id) < ($4::text, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND lead_owner = $8)
  )
  AND (NOT $9::boolean OR lead_owner = $8)
  AND ($10::text = '' OR lead_status = $10::text)
  AND (
      $11::text = ''
      OR lead_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN lead_source END ASC,
  CASE WHEN $2::text = 'desc' THEN lead_source END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListLeadsSortBySourceParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorIsNull bool   `json:"cursor_is_null"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157b: sort by lead_source ("Sumber"). NULLABLE. Pola null-aware PERSIS
// ListLeadsSortByCode, kolom beda.
func (q *Queries) ListLeadsSortBySource(ctx context.Context, arg ListLeadsSortBySourceParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortBySource,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortByStatus = `-- name: ListLeadsSortByStatus :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc'
          AND (lead_status, id) > ($3::text, $4::bigint))
      OR ($2::text = 'desc'
          AND (lead_status, id) < ($3::text, $4::bigint))
  )
  AND (
      $5::boolean
      OR ($6::boolean AND lead_owner = $7)
  )
  AND (NOT $8::boolean OR lead_owner = $7)
  AND ($9::text = '' OR lead_status = $9::text)
  AND (
      $10::text = ''
      OR lead_name ILIKE '%' || $10 || '%'
      OR entity_code ILIKE '%' || $10 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN lead_status END ASC,
  CASE WHEN $2::text = 'desc' THEN lead_status END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $11
`

type ListLeadsSortByStatusParams struct {
	HasCursor    bool   `json:"has_cursor"`
	Dir          string `json:"dir"`
	CursorVal    string `json:"cursor_val"`
	CursorID     int64  `json:"cursor_id"`
	ScopeAll     bool   `json:"scope_all"`
	IsOwn        bool   `json:"is_own"`
	Uid          *int64 `json:"uid"`
	MineOnly     bool   `json:"mine_only"`
	StatusFilter string `json:"status_filter"`
	Search       string `json:"search"`
	PageSize     int32  `json:"page_size"`
}

// BL-157b: sort by lead_status ("Status" — RAW enum New/Contacted/Qualified/
// Unqualified/Converted, alfabetis; tak menduplikasi urutan tingkat ke SQL,
// mirror keputusan "Masa Berlaku" BL-157a). lead_status NOT NULL → kloning
// PERSIS pola ListLeadsSortByName.
func (q *Queries) ListLeadsSortByStatus(ctx context.Context, arg ListLeadsSortByStatusParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortByStatus,
		arg.HasCursor,
		arg.Dir,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsSortByValue = `-- name: ListLeadsSortByValue :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (
      NOT $1::boolean
      OR ($2::text = 'asc' AND (
          (NOT $3::boolean
           AND (estimated_value IS NULL OR (estimated_value, id) > ($4::numeric, $5::bigint)))
          OR ($3::boolean AND estimated_value IS NULL AND id > $5::bigint)
      ))
      OR ($2::text = 'desc' AND (
          ($3::boolean
           AND (estimated_value IS NOT NULL OR id < $5::bigint))
          OR (NOT $3::boolean AND estimated_value IS NOT NULL
              AND (estimated_value, id) < ($4::numeric, $5::bigint))
      ))
  )
  AND (
      $6::boolean
      OR ($7::boolean AND lead_owner = $8)
  )
  AND (NOT $9::boolean OR lead_owner = $8)
  AND ($10::text = '' OR lead_status = $10::text)
  AND (
      $11::text = ''
      OR lead_name ILIKE '%' || $11 || '%'
      OR entity_code ILIKE '%' || $11 || '%'
  )
ORDER BY
  CASE WHEN $2::text = 'asc'  THEN estimated_value END ASC,
  CASE WHEN $2::text = 'desc' THEN estimated_value END DESC,
  CASE WHEN $2::text = 'asc'  THEN id END ASC,
  CASE WHEN $2::text = 'desc' THEN id END DESC
LIMIT $12
`

type ListLeadsSortByValueParams struct {
	HasCursor    bool           `json:"has_cursor"`
	Dir          string         `json:"dir"`
	CursorIsNull bool           `json:"cursor_is_null"`
	CursorVal    pgtype.Numeric `json:"cursor_val"`
	CursorID     int64          `json:"cursor_id"`
	ScopeAll     bool           `json:"scope_all"`
	IsOwn        bool           `json:"is_own"`
	Uid          *int64         `json:"uid"`
	MineOnly     bool           `json:"mine_only"`
	StatusFilter string         `json:"status_filter"`
	Search       string         `json:"search"`
	PageSize     int32          `json:"page_size"`
}

// BL-157b: sort by estimated_value ("Estimasi"). NULLABLE numeric. Kunci sort
// memakai nilai ASLI (tak ter-mask) — F4 (maskARR) hanya menyamarkan TAMPILAN
// di handler, mirror presedan MRR BL-157a (ListSubscriptionsSortByMrr). Pola
// null-aware SAMA dgn ListLeadsSortByCode, tipe kolom numeric bukan text.
func (q *Queries) ListLeadsSortByValue(ctx context.Context, arg ListLeadsSortByValueParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsSortByValue,
		arg.HasCursor,
		arg.Dir,
		arg.CursorIsNull,
		arg.CursorVal,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLeadConverted = `-- name: MarkLeadConverted :exec
UPDATE leads SET
    converted            = true,
    converted_account_id = $1,
    converted_contact_id = $2,
    converted_deal_id    = $3,
    converted_at         = now(),
    lead_status          = 'Converted',
    updated_by           = $4,
    updated_at           = now()
WHERE id = $5 AND deleted_at IS NULL
  AND lead_status = 'Qualified' AND NOT converted
`

type MarkLeadConvertedParams struct {
	ConvertedAccountID *int64 `json:"converted_account_id"`
	ConvertedContactID *int64 `json:"converted_contact_id"`
	ConvertedDealID    *int64 `json:"converted_deal_id"`
	UpdatedBy          *int64 `json:"updated_by"`
	ID                 int64  `json:"id"`
}

// Tautkan hasil konversi ke lead + kunci statusnya. Dipanggil DALAM tx konversi
// (bersama INSERT account/contact/deal) → gagal-sebagian rollback penuh. Guard
// "hanya Qualified & belum converted" ada di WHERE agar konversi ganda idempotent-
// aman: baris yang sudah converted tak ter-update lagi.
func (q *Queries) MarkLeadConverted(ctx context.Context, arg MarkLeadConvertedParams) error {
	_, err := q.db.Exec(ctx, markLeadConverted,
		arg.ConvertedAccountID,
		arg.ConvertedContactID,
		arg.ConvertedDealID,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const softDeleteLead = `-- name: SoftDeleteLead :exec
UPDATE leads SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteLeadParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK
// converted_* tak putus). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error {
	_, err := q.db.Exec(ctx, softDeleteLead, arg.UpdatedBy, arg.ID)
	return err
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads SET
    lead_name          = $1,
    lead_owner         = $2,
    contact_person     = $3,
    job_title          = $4,
    lead_source        = $5,
    lead_status        = $6,
    rating             = $7,
    unqualified_reason = $8,
    estimated_value    = $9,
    district_id        = $10,
    mobile_phone       = $11,
    whatsapp           = $12,
    email              = $13,
    updated_by         = $14,
    updated_at         = now()
WHERE id = $15 AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id
`

type UpdateLeadParams struct {
	LeadName          string         `json:"lead_name"`
	LeadOwner         *int64         `json:"lead_owner"`
	ContactPerson     *string        `json:"contact_person"`
	JobTitle          *string        `json:"job_title"`
	LeadSource        *string        `json:"lead_source"`
	LeadStatus        string         `json:"lead_status"`
	Rating            *string        `json:"rating"`
	UnqualifiedReason *string        `json:"unqualified_reason"`
	EstimatedValue    pgtype.Numeric `json:"estimated_value"`
	DistrictID        *int64         `json:"district_id"`
	MobilePhone       *string        `json:"mobile_phone"`
	Whatsapp          *string        `json:"whatsapp"`
	Email             *string        `json:"email"`
	UpdatedBy         *int64         `json:"updated_by"`
	ID                int64          `json:"id"`
}

// Sunting profil & kualifikasi lead. entity_code tak diubah (kode identitas yang
// dikutip). converted_* TAK disentuh di sini — itu efek konversi (ConvertLead),
// bukan edit biasa.
func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.LeadName,
		arg.LeadOwner,
		arg.ContactPerson,
		arg.JobTitle,
		arg.LeadSource,
		arg.LeadStatus,
		arg.Rating,
		arg.UnqualifiedReason,
		arg.EstimatedValue,
		arg.DistrictID,
		arg.MobilePhone,
		arg.Whatsapp,
		arg.Email,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.LeadOwner,
		&i.LeadName,
		&i.ContactPerson,
		&i.JobTitle,
		&i.LeadSource,
		&i.LeadStatus,
		&i.Rating,
		&i.UnqualifiedReason,
		&i.EstimatedValue,
		&i.ProvinceLegacy,
		&i.RegencyLegacy,
		&i.DistrictLegacy,
		&i.MobilePhone,
		&i.Whatsapp,
		&i.Email,
		&i.Converted,
		&i.ConvertedAccountID,
		&i.ConvertedContactID,
		&i.ConvertedDealID,
		&i.ConvertedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DistrictID,
	)
	return i, err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :exec
UPDATE leads SET
    lead_status        = $1,
    unqualified_reason = $2,
    updated_by         = $3,
    updated_at         = now()
WHERE id = $4 AND deleted_at IS NULL AND NOT converted
`

type UpdateLeadStatusParams struct {
	LeadStatus        string  `json:"lead_status"`
	UnqualifiedReason *string `json:"unqualified_reason"`
	UpdatedBy         *int64  `json:"updated_by"`
	ID                int64   `json:"id"`
}

// BL-83: transisi STATUS lead sebagai aksi tersendiri (bukan efek edit profil),
// cermin UpdateDealStage. Hanya lead_status + unqualified_reason (terkopel status
// Unqualified, BL-80) yang disentuh — profil lead tak diubah di sini. Transisi
// BEBAS antar-status manual (keputusan BL-83); 'Converted' TAK dapat dicapai lewat
// jalur ini: guard `AND NOT converted` menolak baris hasil konversi agar invariant
// "converted = terminal" tak bisa dipalsukan (handler juga menyembunyikan kontrol).
func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) error {
	_, err := q.db.Exec(ctx, updateLeadStatus,
		arg.LeadStatus,
		arg.UnqualifiedReason,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
