// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLead = `-- name: CreateLead :one

INSERT INTO leads (
    tenant_id, entity_code, lead_name, lead_owner,
    contact_person, job_title, lead_source,
    lead_status, rating, unqualified_reason, estimated_value,
    district_id, mobile_phone, whatsapp, email,
    created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11,
    $12,
    $13, $14, $15,
    $16
)
RETURNING id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id
`

type CreateLeadParams struct {
	TenantID          int64          `json:"tenant_id"`
	EntityCode        *string        `json:"entity_code"`
	LeadName          string         `json:"lead_name"`
	LeadOwner         *int64         `json:"lead_owner"`
	ContactPerson     *string        `json:"contact_person"`
	JobTitle          *string        `json:"job_title"`
	LeadSource        *string        `json:"lead_source"`
	LeadStatus        string         `json:"lead_status"`
	Rating            *string        `json:"rating"`
	UnqualifiedReason *string        `json:"unqualified_reason"`
	EstimatedValue    pgtype.Numeric `json:"estimated_value"`
	DistrictID        *int64         `json:"district_id"`
	MobilePhone       *string        `json:"mobile_phone"`
	Whatsapp          *string        `json:"whatsapp"`
	Email             *string        `json:"email"`
	CreatedBy         *int64         `json:"created_by"`
}

// leads.sql — funnel Sales (Lead). Isolasi WORKSPACE ditegakkan RLS (GUC
// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
// lewat flag ownership di ListLeads — lihat internal/db/ownership.go. Ownership
// lead memakai SATU kolom (lead_owner), beda dari accounts yang tiga kolom.
//
// entity_code (LEAD-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
// dioper ke CreateLead. Field region/kontak mentah (province/mobile_phone/dst)
// karena lead belum jadi account — konversi yang memindahkannya.
// Buat lead. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
// entity_code sudah dirakit pemanggil (GenerateEntityCode).
func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.TenantID,
		arg.EntityCode,
		arg.LeadName,
		arg.LeadOwner,
		arg.ContactPerson,
		arg.JobTitle,
		arg.LeadSource,
		arg.LeadStatus,
		arg.Rating,
		arg.UnqualifiedReason,
		arg.EstimatedValue,
		arg.DistrictID,
		arg.MobilePhone,
		arg.Whatsapp,
		arg.Email,
		arg.CreatedBy,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.LeadOwner,
		&i.LeadName,
		&i.ContactPerson,
		&i.JobTitle,
		&i.LeadSource,
		&i.LeadStatus,
		&i.Rating,
		&i.UnqualifiedReason,
		&i.EstimatedValue,
		&i.ProvinceLegacy,
		&i.RegencyLegacy,
		&i.DistrictLegacy,
		&i.MobilePhone,
		&i.Whatsapp,
		&i.Email,
		&i.Converted,
		&i.ConvertedAccountID,
		&i.ConvertedContactID,
		&i.ConvertedDealID,
		&i.ConvertedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DistrictID,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE id = $1 AND deleted_at IS NULL
`

// Satu lead hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
// ter-soft-delete. Ownership diputuskan handler (LeadsListFilter.Allows) atas baris.
func (q *Queries) GetLead(ctx context.Context, id int64) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.LeadOwner,
		&i.LeadName,
		&i.ContactPerson,
		&i.JobTitle,
		&i.LeadSource,
		&i.LeadStatus,
		&i.Rating,
		&i.UnqualifiedReason,
		&i.EstimatedValue,
		&i.ProvinceLegacy,
		&i.RegencyLegacy,
		&i.DistrictLegacy,
		&i.MobilePhone,
		&i.Whatsapp,
		&i.Email,
		&i.Converted,
		&i.ConvertedAccountID,
		&i.ConvertedContactID,
		&i.ConvertedDealID,
		&i.ConvertedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DistrictID,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id FROM leads
WHERE deleted_at IS NULL
  AND (created_at, id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND lead_owner = $5)
  )
  AND (NOT $6::boolean OR lead_owner = $5)
  AND ($7::text = '' OR lead_status = $7::text)
  AND (
      $8::text = ''
      OR lead_name ILIKE '%' || $8 || '%'
      OR entity_code ILIKE '%' || $8 || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type ListLeadsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	MineOnly        bool               `json:"mine_only"`
	StatusFilter    string             `json:"status_filter"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

// Daftar lead, keyset (created_at DESC, id DESC) + filter ownership F3 + tab.
//
// Ownership sebagai dua flag boolean (bukan SQL dinamis) supaya query tetap sqlc
// murni & ter-scan typed — sumber SATU dengan LeadsListFilter (ownership.go):
//
//	scope_all → lihat semua (Admin/Manager)
//	is_own    → hanya lead_owner = uid (Sales)
//
// Keduanya false (Support/role kosong/liar) → NOL baris (fail-closed).
//
// Tab tambahan (ortogonal dari ownership):
//
//	mine_only  → paksa lead_owner = uid (tab "My Leads", walau aktor scope_all)
//	status_filter '' → semua status; selain itu = filter satu status ("Unqualified")
//
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership+tab — tak pernah melebarkan baris yang boleh
// dilihat aktor. Hanya kolom yang DITAMPILKAN tak-tersamar di daftar (lead_name +
// entity_code); PII (telepon/email) tak ikut agar search bukan jalur enumerasi
// data tersamar. Tetap keyset+LIMIT. Trigram/index ditunda (dataset kecil).
func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.MineOnly,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.LeadOwner,
			&i.LeadName,
			&i.ContactPerson,
			&i.JobTitle,
			&i.LeadSource,
			&i.LeadStatus,
			&i.Rating,
			&i.UnqualifiedReason,
			&i.EstimatedValue,
			&i.ProvinceLegacy,
			&i.RegencyLegacy,
			&i.DistrictLegacy,
			&i.MobilePhone,
			&i.Whatsapp,
			&i.Email,
			&i.Converted,
			&i.ConvertedAccountID,
			&i.ConvertedContactID,
			&i.ConvertedDealID,
			&i.ConvertedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLeadConverted = `-- name: MarkLeadConverted :exec
UPDATE leads SET
    converted            = true,
    converted_account_id = $1,
    converted_contact_id = $2,
    converted_deal_id    = $3,
    converted_at         = now(),
    lead_status          = 'Converted',
    updated_by           = $4,
    updated_at           = now()
WHERE id = $5 AND deleted_at IS NULL
  AND lead_status = 'Qualified' AND NOT converted
`

type MarkLeadConvertedParams struct {
	ConvertedAccountID *int64 `json:"converted_account_id"`
	ConvertedContactID *int64 `json:"converted_contact_id"`
	ConvertedDealID    *int64 `json:"converted_deal_id"`
	UpdatedBy          *int64 `json:"updated_by"`
	ID                 int64  `json:"id"`
}

// Tautkan hasil konversi ke lead + kunci statusnya. Dipanggil DALAM tx konversi
// (bersama INSERT account/contact/deal) → gagal-sebagian rollback penuh. Guard
// "hanya Qualified & belum converted" ada di WHERE agar konversi ganda idempotent-
// aman: baris yang sudah converted tak ter-update lagi.
func (q *Queries) MarkLeadConverted(ctx context.Context, arg MarkLeadConvertedParams) error {
	_, err := q.db.Exec(ctx, markLeadConverted,
		arg.ConvertedAccountID,
		arg.ConvertedContactID,
		arg.ConvertedDealID,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const softDeleteLead = `-- name: SoftDeleteLead :exec
UPDATE leads SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteLeadParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK
// converted_* tak putus). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error {
	_, err := q.db.Exec(ctx, softDeleteLead, arg.UpdatedBy, arg.ID)
	return err
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads SET
    lead_name          = $1,
    lead_owner         = $2,
    contact_person     = $3,
    job_title          = $4,
    lead_source        = $5,
    lead_status        = $6,
    rating             = $7,
    unqualified_reason = $8,
    estimated_value    = $9,
    district_id        = $10,
    mobile_phone       = $11,
    whatsapp           = $12,
    email              = $13,
    updated_by         = $14,
    updated_at         = now()
WHERE id = $15 AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, lead_owner, lead_name, contact_person, job_title, lead_source, lead_status, rating, unqualified_reason, estimated_value, province_legacy, regency_legacy, district_legacy, mobile_phone, whatsapp, email, converted, converted_account_id, converted_contact_id, converted_deal_id, converted_at, deleted_at, created_by, created_at, updated_by, updated_at, district_id
`

type UpdateLeadParams struct {
	LeadName          string         `json:"lead_name"`
	LeadOwner         *int64         `json:"lead_owner"`
	ContactPerson     *string        `json:"contact_person"`
	JobTitle          *string        `json:"job_title"`
	LeadSource        *string        `json:"lead_source"`
	LeadStatus        string         `json:"lead_status"`
	Rating            *string        `json:"rating"`
	UnqualifiedReason *string        `json:"unqualified_reason"`
	EstimatedValue    pgtype.Numeric `json:"estimated_value"`
	DistrictID        *int64         `json:"district_id"`
	MobilePhone       *string        `json:"mobile_phone"`
	Whatsapp          *string        `json:"whatsapp"`
	Email             *string        `json:"email"`
	UpdatedBy         *int64         `json:"updated_by"`
	ID                int64          `json:"id"`
}

// Sunting profil & kualifikasi lead. entity_code tak diubah (kode identitas yang
// dikutip). converted_* TAK disentuh di sini — itu efek konversi (ConvertLead),
// bukan edit biasa.
func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.LeadName,
		arg.LeadOwner,
		arg.ContactPerson,
		arg.JobTitle,
		arg.LeadSource,
		arg.LeadStatus,
		arg.Rating,
		arg.UnqualifiedReason,
		arg.EstimatedValue,
		arg.DistrictID,
		arg.MobilePhone,
		arg.Whatsapp,
		arg.Email,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.LeadOwner,
		&i.LeadName,
		&i.ContactPerson,
		&i.JobTitle,
		&i.LeadSource,
		&i.LeadStatus,
		&i.Rating,
		&i.UnqualifiedReason,
		&i.EstimatedValue,
		&i.ProvinceLegacy,
		&i.RegencyLegacy,
		&i.DistrictLegacy,
		&i.MobilePhone,
		&i.Whatsapp,
		&i.Email,
		&i.Converted,
		&i.ConvertedAccountID,
		&i.ConvertedContactID,
		&i.ConvertedDealID,
		&i.ConvertedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DistrictID,
	)
	return i, err
}
