// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Tandai terpakai (one-time). Guard accepted_at IS NULL → race dua klik tak
	// menghasilkan dua membership (UNIQUE di memberships jadi jaring kedua).
	AcceptInvite(ctx context.Context, token string) error
	AddPlatformStaff(ctx context.Context, email string) (PlatformStaff, error)
	// OWNER. Workspace jadi READ-ONLY tapi datanya utuh. Guard `status = 'active'`
	// mencegah archive menimpa SUSPENSI platform — kalau tidak, owner bisa keluar
	// dari suspensi lewat pintu samping (archive lalu unarchive).
	//
	// `NOT is_primary`: mengarsipkan rumah aplikasi menjadikan SELURUH aplikasi
	// read-only lewat tombol yang tampak rutin. Guard-nya di SQL, bukan cuma di
	// handler — jalur yang tak lewat handler pun harus tertahan.
	ArchiveTenant(ctx context.Context, id int64) error
	// Penugasan CSM (binaan + cadangan) — jalur terpisah dari edit profil (§8.1).
	// NULL = lepas penugasan. updated_by/at ikut agar jejaknya jelas.
	AssignAccountCSM(ctx context.Context, arg AssignAccountCSMParams) error
	// Lepas penanda utama dari SEMUA kontak hidup satu desa. Dipanggil SEBELUM
	// memasang primary baru (create/update/set-primary) supaya idx_contacts_primary
	// (maks 1 utama per desa) tak pernah dilanggar. Idempotent: nol baris bila belum
	// ada utama.
	ClearAccountPrimaryContact(ctx context.Context, arg ClearAccountPrimaryContactParams) error
	// Jumlah peristiwa per KELUARGA aksi pada rentang ini (auth, workspace, member,
	// user, invite, settings, platform) — dipakai untuk melabeli opsi filter dengan
	// angka, sehingga operator tahu mana yang berisi sebelum mengkliknya.
	//
	// split_part di segmen pertama: penamaan aksi kita selalu `keluarga.sisanya`
	// (auth.login, workspace.create, member.role.update), jadi keluarga bisa
	// diturunkan tanpa tabel pemetaan yang harus dijaga selaras.
	CountActivityByAction(ctx context.Context, arg CountActivityByActionParams) ([]CountActivityByActionRow, error)
	// Jumlah kontak hidup satu desa — untuk badge/ringkasan di detail desa. Murah:
	// idx_contacts_account (partial WHERE deleted_at IS NULL) melayaninya langsung.
	CountContactsByAccount(ctx context.Context, accountID int64) (int64, error)
	// Berapa workspace yang DIMILIKI user (role owner) — untuk cek kuota sebelum
	// membuat workspace baru. Diundang jadi member/admin TIDAK memakan kuota.
	//
	// Workspace TERHAPUS tak dihitung (0005 §7): kuota yang masih tertahan oleh
	// workspace yang sudah dihapus terasa seperti bug, dan mendorong user memurge
	// lebih cepat — kebalikan dari tujuan masa tenggang. Yang TERARSIP TETAP
	// dihitung: datanya masih disimpan & bisa diaktifkan kapan saja.
	//
	// Workspace PRIMER juga tak dihitung (0007): kuota membatasi berapa banyak yang
	// boleh DIBUAT, dan rumah aplikasi tak dibuat siapa pun — ia sudah ada sebelum
	// user pertama mendaftar. Tanpa pengecualian ini, super_admin yang jadi ownernya
	// memakai jatahnya sendiri, dan dengan default 1 orang yang MENETAPKAN aturan
	// kuota justru tak bisa membuat workspace apa pun.
	CountOwnedWorkspaces(ctx context.Context, userID int64) (int64, error)
	// Bagian "perlu tindakan" dari badge. Undangan pending SENGAJA tak pernah
	// ter-auto-read: ia tugas, bukan kabar — lihat MarkNotificationsRead.
	CountPendingInvitesByEmail(ctx context.Context, email string) (int64, error)
	// Berapa user memegang HAK KHUSUS (kuota di-override, bukan mengikuti global).
	// Dipakai halaman pengaturan untuk menyatakan dampak sebelum operator menyimpan:
	// mereka SENGAJA tak ikut berubah, dan tanpa angka ini operator mengira
	// pengaturannya tak bekerja.
	CountQuotaOverrides(ctx context.Context) (int64, error)
	// Jumlah owner di satu workspace — cegah menghapus/menurunkan owner terakhir
	// (workspace tanpa owner = yatim).
	CountTenantOwners(ctx context.Context, tenantID int64) (int64, error)
	CountTenantsForPlatform(ctx context.Context) (int64, error)
	// Badge sidebar — dirender di SETIAP halaman, ditopang index partial
	// idx_notif_unread agar tak menyentuh baris yang sudah terbaca.
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	// accounts.sql — hub Desa (Account). Isolasi WORKSPACE ditegakkan RLS (GUC
	// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
	// lewat flag ownership di ListAccounts — lihat internal/db/ownership.go.
	//
	// entity_code (DESA-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
	// dioper ke CreateAccount; village_code (Kode Kemendagri) datang dari user & boleh
	// kosong. Dua kode berbeda asal, keduanya disimpan di baris.
	// Buat desa. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// entity_code sudah dirakit pemanggil (GenerateEntityCode) — INSERT-nya dijaga
	// unik oleh idx_accounts_entity_code bila format diubah bertabrakan.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Jejak aksi admin. metadata TANPA PII (id saja, bukan email/nama).
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Buat peran baru (atau seed default). name = subject Casbin & nilai
	// memberships.business_role; display_name = label layar; description = keterangan
	// satu baris (kolom Deskripsi wireframe 9.2, boleh ''). is_system hanya true untuk
	// seed admin. created_by NULL untuk seed migrasi/boot.
	CreateBusinessRole(ctx context.Context, arg CreateBusinessRoleParams) (CreateBusinessRoleRow, error)
	// contacts.sql — orang di dalam sebuah desa (Contact), 1:N ke accounts. Isolasi
	// WORKSPACE ditegakkan RLS (GUC app.tenant_id di WithTenant, tenant_id di-AND-kan
	// otomatis). Isolasi ANTAR-DESA (F3) TIDAK punya filter sendiri di sini: kontak
	// MEWARISI kepemilikan desa induknya (docs/crm/tasks.md §Modul 3). Maka:
	//   - daftar per-desa (ListContactsByAccount) tak menyaring ownership sama sekali —
	//     handler sudah menjaga bahwa desa induknya boleh dilihat aktor (loadOwnedAccount);
	//     begitu lolos, SEMUA kontak desa itu tampil.
	//   - daftar global (ListContacts) menyaring lewat kolom ownership DESA INDUK
	//     (JOIN accounts), memakai flag yang SAMA dengan ListAccounts — sumber tunggal
	//     AccountsListFilter. "Kontak siapa yang tampil" = "desa siapa yang tampil".
	//
	// Maks 1 kontak utama per desa dijaga idx_contacts_primary (partial UNIQUE). Set-
	// primary WAJIB dua langkah dalam satu tx: kosongkan primary lama dulu, baru pasang
	// yang baru — kalau tidak, INSERT/UPDATE bertabrakan dengan index (satu tx, satu
	// tenant, jadi tak ada balapan antar-request di jalur ini).
	// Buat kontak. account_id mengikat ke desa induk (RLS memverifikasi tenant_id =
	// GUC lewat FK + WITH CHECK). is_primary_contact di-set pemanggil SETELAH
	// mengosongkan primary lama (ClearAccountPrimaryContact) agar tak melanggar index.
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	// deals.sql — pipeline Sales (Deal). Isolasi WORKSPACE ditegakkan RLS (GUC
	// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
	// lewat flag ownership di ListDeals/ListDealsForPipeline — lihat ownership.go.
	// Ownership deal memakai SATU kolom (deal_owner).
	//
	// entity_code (DEAL-001) dialokasikan di GenerateEntityCode DALAM tx create.
	// account_id NN: deal selalu menempel ke satu desa. Deal hasil konversi lead dibuat
	// di tx konversi (bersama account+contact) — lihat handler.
	// Buat deal. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error)
	// Undangan bergabung ke workspace. token = rahasia URL (crypto/rand hex via
	// oauth.NewState). email boleh milik orang yang BELUM punya akun.
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// leads.sql — funnel Sales (Lead). Isolasi WORKSPACE ditegakkan RLS (GUC
	// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
	// lewat flag ownership di ListLeads — lihat internal/db/ownership.go. Ownership
	// lead memakai SATU kolom (lead_owner), beda dari accounts yang tiga kolom.
	//
	// entity_code (LEAD-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
	// dioper ke CreateLead. Field region/kontak mentah (province/mobile_phone/dst)
	// karena lead belum jadi account — konversi yang memindahkannya.
	// Buat lead. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// entity_code sudah dirakit pemanggil (GenerateEntityCode).
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	// Jadikan user anggota workspace dgn role tertentu. Dipakai: register/OAuth (owner
	// workspace pertama), buat workspace baru (owner), terima invite (admin/member).
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// Dipanggil saat peristiwa keanggotaan terjadi (role diubah, dikeluarkan).
	// payload = snapshot detail siap-render; lihat migrasi 00009.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	// User baru dari OAuth: tanpa password, email terverifikasi provider, + avatar
	// & nama tampilan. Keduanya nullable — provider boleh tak mengirimkannya.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	// Dipanggil SEKALI saat boot pertama. Unique partial index di tenants menjamin
	// hanya ada satu primer — dua instance yang boot bersamaan, satu akan gagal, dan
	// itu jauh lebih baik daripada dua "rumah aplikasi".
	CreatePrimaryTenant(ctx context.Context, arg CreatePrimaryTenantParams) (Tenant, error)
	// Buat tenant baru (dipanggil saat register/oauth user baru — 1 user = 1 tenant).
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// users = tabel GLOBAL (identitas murni, TANPA tenant/role — keduanya pindah ke
	// memberships). Keanggotaan dibuat terpisah via CreateMembership dalam tx sama.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// KPI ringkas pipeline dalam cakupan ownership (satu round-trip, bukan hitung di
	// Go atas seluruh baris). COALESCE(...)::bigint/::numeric membungkus agregat agar
	// sqlc tak meng-emit interface{} (gotcha #14). Win rate dihitung di Go dari
	// won_count/(won_count+lost_count) — pembagian nol ditangani di sana.
	DealPipelineStats(ctx context.Context, arg DealPipelineStatsParams) (DealPipelineStatsRow, error)
	// Tolak undangan (sisi PENERIMA). Kunci ganda token + email: penerima tak punya
	// scope ke workspace pengundang, jadi DeleteInvite (yang butuh tenant_id) tak
	// bisa dipakai. Mencocokkan email mencegah pemegang token menolak undangan
	// milik orang lain.
	DeclineInvite(ctx context.Context, arg DeclineInviteParams) error
	// Hapus peran. Perizinannya ikut (FK CASCADE); anggota yang memegangnya di-
	// unassign TERPISAH (UnassignBusinessRole) SEBELUM ini di handler — FK ke
	// memberships sengaja tak ada agar penghapusan peran bukan penghapusan orang.
	// Peran is_system ditolak di handler.
	DeleteBusinessRole(ctx context.Context, arg DeleteBusinessRoleParams) error
	// Kosongkan matriks satu peran sebelum menulis ulang (pola replace-all: handler
	// hapus semua lalu sisipkan set baru dalam satu tx — lebih sederhana & bebas
	// selisih daripada diff per-baris). CASCADE peran tak menyentuh ini; ini untuk
	// peran yang TETAP ada tapi izinnya diganti.
	DeleteBusinessRolePermissionsForRole(ctx context.Context, arg DeleteBusinessRolePermissionsForRoleParams) error
	// Batalkan undangan yang belum diterima (sisi PENGUNDANG, di panel anggota).
	DeleteInvite(ctx context.Context, arg DeleteInviteParams) error
	// Keluarkan anggota dari workspace (atau user keluar sendiri).
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	// Satu desa hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
	// ter-soft-delete. Tak menerapkan ownership — pemanggil (handler) yang memutuskan
	// apakah aktor boleh membuka baris ini (detail bisa dibuka lewat tautan langsung).
	GetAccount(ctx context.Context, id int64) (Account, error)
	// Satu peran (edit/validasi). tenant_id di predikat = pertahanan berlapis di atas
	// RLS: nama peran datang dari URL, jadi cocokkan eksplisit ke workspace aktif.
	GetBusinessRole(ctx context.Context, arg GetBusinessRoleParams) (GetBusinessRoleRow, error)
	// Cakupan desa (F3) untuk satu business_role — dibaca per-request di
	// RefreshIdentity, disimpan di session. Dipisah dari GetBusinessRole agar jalur
	// panas ini tak menarik kolom yang tak dipakainya.
	GetBusinessRoleDataScope(ctx context.Context, arg GetBusinessRoleDataScopeParams) (string, error)
	// Format kode satu (tenant, entity). Tak ada baris = SAH: pemanggil jatuh ke
	// codes.DefaultFormat (workspace baru berkode tanpa seed). pgx.ErrNoRows bukan
	// kegagalan yang perlu diributkan.
	GetCodeFormat(ctx context.Context, arg GetCodeFormatParams) (CodeFormat, error)
	// Satu kontak hidup. RLS menjamin tenant_id; deleted_at menyembunyikan yang
	// ter-soft-delete. Tak menerapkan ownership — pemanggil (handler) memutuskan lewat
	// desa INDUK apakah aktor boleh membukanya (kontak mewarisi kepemilikan desa).
	GetContact(ctx context.Context, id int64) (Contact, error)
	// Satu deal hidup. RLS menjamin tenant_id; ownership diputuskan handler
	// (DealsListFilter.Allows) atas baris.
	GetDeal(ctx context.Context, id int64) (Deal, error)
	// Jalur PUBLIK (/invite/{token}) — penerima belum tentu login/anggota. Validasi
	// kedaluwarsa & sudah-dipakai dilakukan di handler agar pesannya spesifik.
	GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error)
	// Satu lead hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
	// ter-soft-delete. Ownership diputuskan handler (LeadsListFilter.Allows) atas baris.
	GetLead(ctx context.Context, id int64) (Lead, error)
	// Validasi keanggotaan — dipakai middleware Scope SEBELUM membuka tx ber-tenant
	// (memastikan tenant aktif di session memang milik user; anti tenant-forcing).
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	// Workspace PRIMER = rumah aplikasi. Dicari lewat kolom is_primary, BUKAN lewat
	// perbandingan slug: yang bergantung padanya adalah penolakan arsip/hapus, dan
	// aturan sepenting itu tak boleh bergantung pada string yang kebetulan cocok.
	GetPrimaryTenant(ctx context.Context) (Tenant, error)
	// Baca satu pengaturan platform. Tak ditemukan = keadaan SAH (pemanggil jatuh ke
	// default bawaan kode), bukan error yang perlu diributkan.
	GetSetting(ctx context.Context, key string) (PlatformSetting, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	// SENGAJA tanpa filter deleted_at: middleware Scope perlu MEMBEDAKAN "workspace
	// tak pernah ada" dari "workspace terhapus" (0005) — keduanya berujung 404 bagi
	// user, tapi jalur restore/purge platform butuh barisnya tetap terbaca.
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id int64) (User, error)
	// Soft-delete gotcha: user terhapus tak boleh login.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Tambah satu baris matriks (role,obj,act). Idempoten via UNIQUE. Dipakai seed
	// dan saat matriks disunting (handler menghitung selisih, sisipkan yang baru).
	InsertBusinessRolePermission(ctx context.Context, arg InsertBusinessRolePermissionParams) error
	// Cek apakah email = operator platform (staff). Dipakai RefreshIdentity untuk
	// menentukan bypass RLS (is_super) + role platform. super_admin TIDAK di sini
	// (env-only via SUPER_ADMIN_EMAILS).
	IsPlatformStaff(ctx context.Context, email string) (bool, error)
	// Daftar desa, keyset (created_at DESC, id DESC) + filter ownership F3.
	//
	// Ownership dikodekan sebagai tiga flag boolean (bukan fragmen SQL dinamis) supaya
	// query tetap sqlc murni & ter-scan typed. Keputusan cakupannya SATU sumber dengan
	// AccountsOwnershipClause: keduanya diturunkan dari AccountsScopeFor lewat
	// AccountsListFilter — diuji bersama agar tak bercabang.
	//   scope_all → lihat semua (Admin/Manager)
	//   is_sales  → hanya account_owner = uid
	//   is_csm    → assigned_csm = uid ATAU backup_csm = uid
	// Ketiganya false (Support/role kosong/liar) → OR selalu false → NOL baris
	// (fail-closed, bukan bocor). uid tetap dioper walau scope_all (diabaikan).
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	// Orang yang punya jejak pada rentang ini — isi dropdown "filter per-orang".
	//
	// Diturunkan dari DATA, bukan dari daftar user: memilih orang yang tak punya
	// jejak sama sekali selalu menghasilkan halaman kosong, dan pilihan yang pasti
	// kosong lebih buruk daripada pilihan yang tak ada. Ikut mengecil sendiri saat
	// rentangnya dipersempit.
	ListActivityActors(ctx context.Context, arg ListActivityActorsParams) ([]ListActivityActorsRow, error)
	// Jejak aktivitas untuk panel /dev/logs: SEMUA aksi, bukan hanya login/logout.
	//
	// Sebelum ini panel hanya menampilkan `action IN ('auth.login','auth.logout')`,
	// sementara 14 jenis aksi lain ikut tercatat dan tak pernah dilihat siapa pun —
	// biayanya sudah dibayar penuh (kolom, index, penulisan di 16 tempat), hanya
	// jalur bacanya yang berhenti di satu filter.
	//
	// NAMA di-JOIN saat DIBACA, tak pernah disalin ke metadata: kolom itu sengaja
	// bebas PII, dan nama yang disalin ke sana jadi salinan permanen yang tak ikut
	// terhapus bersama usernya. LEFT JOIN, sebab jejak wajib tetap terbaca setelah
	// pelaku/sasarannya hilang — actor_user_id ON DELETE SET NULL, dan target_id
	// sengaja BUKAN FK.
	//
	// Sasaran dicari dari DUA tabel sesuai target_type, dan syarat itu WAJIB ada di
	// klausa JOIN-nya: tanpa `target_type = '...'`, id workspace akan mencocoki
	// baris users yang id-nya kebetulan sama, lalu memampangkan nama orang yang tak
	// terlibat. Salah, dan terlihat meyakinkan.
	//
	// Filter opsional lewat sqlc.narg (NULL = tanpa filter) supaya satu query
	// melayani semua kombinasi — dua query terpisah akan berbeda diam-diam begitu
	// salah satunya diubah.
	ListActivityTrail(ctx context.Context, arg ListActivityTrailParams) ([]ListActivityTrailRow, error)
	// Query sumbu RBAC bisnis (F2/F3) yang bisa diedit per-workspace. Dua tabel:
	// business_roles (definisi peran + data_scope) & business_role_permissions
	// (matriks obj/act). Enforcer Casbin di-load dari permissions; data_scope dibaca
	// per-request untuk filter kepemilikan desa (F3).
	// STARTUP: seluruh izin SEMUA tenant, untuk membangun enforcer bisnis global
	// (subject di-fold jadi `t<tenant_id>:<role>` di Go). WAJIB dipanggil di dalam
	// WithSuper — di tenant-tx, RLS menyembunyikan tenant lain → enforcer deny-all
	// senyap untuk mereka.
	ListAllBusinessRolePermissions(ctx context.Context) ([]ListAllBusinessRolePermissionsRow, error)
	ListAuditLogs(ctx context.Context, pageSize int32) ([]AuditLog, error)
	// Izin SATU workspace — dipakai reload per-tenant setelah matriks diubah, dan
	// untuk merender editor. Urut agar diff/tampilan stabil.
	ListBusinessRolePermissionsByTenant(ctx context.Context, tenantID int64) ([]ListBusinessRolePermissionsByTenantRow, error)
	// Daftar peran satu workspace (panel /roles + assign ke member). is_system dulu
	// agar admin (peran terkunci) tampil di atas. member_count = jumlah anggota yang
	// memegang peran ini (kolom "Jumlah User" di wireframe 9.2) — LEFT JOIN agar peran
	// tanpa pemegang tetap muncul dengan 0. COALESCE ke bigint: sqlc emit int64, bukan
	// interface{}. GROUP BY br.id (PK) sah — kolom br.* bergantung fungsional padanya.
	ListBusinessRoles(ctx context.Context, tenantID int64) ([]ListBusinessRolesRow, error)
	// Semua format kode workspace, untuk halaman pengaturan. Sedikit barisnya (satu
	// per entitas), jadi tak dipaginasi. Urut per entity agar tampilannya stabil.
	ListCodeFormats(ctx context.Context, tenantID int64) ([]CodeFormat, error)
	// Daftar kontak LINTAS-desa, keyset + filter kepemilikan DESA INDUK (bukan filter
	// kontak sendiri). JOIN accounts membawa kolom ownership desa; flag scope_all/
	// is_sales/is_csm identik dengan ListAccounts (AccountsListFilter) — "kontak siapa
	// yang tampil" diturunkan dari "desa siapa yang tampil", satu kebenaran.
	// Ketiganya false (Support/role kosong/liar) → NOL baris (fail-closed).
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	// Kontak SATU desa, keyset (created_at DESC, id DESC). TANPA filter ownership:
	// gerbangnya adalah desa induk (handler memvalidasi via loadOwnedAccount sebelum
	// memanggil ini). Kontak utama diangkat ke atas agar penanda primary langsung
	// terlihat tanpa menggeser urutan kronologis baris lainnya.
	ListContactsByAccount(ctx context.Context, arg ListContactsByAccountParams) ([]Contact, error)
	// Daftar deal (tampilan Tabel), keyset (created_at DESC, id DESC) + filter
	// ownership F3 + filter stage opsional. Dua flag ownership (sumber SATU dengan
	// DealsListFilter): scope_all → semua; is_own → deal_owner = uid; keduanya false
	// → NOL baris (fail-closed). stage_filter '' → semua stage.
	ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error)
	// Papan Kanban: seluruh deal hidup dalam cakupan ownership, diurutkan agar kartu
	// rapi per-stage lalu terbaru dulu. Di-bucket per-stage di handler (bukan N query
	// per kolom). LIMIT membatasi papan agar tak memuat seluruh tabel (guardrail
	// pagination); deal di luar batas tetap terlihat lewat tampilan Tabel berkeyset.
	ListDealsForPipeline(ctx context.Context, arg ListDealsForPipelineParams) ([]Deal, error)
	// Kandidat purge permanen: terhapus melewati masa tenggang. Dipanggil perintah
	// terjadwal, TAK PERNAH di jalur request (purge = kerja berat & tak reversibel).
	ListExpiredTenants(ctx context.Context, deletedAt pgtype.Timestamptz) ([]Tenant, error)
	// Undangan PENDING satu workspace (panel anggota) — yang sudah diterima disaring.
	ListInvitesByTenant(ctx context.Context, tenantID int64) ([]Invite, error)
	// Daftar lead, keyset (created_at DESC, id DESC) + filter ownership F3 + tab.
	//
	// Ownership sebagai dua flag boolean (bukan SQL dinamis) supaya query tetap sqlc
	// murni & ter-scan typed — sumber SATU dengan LeadsListFilter (ownership.go):
	//   scope_all → lihat semua (Admin/Manager)
	//   is_own    → hanya lead_owner = uid (Sales)
	// Keduanya false (Support/role kosong/liar) → NOL baris (fail-closed).
	//
	// Tab tambahan (ortogonal dari ownership):
	//   mine_only  → paksa lead_owner = uid (tab "My Leads", walau aktor scope_all)
	//   status_filter '' → semua status; selain itu = filter satu status ("Unqualified")
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error)
	// Daftar anggota SATU workspace (panel /admin/members). JOIN users untuk data
	// tampilan — users kini tabel global (tanpa RLS), jadi filter tenant di sini.
	//
	// `u.name` ikut diambil dan MENDAHULUI email sebagai penanda orang di layar.
	// Emailnya tetap dibawa karena pengelola membutuhkannya (mengundang,
	// mencocokkan orang) — yang menahannya dari mata lain adalah handler, yang
	// menyamarkannya sebelum data menyentuh view.
	ListMembersByTenant(ctx context.Context, tenantID int64) ([]ListMembersByTenantRow, error)
	// Daftar workspace milik user (untuk switcher sidebar). Urut terlama dulu agar
	// workspace pertama (dari register) jadi default stabil.
	//
	// Workspace TERHAPUS disembunyikan (0005): ia juga jadi sumber pilihan fallback
	// middleware Scope, jadi tanpa filter ini user bisa dilempar ke workspace yang
	// sudah dihapus. status ikut dikembalikan agar switcher bisa menandai yang
	// suspended/archived alih-alih membiarkan user menabrak 403 setelah mengklik.
	// is_primary ikut dikembalikan karena sidebar menghitung sisa kuota dari daftar
	// ini; tanpanya hitungannya akan BERBEDA dari CountOwnedWorkspaces, dan user
	// melihat tombol "Buat workspace" yang lalu ditolak (atau sebaliknya).
	ListMembershipsByUser(ctx context.Context, userID int64) ([]ListMembershipsByUserRow, error)
	// Membership BANYAK user sekaligus (panel /dev: tampilkan workspace+role tiap
	// user). Satu query untuk semua id → hindari N+1 (Rule 13).
	ListMembershipsForUsers(ctx context.Context, userIds []int64) ([]ListMembershipsForUsersRow, error)
	// Keyset pagination (pola ListUsers) — cast ::timestamptz/::bigint WAJIB, tanpa
	// itu sqlc salah infer tipe cursor_id pada row-value comparison.
	//
	// `user_id = $1` BUKAN sekadar filter tampilan: notifications sengaja TANPA RLS
	// (lihat 00009), jadi klausa ini adalah SATU-SATUNYA penjaga isolasi antar-user.
	// Jangan pernah menghapusnya "karena sudah difilter di Go".
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListOAuthAccountsByUser(ctx context.Context, userID int64) ([]OauthAccount, error)
	// Undangan yang ditujukan ke SATU ORANG (halaman notifikasi). Dicari per-email,
	// bukan user_id: saat diundang penerima belum tentu punya akun.
	//
	// lower(email) = $1 — pemanggil WAJIB mengirim email yang sudah di-lowercase
	// (pola auth.go/invite.go). Ditopang index partial idx_invites_email.
	ListPendingInvitesByEmail(ctx context.Context, email string) ([]ListPendingInvitesByEmailRow, error)
	ListPlatformStaff(ctx context.Context) ([]PlatformStaff, error)
	// Semua pengaturan sekaligus — dipakai halaman /dev/settings dan pemuatan cache
	// saat boot. Jumlahnya sedikit, jadi tak dipaginasi (beda dari daftar user).
	ListSettings(ctx context.Context) ([]PlatformSetting, error)
	// Daftar workspace untuk panel /dev (lintas-workspace — route platform). Termasuk
	// yang suspended/archived: justru itu yang perlu dilihat operator. Yang TERHAPUS
	// ikut tampil agar restore masih mungkin selama masa tenggang.
	ListTenantsForPlatform(ctx context.Context, arg ListTenantsForPlatformParams) ([]ListTenantsForPlatformRow, error)
	// Panel /dev: keyset pagination, hanya user aktif (belum soft-delete).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Tautkan hasil konversi ke lead + kunci statusnya. Dipanggil DALAM tx konversi
	// (bersama INSERT account/contact/deal) → gagal-sebagian rollback penuh. Guard
	// "hanya Qualified & belum converted" ada di WHERE agar konversi ganda idempotent-
	// aman: baris yang sudah converted tak ter-update lagi.
	MarkLeadConverted(ctx context.Context, arg MarkLeadConvertedParams) error
	// Auto-read saat halaman dibuka. Undangan TIDAK tersentuh di sini — memang tak
	// disimpan di tabel ini (sumber kebenarannya tetap `invites`), sehingga undangan
	// pending tetap terhitung di badge sampai benar-benar ditindak.
	MarkNotificationsRead(ctx context.Context, userID int64) error
	// Alokasi nomor urut BERIKUTNYA untuk (tenant, entity), ATOMIK.
	//
	// Kenapa satu pernyataan INSERT..ON CONFLICT dan bukan SELECT max+1 di Go: ON
	// CONFLICT DO UPDATE mengambil ROW LOCK pada baris counter, jadi dua create
	// bersamaan diserialkan oleh Postgres — mustahil dapat nomor sama. Menghitung di
	// aplikasi (baca lalu tulis) justru race yang paling sering lolos sampai dua
	// baris bertabrakan di produksi.
	//
	// next_val = "nomor yang akan DIPAKAI berikutnya" (mulai 1). Kita menyimpan hasil
	// SESUDAH dinaikkan lalu pemanggil mengurangi 1 (lihat GenerateEntityCode):
	//   • baris belum ada → INSERT next_val=2, RETURNING 2 → alokasi 2-1=1
	//   • baris next_val=N → UPDATE jadi N+1, RETURNING N+1 → alokasi (N+1)-1=N
	// RETURNING kolom mentah (BIGINT NOT NULL) supaya sqlc mengetiknya int64, bukan
	// pointer nullable (ekspresi aritmetika di RETURNING akan ditebak nullable).
	NextEntityCodeSeq(ctx context.Context, arg NextEntityCodeSeqParams) (int64, error)
	// Tren per HARI-LOKAL untuk rentang mingguan/bulanan (line chart).
	PresenceByDay(ctx context.Context, arg PresenceByDayParams) ([]PresenceByDayRow, error)
	// Distribusi aktivitas per JAM-LOKAL untuk satu rentang (bar "aktivitas per jam").
	// AT TIME ZONE mengonversi bucket UTC ke jam lokal. Handler mengisi jam kosong
	// jadi 0 (sumbu X ECharts butuh 0..23 lengkap). COALESCE+cast: SUM/COUNT nullable
	// → paksa int64 (bukan pgtype.Numeric).
	PresenceByHour(ctx context.Context, arg PresenceByHourParams) ([]PresenceByHourRow, error)
	// KPI ringkas untuk stat cards pada rentang aktif.
	PresenceKPIs(ctx context.Context, arg PresenceKPIsParams) (PresenceKPIsRow, error)
	// "User aktif jam berapa s/d jam berapa" untuk rentang: first/last seen per user +
	// total hit. JOIN users untuk email TAMPILAN panel (dev-only UI, bukan log — tabel
	// activity_presence sendiri hanya simpan user_id). first/last dikembalikan sebagai
	// timestamptz UTC; handler memformatnya ke jam lokal (appTZ) — lebih bersih dari
	// AT TIME ZONE di SQL (yang bikin sqlc emit interface{}).
	PresenceUserSpans(ctx context.Context, arg PresenceUserSpansParams) ([]PresenceUserSpansRow, error)
	// Retensi: buang jejak yang lebih tua dari batas. Dipanggil pemeliharaan
	// terjadwal, TAK PERNAH di jalur request.
	//
	// Tabel ini append-only dan dulu tumbuh selamanya. Selama tak pernah dibaca itu
	// cuma soal disk; begitu ia jadi halaman yang aktif dibuka, biayanya ikut ke
	// setiap query. Yang dibayar: peristiwa lebih lama dari batas TAK BISA
	// diselidiki lagi — karena itu batasnya hidup di platform_settings (bisa
	// dinaikkan operator sebelum sesuatu telanjur hilang), bukan dipaku di kode.
	//
	// Mengembalikan JUMLAH baris terhapus supaya pemeliharaan bisa mencatat apa yang
	// sebenarnya terjadi: pekerjaan pembersihan yang diam tak bisa dibedakan dari
	// pekerjaan yang tak pernah jalan.
	PurgeAuditLogsBefore(ctx context.Context, before pgtype.Timestamptz) (int64, error)
	// Hapus PERMANEN. memberships/invites/notifications ikut CASCADE (data
	// operasional); audit_logs TIDAK — FK-nya ON DELETE SET NULL sejak migrasi 00010,
	// sebab bukti tak boleh lenyap bersama yang dibuktikan (0005 §6).
	PurgeTenant(ctx context.Context, id int64) error
	// Presence bucket 15-menit. bucket_at di-floor SERVER-SIDE ke kelipatan 900 dtk
	// (jangan hitung di Go — hindari drift clock). Agregasi di level baris: request
	// berulang dalam bucket sama hanya menaikkan hits, bukan insert baris baru.
	RecordPresence(ctx context.Context, arg RecordPresenceParams) error
	RemovePlatformStaff(ctx context.Context, email string) error
	// Batalkan penghapusan dalam masa tenggang. Status dikembalikan ke 'active':
	// workspace yang dihapus saat ter-arsip pun kembali sebagai aktif — pemulihan
	// harus meninggalkan keadaan yang bisa langsung dipakai, bukan setengah jalan.
	RestoreTenant(ctx context.Context, id int64) error
	// Angkat SATU kontak jadi utama. Pemanggil WAJIB memanggil ClearAccountPrimaryContact
	// lebih dulu (satu tx) — index memblokir dua utama. account_id ikut di WHERE sebagai
	// sabuk pengaman: kontak yang bukan milik desa itu tak bisa diangkat lewat jalurnya.
	SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
	// entitas lain — deal/tiket — tak putus). Idempotent: hanya baris hidup.
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
	// entitas lain tak putus). Idempotent: hanya baris hidup. Kontak utama yang dihapus
	// membebaskan slot primary (index-nya partial WHERE deleted_at IS NULL).
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
	// leads.converted_deal_id tak putus). Idempotent: hanya baris hidup.
	SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK
	// converted_* tak putus). Idempotent: hanya baris hidup.
	SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error
	// Owner ATAU platform. Masa tenggang: baris tetap ada, slug TIDAK dilepas.
	//
	// `NOT is_primary`: rumah aplikasi tak bisa dihapus dari dalam aplikasi itu
	// sendiri. Di mode single ia satu-satunya workspace — menghapusnya berarti
	// menghapus aplikasinya, lewat tombol yang di workspace lain berarti "hapus
	// salah satu dari beberapa".
	SoftDeleteTenant(ctx context.Context, id int64) error
	SoftDeleteUser(ctx context.Context, id int64) error
	// PLATFORM-ONLY (super_admin/staff). Owner tak bisa membatalkannya sendiri —
	// kalau bisa, gunanya hilang (0005 §1). Alasan disimpan agar pertanyaan support
	// pertama ("kenapa workspace saya mati") terjawab tanpa menggali audit log.
	SuspendTenant(ctx context.Context, arg SuspendTenantParams) error
	// Cek ketersediaan slug (untuk auto-suffix unik: acme -> acme-2 -> ...). Ikut
	// menghitung workspace TERHAPUS: slug tak dilepas selama masa tenggang, kalau
	// dilepas orang lain bisa mengambilnya & restore jadi mustahil (0005 §5).
	TenantSlugExists(ctx context.Context, slug string) (bool, error)
	// OWNER. Hanya dari 'archived' — tak bisa dipakai membatalkan suspensi platform.
	UnarchiveTenant(ctx context.Context, id int64) error
	// Cabut satu business_role dari SEMUA anggota workspace yang memegangnya —
	// dipanggil SEBELUM menghapus perannya, agar penghapusan peran meng-unassign
	// orang alih-alih (lewat FK) menghapus keanggotaannya. Idempoten.
	UnassignBusinessRole(ctx context.Context, arg UnassignBusinessRoleParams) error
	// PLATFORM-ONLY. Membersihkan jejak suspensi agar kolomnya tak jadi sisa yang
	// menyesatkan saat suspensi berikutnya.
	UnsuspendTenant(ctx context.Context, id int64) error
	// Sunting profil desa. entity_code & village_code tak diubah di sini (kode identitas
	// yang dikutip; village_code punya jalur khusus bila kelak perlu). Penugasan
	// (owner/CSM) juga TERPISAH (AssignAccountCSM) agar perubahan wewenang terlihat
	// sebagai aksi tersendiri, bukan efek samping edit profil.
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	// Sunting label, deskripsi & cakupan peran. name (subject Casbin) TAK diubah di
	// sini — mengganti nama peran memutus assign yang sudah ada; kalau perlu, buat
	// peran baru. is_system tak bisa disunting (dijaga di handler, bukan di query).
	UpdateBusinessRole(ctx context.Context, arg UpdateBusinessRoleParams) error
	// Sunting kontak. is_primary_contact di-set pemanggil setelah mengosongkan primary
	// lama (ClearAccountPrimaryContact) bila dinaikkan jadi utama. account_id TIDAK
	// diubah di sini — memindahkan kontak antar-desa adalah aksi lain (belum ada).
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	// Sunting profil deal. entity_code, stage, dan hasil (win_loss_reason/closed_date)
	// TAK di sini: stage punya jalur khusus (UpdateDealStage) agar perpindahan pipeline
	// terlihat sebagai aksi tersendiri, bukan efek samping edit.
	UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error)
	// Pindah stage pipeline (aksi tersendiri). closed_date/win_loss_reason/loss_notes
	// diisi saat Closed Won/Lost — validasi "Closed Lost wajib win_loss_reason" di
	// handler (bukan constraint DB agar pesan bisa diperbaiki user). closed_date =
	// CURRENT_DATE bila stage terminal, NULL bila dibuka kembali ke stage aktif.
	UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) error
	// Sunting profil & kualifikasi lead. entity_code tak diubah (kode identitas yang
	// dikutip). converted_* TAK disentuh di sini — itu efek konversi (ConvertLead),
	// bukan edit biasa.
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
	// Set/ganti business_role (sumbu CRM F2) satu anggota. Nilai divalidasi tenant-
	// aware di handler (ada di business_roles workspace ini) SEBELUM query — kolom
	// tak lagi punya CHECK sejak 00007. NULL = cabut peran CRM (mis. saat perannya
	// dihapus) — pgtype/pointer NULL diteruskan apa adanya.
	UpdateMemberBusinessRole(ctx context.Context, arg UpdateMemberBusinessRoleParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	// Ganti NAMA tampilan workspace (owner-only, di-guard di handler). Slug SENGAJA
	// tak diubah — immutable setelah dibuat (stabilitas URL; ganti display != ganti URL).
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	// Profil dari provider (avatar + nama tampilan) di-refresh TIAP LOGIN: keduanya
	// berubah di sisi Google tanpa memberi tahu kita, dan login adalah satu-satunya
	// saat kita mendengar kabar terbaru.
	//
	// COALESCE, bukan penimpaan lugas: argumen NULL berarti "provider tak
	// mengirimkan apa pun kali ini", BUKAN "hapus yang tersimpan". Tanpa ini, satu
	// respons Google tanpa `picture` (boleh terjadi walau scope diminta) akan
	// menghapus avatar yang sudah benar. Nilai lama lebih baik daripada tak ada.
	//
	// Konsekuensi yang disengaja: user yang MENGHAPUS fotonya di Google tetap
	// memakai foto lamanya di sini. Ditukar sadar dengan menghindari penghapusan
	// palsu, yang jauh lebih sering terjadi.
	//
	// CATATAN untuk kelak: begitu ada fitur "edit profil" di aplikasi ini, refresh
	// otomatis ini akan MENIMPA nama yang disunting user tiap kali ia login. Saat
	// itu tiba, nama pilihan sendiri harus jadi kolom terpisah yang diutamakan —
	// jangan sekadar mematikan refresh, sebab avatar tetap perlu ikut berubah.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// Kuota workspace per user. NULL = IKUT DEFAULT GLOBAL (platform_settings), angka
	// = hak khusus milik user itu yang kebal perubahan global. Membedakan keduanya
	// adalah alasan kolom ini nullable — dgn NOT NULL, "kebetulan 3" tak bisa
	// dibedakan dari "sengaja diberi 3".
	UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	// Simpan/ubah format satu entitas. UPSERT: baris mungkin belum ada (default masih
	// dipakai) — operator hanya menyentuh baris saat ingin MENGUBAH default. created_by
	// diisi saat pertama dibuat; updated_by/updated_at tiap kali diubah.
	UpsertCodeFormat(ctx context.Context, arg UpsertCodeFormatParams) error
	// Simpan pengaturan. UPSERT karena baris mungkin belum ada (deployment baru yang
	// tak menjalankan seed): pemanggil tak perlu tahu bedanya.
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
