// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Tandai terpakai (one-time). Guard accepted_at IS NULL → race dua klik tak
	// menghasilkan dua membership (UNIQUE di memberships jadi jaring kedua).
	AcceptInvite(ctx context.Context, token string) error
	AddPlatformStaff(ctx context.Context, email string) (PlatformStaff, error)
	// ── quote_items — baris penawaran (hard-delete, tanpa soft-delete/audit) ──────
	// Tambah baris item. tenant_id eksplisit (RLS WITH CHECK). unit_price & subtotal =
	// SNAPSHOT: unit_price disalin dari plans.base_price saat dibuat, subtotal dihitung
	// app (unit_price * quantity * (1 - discount_pct/100)); keduanya beku sesudahnya.
	AddQuoteItem(ctx context.Context, arg AddQuoteItemParams) (QuoteItem, error)
	// Setujui renewal Upsell yang menunggu (M5-3c): baris 'PendingApproval' → 'Active'.
	// Handler WAJIB meng-Expired baris lama (previous_subscription_id) SEBELUM query ini
	// dalam tx yang sama — invarian idx_subs_one_active (1 Active per account+plan).
	// Filter status='PendingApproval' = penjaga transisi: baris yang sudah diputus tak
	// bisa disetujui dua kali (0 baris ter-update → handler kabari "tak lagi pending").
	ApproveRenewal(ctx context.Context, arg ApproveRenewalParams) (Subscription, error)
	// OWNER. Workspace jadi READ-ONLY tapi datanya utuh. Guard `status = 'active'`
	// mencegah archive menimpa SUSPENSI platform — kalau tidak, owner bisa keluar
	// dari suspensi lewat pintu samping (archive lalu unarchive).
	//
	// `NOT is_primary`: mengarsipkan rumah aplikasi menjadikan SELURUH aplikasi
	// read-only lewat tombol yang tampak rutin. Guard-nya di SQL, bukan cuma di
	// handler — jalur yang tak lewat handler pun harus tertahan.
	ArchiveTenant(ctx context.Context, id int64) error
	// Penugasan CSM (binaan + cadangan) — jalur terpisah dari edit profil (§8.1).
	// NULL = lepas penugasan. updated_by/at ikut agar jejaknya jelas.
	AssignAccountCSM(ctx context.Context, arg AssignAccountCSMParams) error
	// Churn (5.4): satu aksi bisnis — set status (Cancelled/Churned) + seluruh kolom
	// churn sekaligus. Domain churn_reason/churn_type dijaga subs_churn_*_chk.
	ChurnSubscription(ctx context.Context, arg ChurnSubscriptionParams) error
	// Lepas penanda utama dari SEMUA kontak hidup satu desa. Dipanggil SEBELUM
	// memasang primary baru (create/update/set-primary) supaya idx_contacts_primary
	// (maks 1 utama per desa) tak pernah dilanggar. Idempotent: nol baris bila belum
	// ada utama.
	ClearAccountPrimaryContact(ctx context.Context, arg ClearAccountPrimaryContactParams) error
	// Jumlah peristiwa per KELUARGA aksi pada rentang ini (auth, workspace, member,
	// user, invite, settings, platform) — dipakai untuk melabeli opsi filter dengan
	// angka, sehingga operator tahu mana yang berisi sebelum mengkliknya.
	//
	// split_part di segmen pertama: penamaan aksi kita selalu `keluarga.sisanya`
	// (auth.login, workspace.create, member.role.update), jadi keluarga bisa
	// diturunkan tanpa tabel pemetaan yang harus dijaga selaras.
	CountActivityByAction(ctx context.Context, arg CountActivityByActionParams) ([]CountActivityByActionRow, error)
	// Jumlah kontak hidup satu desa — untuk badge/ringkasan di detail desa. Murah:
	// idx_contacts_account (partial WHERE deleted_at IS NULL) melayaninya langsung.
	CountContactsByAccount(ctx context.Context, accountID int64) (int64, error)
	// Berapa workspace yang DIMILIKI user (role owner) — untuk cek kuota sebelum
	// membuat workspace baru. Diundang jadi member/admin TIDAK memakan kuota.
	//
	// Workspace TERHAPUS tak dihitung (0005 §7): kuota yang masih tertahan oleh
	// workspace yang sudah dihapus terasa seperti bug, dan mendorong user memurge
	// lebih cepat — kebalikan dari tujuan masa tenggang. Yang TERARSIP TETAP
	// dihitung: datanya masih disimpan & bisa diaktifkan kapan saja.
	//
	// Workspace PRIMER juga tak dihitung (0007): kuota membatasi berapa banyak yang
	// boleh DIBUAT, dan rumah aplikasi tak dibuat siapa pun — ia sudah ada sebelum
	// user pertama mendaftar. Tanpa pengecualian ini, super_admin yang jadi ownernya
	// memakai jatahnya sendiri, dan dengan default 1 orang yang MENETAPKAN aturan
	// kuota justru tak bisa membuat workspace apa pun.
	CountOwnedWorkspaces(ctx context.Context, userID int64) (int64, error)
	// Bagian "perlu tindakan" dari badge. Undangan pending SENGAJA tak pernah
	// ter-auto-read: ia tugas, bukan kabar — lihat MarkNotificationsRead.
	CountPendingInvitesByEmail(ctx context.Context, email string) (int64, error)
	// Berapa user memegang HAK KHUSUS (kuota di-override, bukan mengikuti global).
	// Dipakai halaman pengaturan untuk menyatakan dampak sebelum operator menyimpan:
	// mereka SENGAJA tak ikut berubah, dan tanpa angka ini operator mengira
	// pengaturannya tak bekerja.
	CountQuotaOverrides(ctx context.Context) (int64, error)
	// Jumlah owner di satu workspace — cegah menghapus/menurunkan owner terakhir
	// (workspace tanpa owner = yatim).
	CountTenantOwners(ctx context.Context, tenantID int64) (int64, error)
	CountTenantsForPlatform(ctx context.Context) (int64, error)
	// Badge sidebar — dirender di SETIAP halaman, ditopang index partial
	// idx_notif_unread agar tak menyentuh baris yang sudah terbaca.
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	// accounts.sql — hub Desa (Account). Isolasi WORKSPACE ditegakkan RLS (GUC
	// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
	// lewat flag ownership di ListAccounts — lihat internal/db/ownership.go.
	//
	// entity_code (DESA-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
	// dioper ke CreateAccount; village_code (Kode Kemendagri) datang dari user & boleh
	// kosong. Dua kode berbeda asal, keduanya disimpan di baris.
	// Buat desa. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// entity_code sudah dirakit pemanggil (GenerateEntityCode) — INSERT-nya dijaga
	// unik oleh idx_accounts_entity_code bila format diubah bertabrakan.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// activities.sql — aktivitas polimorfik (task/call/note …). Isolasi WORKSPACE
	// ditegakkan RLS (GUC app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3)
	// ditegakkan di layer query lewat flag ownership di ListActivities — lihat
	// ownership.go (ActivitiesListFilter, sumbu tunggal owner_id).
	//
	// Nama query JAMAK (Activities) — sengaja beda dari activity.sql (presence,
	// 00001) agar tak bentrok di querier generated. Tabel TAK punya entity_code
	// (spec §7a) → tak ada alokasi kode di create.
	//
	// activity_context di-set handler ('sales' untuk 4.4); target_id BUKAN FK
	// (integritas target diverifikasi handler via loadOwned* sebelum insert).
	// Buat aktivitas. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya =
	// GUC). Kolom per-kind opsional (narg) — hanya yang relevan untuk kind terisi.
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	// Jejak aksi admin. metadata TANPA PII (id saja, bukan email/nama).
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Buat peran baru (atau seed default). name = subject Casbin & nilai
	// memberships.business_role; display_name = label layar; description = keterangan
	// satu baris (kolom Deskripsi wireframe 9.2, boleh ''). is_system hanya true untuk
	// seed admin. created_by NULL untuk seed migrasi/boot.
	CreateBusinessRole(ctx context.Context, arg CreateBusinessRoleParams) (CreateBusinessRoleRow, error)
	// contacts.sql — orang di dalam sebuah desa (Contact), 1:N ke accounts. Isolasi
	// WORKSPACE ditegakkan RLS (GUC app.tenant_id di WithTenant, tenant_id di-AND-kan
	// otomatis). Isolasi ANTAR-DESA (F3) TIDAK punya filter sendiri di sini: kontak
	// MEWARISI kepemilikan desa induknya (docs/crm/tasks.md §Modul 3). Maka:
	//   - daftar per-desa (ListContactsByAccount) tak menyaring ownership sama sekali —
	//     handler sudah menjaga bahwa desa induknya boleh dilihat aktor (loadOwnedAccount);
	//     begitu lolos, SEMUA kontak desa itu tampil.
	//   - daftar global (ListContacts) menyaring lewat kolom ownership DESA INDUK
	//     (JOIN accounts), memakai flag yang SAMA dengan ListAccounts — sumber tunggal
	//     AccountsListFilter. "Kontak siapa yang tampil" = "desa siapa yang tampil".
	//
	// Maks 1 kontak utama per desa dijaga idx_contacts_primary (partial UNIQUE). Set-
	// primary WAJIB dua langkah dalam satu tx: kosongkan primary lama dulu, baru pasang
	// yang baru — kalau tidak, INSERT/UPDATE bertabrakan dengan index (satu tx, satu
	// tenant, jadi tak ada balapan antar-request di jalur ini).
	// Buat kontak. account_id mengikat ke desa induk (RLS memverifikasi tenant_id =
	// GUC lewat FK + WITH CHECK). is_primary_contact di-set pemanggil SETELAH
	// mengosongkan primary lama (ClearAccountPrimaryContact) agar tak melanggar index.
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	// deals.sql — pipeline Sales (Deal). Isolasi WORKSPACE ditegakkan RLS (GUC
	// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
	// lewat flag ownership di ListDeals/ListDealsForPipeline — lihat ownership.go.
	// Ownership deal memakai SATU kolom (deal_owner).
	//
	// entity_code (DEAL-001) dialokasikan di GenerateEntityCode DALAM tx create.
	// account_id NN: deal selalu menempel ke satu desa. Deal hasil konversi lead dibuat
	// di tx konversi (bersama account+contact) — lihat handler.
	// Buat deal. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error)
	// Undangan bergabung ke workspace. token = rahasia URL (crypto/rand hex via
	// oauth.NewState). email boleh milik orang yang BELUM punya akun.
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// leads.sql — funnel Sales (Lead). Isolasi WORKSPACE ditegakkan RLS (GUC
	// app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3) ditegakkan di layer query
	// lewat flag ownership di ListLeads — lihat internal/db/ownership.go. Ownership
	// lead memakai SATU kolom (lead_owner), beda dari accounts yang tiga kolom.
	//
	// entity_code (LEAD-001) dialokasikan di GenerateEntityCode DALAM tx create, lalu
	// dioper ke CreateLead. Field region/kontak mentah (province/mobile_phone/dst)
	// karena lead belum jadi account — konversi yang memindahkannya.
	// Buat lead. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// entity_code sudah dirakit pemanggil (GenerateEntityCode).
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	// Jadikan user anggota workspace dgn role tertentu. Dipakai: register/OAuth (owner
	// workspace pertama), buat workspace baru (owner), terima invite (admin/member).
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	// Dipanggil saat peristiwa keanggotaan terjadi (role diubah, dikeluarkan).
	// payload = snapshot detail siap-render; lihat migrasi 00009.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	// User baru dari OAuth: tanpa password, email terverifikasi provider, + avatar
	// & nama tampilan. Keduanya nullable — provider boleh tak mengirimkannya.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	// Buat plan katalog. tenant_id eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// plan_code unik per tenant (idx_plans_code) → kode kembar ditolak DB. is_active
	// default true di skema tapi di-set eksplisit agar handler bisa membuat draft pensiun.
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	// Dipanggil SEKALI saat boot pertama. Unique partial index di tenants menjamin
	// hanya ada satu primer — dua instance yang boot bersamaan, satu akan gagal, dan
	// itu jauh lebih baik daripada dua "rumah aplikasi".
	CreatePrimaryTenant(ctx context.Context, arg CreatePrimaryTenantParams) (Tenant, error)
	// quotes.sql — penawaran (Quote) + baris (quote_item), Modul 4 Sales slice 2.
	// Isolasi WORKSPACE ditegakkan RLS (GUC app.tenant_id di WithTenant). Ownership
	// F3 TAK ditegakkan di sini: quote diakses NEST di bawah deal (/deals/{id}/quotes),
	// handler memuat deal ber-owner dulu (loadOwnedDeal) lalu quote-nya — tak ada kolom
	// quote_owner. grand_total/tax_amount = SNAPSHOT: dihitung ulang app dari quote_items
	// tiap item berubah (bukan agregat live saat baca).
	// entity_code (QUO-001) dialokasikan GenerateEntityCode DALAM tx create.
	// Buat quote. tenant_id di-set eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// deal_id nullable di skema tapi selalu terisi di alur nest; account_id NN = jangkar.
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	// subscriptions.sql — langganan (Subscription), Modul 5 slice 2. Isolasi WORKSPACE
	// ditegakkan RLS (GUC app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3)
	// ditegakkan di layer query lewat flag ownership di ListSubscriptions (kolom
	// subscription_owner) — pola sama dgn deals (lihat ownership.go).
	//
	// KEPUTUSAN inti (docs/crm/skema.md §5, migrasi 00012):
	//   • Renewal = INSERT baris BARU (CreateSubscription dgn previous_subscription_id
	//     + previous_value), BUKAN update. Handler WAJIB meng-Expired baris lama
	//     (UpdateSubscriptionStatus 'Expired') SEBELUM CreateSubscription baris aktif,
	//     dalam SATU tx — kalau tidak, idx_subs_one_active (1 Active per account+plan)
	//     menolak INSERT kedua. Urutan itu = invarian, ditegakkan test M5-5.
	//   • Create-from-deal = CreateSubscription (source_deal_id) lalu
	//     SetDealCreatedSubscription (deals.sql) dalam tx yang sama → tautan dua-arah.
	//   • Churn = ChurnSubscription (status Cancelled/Churned + kolom churn 5.4 sekali
	//     tulis; churn adalah SATU aksi bisnis, bukan edit profil).
	//   • ARR DISIMPAN (bukan MRR×12); field-level masking ARR utk non-manager = urusan
	//     handler/view (F4), bukan query.
	// entity_code (SUB-0001) dialokasikan GenerateEntityCode DALAM tx create.
	// Buat langganan. tenant_id eksplisit (RLS WITH CHECK memverifikasinya = GUC).
	// Dipakai DUA jalur: (a) create-from-deal (source_deal_id terisi, previous_* NULL);
	// (b) renewal (previous_subscription_id + previous_value terisi, source_deal_id
	// opsional). status default 'Trial' di skema tapi di-set eksplisit (renewal lahir
	// 'Active'). Kolom renewal-action (6.6) & churn (5.4) TIDAK di-set di sini — punya
	// jalur sendiri.
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// Buat tenant baru (dipanggil saat register/oauth user baru — 1 user = 1 tenant).
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// users = tabel GLOBAL (identitas murni, TANPA tenant/role — keduanya pindah ke
	// memberships). Keanggotaan dibuat terpisah via CreateMembership dalam tx sama.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// KPI ringkas pipeline dalam cakupan ownership (satu round-trip, bukan hitung di
	// Go atas seluruh baris). COALESCE(...)::bigint/::numeric membungkus agregat agar
	// sqlc tak meng-emit interface{} (gotcha #14). Win rate dihitung di Go dari
	// won_count/(won_count+lost_count) — pembagian nol ditangani di sana.
	DealPipelineStats(ctx context.Context, arg DealPipelineStatsParams) (DealPipelineStatsRow, error)
	// Tolak undangan (sisi PENERIMA). Kunci ganda token + email: penerima tak punya
	// scope ke workspace pengundang, jadi DeleteInvite (yang butuh tenant_id) tak
	// bisa dipakai. Mencocokkan email mencegah pemegang token menolak undangan
	// milik orang lain.
	DeclineInvite(ctx context.Context, arg DeclineInviteParams) error
	// Hapus peran. Perizinannya ikut (FK CASCADE); anggota yang memegangnya di-
	// unassign TERPISAH (UnassignBusinessRole) SEBELUM ini di handler — FK ke
	// memberships sengaja tak ada agar penghapusan peran bukan penghapusan orang.
	// Peran is_system ditolak di handler.
	DeleteBusinessRole(ctx context.Context, arg DeleteBusinessRoleParams) error
	// Kosongkan matriks satu peran sebelum menulis ulang (pola replace-all: handler
	// hapus semua lalu sisipkan set baru dalam satu tx — lebih sederhana & bebas
	// selisih daripada diff per-baris). CASCADE peran tak menyentuh ini; ini untuk
	// peran yang TETAP ada tapi izinnya diganti.
	DeleteBusinessRolePermissionsForRole(ctx context.Context, arg DeleteBusinessRolePermissionsForRoleParams) error
	// Batalkan undangan yang belum diterima (sisi PENGUNDANG, di panel anggota).
	DeleteInvite(ctx context.Context, arg DeleteInviteParams) error
	// Keluarkan anggota dari workspace (atau user keluar sendiri).
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	// Hard-delete satu baris item (tanpa soft-delete). Total quote direkalkulasi app
	// setelahnya via UpdateQuoteTotals.
	DeleteQuoteItem(ctx context.Context, id int64) error
	// Satu desa hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
	// ter-soft-delete. Tak menerapkan ownership — pemanggil (handler) yang memutuskan
	// apakah aktor boleh membuka baris ini (detail bisa dibuka lewat tautan langsung).
	GetAccount(ctx context.Context, id int64) (Account, error)
	// Satu aktivitas hidup. RLS menjamin tenant_id; ownership diputuskan handler
	// (ActivitiesListFilter.Allows) atas baris.
	GetActivity(ctx context.Context, id int64) (Activity, error)
	// Satu peran (edit/validasi). tenant_id di predikat = pertahanan berlapis di atas
	// RLS: nama peran datang dari URL, jadi cocokkan eksplisit ke workspace aktif.
	GetBusinessRole(ctx context.Context, arg GetBusinessRoleParams) (GetBusinessRoleRow, error)
	// Cakupan desa (F3) untuk satu business_role — dibaca per-request di
	// RefreshIdentity, disimpan di session. Dipisah dari GetBusinessRole agar jalur
	// panas ini tak menarik kolom yang tak dipakainya.
	GetBusinessRoleDataScope(ctx context.Context, arg GetBusinessRoleDataScopeParams) (string, error)
	// Format kode satu (tenant, entity). Tak ada baris = SAH: pemanggil jatuh ke
	// codes.DefaultFormat (workspace baru berkode tanpa seed). pgx.ErrNoRows bukan
	// kegagalan yang perlu diributkan.
	GetCodeFormat(ctx context.Context, arg GetCodeFormatParams) (CodeFormat, error)
	// Satu kontak hidup. RLS menjamin tenant_id; deleted_at menyembunyikan yang
	// ter-soft-delete. Tak menerapkan ownership — pemanggil (handler) memutuskan lewat
	// desa INDUK apakah aktor boleh membukanya (kontak mewarisi kepemilikan desa).
	GetContact(ctx context.Context, id int64) (Contact, error)
	// Satu deal hidup. RLS menjamin tenant_id; ownership diputuskan handler
	// (DealsListFilter.Allows) atas baris.
	GetDeal(ctx context.Context, id int64) (Deal, error)
	// Jalur PUBLIK (/invite/{token}) — penerima belum tentu login/anggota. Validasi
	// kedaluwarsa & sudah-dipakai dilakukan di handler agar pesannya spesifik.
	GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error)
	// Satu lead hidup. RLS menjamin tenant_id; filter deleted_at menyembunyikan yang
	// ter-soft-delete. Ownership diputuskan handler (LeadsListFilter.Allows) atas baris.
	GetLead(ctx context.Context, id int64) (Lead, error)
	// Validasi keanggotaan — dipakai middleware Scope SEBELUM membuka tx ber-tenant
	// (memastikan tenant aktif di session memang milik user; anti tenant-forcing).
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	// Satu plan (untuk baca base_price yang di-SNAPSHOT ke quote_items.unit_price saat
	// add item). RLS menjamin tenant_id. Tak filter is_active: handler memutuskan (add
	// item baru gate ke ListPlans; get by id juga menutup balapan pensiun-saat-submit).
	GetPlan(ctx context.Context, id int64) (Plan, error)
	// Workspace PRIMER = rumah aplikasi. Dicari lewat kolom is_primary, BUKAN lewat
	// perbandingan slug: yang bergantung padanya adalah penolakan arsip/hapus, dan
	// aturan sepenting itu tak boleh bergantung pada string yang kebetulan cocok.
	GetPrimaryTenant(ctx context.Context) (Tenant, error)
	// Satu quote hidup. RLS menjamin tenant_id; kelayakan akses (via deal ber-owner)
	// diputuskan handler sebelum memanggil ini.
	GetQuote(ctx context.Context, id int64) (Quote, error)
	// Baca satu pengaturan platform. Tak ditemukan = keadaan SAH (pemanggil jatuh ke
	// default bawaan kode), bukan error yang perlu diributkan.
	GetSetting(ctx context.Context, key string) (PlatformSetting, error)
	// Satu langganan hidup. RLS menjamin tenant_id; ownership (F3) diputuskan handler
	// atas baris (SubscriptionsListFilter.Allows), bukan di sini.
	GetSubscription(ctx context.Context, id int64) (Subscription, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	// SENGAJA tanpa filter deleted_at: middleware Scope perlu MEMBEDAKAN "workspace
	// tak pernah ada" dari "workspace terhapus" (0005) — keduanya berujung 404 bagi
	// user, tapi jalur restore/purge platform butuh barisnya tetap terbaca.
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUser(ctx context.Context, id int64) (User, error)
	// Soft-delete gotcha: user terhapus tak boleh login.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Tambah satu baris matriks (role,obj,act). Idempoten via UNIQUE. Dipakai seed
	// dan saat matriks disunting (handler menghitung selisih, sisipkan yang baru).
	InsertBusinessRolePermission(ctx context.Context, arg InsertBusinessRolePermissionParams) error
	// Cek apakah email = operator platform (staff). Dipakai RefreshIdentity untuk
	// menentukan bypass RLS (is_super) + role platform. super_admin TIDAK di sini
	// (env-only via SUPER_ADMIN_EMAILS).
	IsPlatformStaff(ctx context.Context, email string) (bool, error)
	// Daftar desa, keyset (created_at DESC, id DESC) + filter ownership F3.
	//
	// Ownership dikodekan sebagai tiga flag boolean (bukan fragmen SQL dinamis) supaya
	// query tetap sqlc murni & ter-scan typed. Keputusan cakupannya SATU sumber dengan
	// AccountsOwnershipClause: keduanya diturunkan dari AccountsScopeFor lewat
	// AccountsListFilter — diuji bersama agar tak bercabang.
	//   scope_all → lihat semua (Admin/Manager)
	//   is_sales  → hanya account_owner = uid
	//   is_csm    → assigned_csm = uid ATAU backup_csm = uid
	// Ketiganya false (Support/role kosong/liar) → OR selalu false → NOL baris
	// (fail-closed, bukan bocor). uid tetap dioper walau scope_all (diabaikan).
	//
	// unowned = tapis SEJAJAR (tab "Belum ada Owner"): saring account_owner IS NULL
	// DI ATAS blok ownership, bukan menggantinya. false → NOT false = TRUE → tak
	// membatasi; true → hanya desa tanpa pemilik. Inheren cakupan-all: pemakai
	// ber-scope 'own' tak pernah punya baris owner-kosong, jadi handler hanya
	// menyalakannya untuk peran ScopeAll (Manager/Admin).
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	// Daftar aktivitas (tampilan Tabel), keyset (created_at DESC, id DESC) + filter
	// ownership F3 + filter context. Dua flag ownership (sumber SATU dengan
	// ActivitiesListFilter): scope_all → semua; is_own → owner_id = uid; keduanya
	// false → NOL baris (fail-closed). context_filter menyaring view modul
	// ('sales' untuk 4.4) — pemisah dari CS 6.5 / general M7.
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error)
	// Orang yang punya jejak pada rentang ini — isi dropdown "filter per-orang".
	//
	// Diturunkan dari DATA, bukan dari daftar user: memilih orang yang tak punya
	// jejak sama sekali selalu menghasilkan halaman kosong, dan pilihan yang pasti
	// kosong lebih buruk daripada pilihan yang tak ada. Ikut mengecil sendiri saat
	// rentangnya dipersempit.
	ListActivityActors(ctx context.Context, arg ListActivityActorsParams) ([]ListActivityActorsRow, error)
	// Jejak aktivitas untuk panel /dev/logs: SEMUA aksi, bukan hanya login/logout.
	//
	// Sebelum ini panel hanya menampilkan `action IN ('auth.login','auth.logout')`,
	// sementara 14 jenis aksi lain ikut tercatat dan tak pernah dilihat siapa pun —
	// biayanya sudah dibayar penuh (kolom, index, penulisan di 16 tempat), hanya
	// jalur bacanya yang berhenti di satu filter.
	//
	// NAMA di-JOIN saat DIBACA, tak pernah disalin ke metadata: kolom itu sengaja
	// bebas PII, dan nama yang disalin ke sana jadi salinan permanen yang tak ikut
	// terhapus bersama usernya. LEFT JOIN, sebab jejak wajib tetap terbaca setelah
	// pelaku/sasarannya hilang — actor_user_id ON DELETE SET NULL, dan target_id
	// sengaja BUKAN FK.
	//
	// Sasaran dicari dari DUA tabel sesuai target_type, dan syarat itu WAJIB ada di
	// klausa JOIN-nya: tanpa `target_type = '...'`, id workspace akan mencocoki
	// baris users yang id-nya kebetulan sama, lalu memampangkan nama orang yang tak
	// terlibat. Salah, dan terlihat meyakinkan.
	//
	// Filter opsional lewat sqlc.narg (NULL = tanpa filter) supaya satu query
	// melayani semua kombinasi — dua query terpisah akan berbeda diam-diam begitu
	// salah satunya diubah.
	ListActivityTrail(ctx context.Context, arg ListActivityTrailParams) ([]ListActivityTrailRow, error)
	// Query sumbu RBAC bisnis (F2/F3) yang bisa diedit per-workspace. Dua tabel:
	// business_roles (definisi peran + data_scope) & business_role_permissions
	// (matriks obj/act). Enforcer Casbin di-load dari permissions; data_scope dibaca
	// per-request untuk filter kepemilikan desa (F3).
	// STARTUP: seluruh izin SEMUA tenant, untuk membangun enforcer bisnis global
	// (subject di-fold jadi `t<tenant_id>:<role>` di Go). WAJIB dipanggil di dalam
	// WithSuper — di tenant-tx, RLS menyembunyikan tenant lain → enforcer deny-all
	// senyap untuk mereka.
	ListAllBusinessRolePermissions(ctx context.Context) ([]ListAllBusinessRolePermissionsRow, error)
	ListAuditLogs(ctx context.Context, pageSize int32) ([]AuditLog, error)
	// Izin SATU workspace — dipakai reload per-tenant setelah matriks diubah, dan
	// untuk merender editor. Urut agar diff/tampilan stabil.
	ListBusinessRolePermissionsByTenant(ctx context.Context, tenantID int64) ([]ListBusinessRolePermissionsByTenantRow, error)
	// Daftar peran satu workspace (panel /roles + assign ke member). is_system dulu
	// agar admin (peran terkunci) tampil di atas. member_count = jumlah anggota yang
	// memegang peran ini (kolom "Jumlah User" di wireframe 9.2) — LEFT JOIN agar peran
	// tanpa pemegang tetap muncul dengan 0. COALESCE ke bigint: sqlc emit int64, bukan
	// interface{}. GROUP BY br.id (PK) sah — kolom br.* bergantung fungsional padanya.
	ListBusinessRoles(ctx context.Context, tenantID int64) ([]ListBusinessRolesRow, error)
	// Dasbor Churn (Menu 5.2/5.4, READ-ONLY). Langganan yang telah berhenti
	// (status Cancelled/Churned), di-scope ownership (F3) dengan flag yang SAMA dgn
	// ListSubscriptions (scope_all → semua; is_own → subscription_owner = uid; keduanya
	// false → NOL baris, fail-closed). Filter tipe churn opsional lewat type_filter
	// (Voluntary/Involuntary); '' → semua tipe. Kolom churn (lost_value_mrr, churn_reason,
	// cancellation_date) dibawa di s.* → tanpa JOIN tambahan. Urut created_at DESC +
	// keyset SAMA dgn ListSubscriptions (reuse pageCursor/splitPage).
	ListChurned(ctx context.Context, arg ListChurnedParams) ([]ListChurnedRow, error)
	// Semua format kode workspace, untuk halaman pengaturan. Sedikit barisnya (satu
	// per entitas), jadi tak dipaginasi. Urut per entity agar tampilannya stabil.
	ListCodeFormats(ctx context.Context, tenantID int64) ([]CodeFormat, error)
	// Daftar kontak LINTAS-desa, keyset + filter kepemilikan DESA INDUK (bukan filter
	// kontak sendiri). JOIN accounts membawa kolom ownership desa; flag scope_all/
	// is_sales/is_csm identik dengan ListAccounts (AccountsListFilter) — "kontak siapa
	// yang tampil" diturunkan dari "desa siapa yang tampil", satu kebenaran.
	// Ketiganya false (Support/role kosong/liar) → NOL baris (fail-closed).
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	// Kontak SATU desa, keyset (created_at DESC, id DESC). TANPA filter ownership:
	// gerbangnya adalah desa induk (handler memvalidasi via loadOwnedAccount sebelum
	// memanggil ini). Kontak utama diangkat ke atas agar penanda primary langsung
	// terlihat tanpa menggeser urutan kronologis baris lainnya.
	ListContactsByAccount(ctx context.Context, arg ListContactsByAccountParams) ([]Contact, error)
	// Daftar deal (tampilan Tabel), keyset (created_at DESC, id DESC) + filter
	// ownership F3 + filter stage opsional. Dua flag ownership (sumber SATU dengan
	// DealsListFilter): scope_all → semua; is_own → deal_owner = uid; keduanya false
	// → NOL baris (fail-closed). stage_filter '' → semua stage.
	ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error)
	// Papan Kanban: seluruh deal hidup dalam cakupan ownership, diurutkan agar kartu
	// rapi per-stage lalu terbaru dulu. Di-bucket per-stage di handler (bukan N query
	// per kolom). LIMIT membatasi papan agar tak memuat seluruh tabel (guardrail
	// pagination); deal di luar batas tetap terlihat lewat tampilan Tabel berkeyset.
	ListDealsForPipeline(ctx context.Context, arg ListDealsForPipelineParams) ([]Deal, error)
	// Kandidat purge permanen: terhapus melewati masa tenggang. Dipanggil perintah
	// terjadwal, TAK PERNAH di jalur request (purge = kerja berat & tak reversibel).
	ListExpiredTenants(ctx context.Context, deletedAt pgtype.Timestamptz) ([]Tenant, error)
	// Undangan PENDING satu workspace (panel anggota) — yang sudah diterima disaring.
	ListInvitesByTenant(ctx context.Context, tenantID int64) ([]Invite, error)
	// Daftar lead, keyset (created_at DESC, id DESC) + filter ownership F3 + tab.
	//
	// Ownership sebagai dua flag boolean (bukan SQL dinamis) supaya query tetap sqlc
	// murni & ter-scan typed — sumber SATU dengan LeadsListFilter (ownership.go):
	//   scope_all → lihat semua (Admin/Manager)
	//   is_own    → hanya lead_owner = uid (Sales)
	// Keduanya false (Support/role kosong/liar) → NOL baris (fail-closed).
	//
	// Tab tambahan (ortogonal dari ownership):
	//   mine_only  → paksa lead_owner = uid (tab "My Leads", walau aktor scope_all)
	//   status_filter '' → semua status; selain itu = filter satu status ("Unqualified")
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error)
	// user_id anggota workspace dgn business_role tertentu — dipakai menarget
	// notifikasi (mis. semua Manager saat renewal Upsell menunggu persetujuan).
	// memberships SENGAJA tanpa RLS (dibaca untuk MENENTUKAN scope), jadi filter
	// tenant_id EKSPLISIT. Cast ::text pada param → sqlc emit `string` (non-null);
	// baris ber-business_role NULL tak pernah cocok, itu benar (belum berperan CRM).
	ListMembersByBusinessRole(ctx context.Context, arg ListMembersByBusinessRoleParams) ([]int64, error)
	// Daftar anggota SATU workspace (panel /admin/members). JOIN users untuk data
	// tampilan — users kini tabel global (tanpa RLS), jadi filter tenant di sini.
	//
	// `u.name` ikut diambil dan MENDAHULUI email sebagai penanda orang di layar.
	// Emailnya tetap dibawa karena pengelola membutuhkannya (mengundang,
	// mencocokkan orang) — yang menahannya dari mata lain adalah handler, yang
	// menyamarkannya sebelum data menyentuh view.
	//
	// m.business_role (sumbu CRM, tegak lurus role tenant) ikut agar kolom "Peran
	// CRM" di /members bisa memilih nilai saat ini tanpa query per-baris (Rule 13);
	// NULL = belum diberi peran CRM.
	ListMembersByTenant(ctx context.Context, tenantID int64) ([]ListMembersByTenantRow, error)
	// Daftar workspace milik user (untuk switcher sidebar). Urut terlama dulu agar
	// workspace pertama (dari register) jadi default stabil.
	//
	// Workspace TERHAPUS disembunyikan (0005): ia juga jadi sumber pilihan fallback
	// middleware Scope, jadi tanpa filter ini user bisa dilempar ke workspace yang
	// sudah dihapus. status ikut dikembalikan agar switcher bisa menandai yang
	// suspended/archived alih-alih membiarkan user menabrak 403 setelah mengklik.
	// is_primary ikut dikembalikan karena sidebar menghitung sisa kuota dari daftar
	// ini; tanpanya hitungannya akan BERBEDA dari CountOwnedWorkspaces, dan user
	// melihat tombol "Buat workspace" yang lalu ditolak (atau sebaliknya).
	ListMembershipsByUser(ctx context.Context, userID int64) ([]ListMembershipsByUserRow, error)
	// Membership BANYAK user sekaligus (panel /dev: tampilkan workspace+role tiap
	// user). Satu query untuk semua id → hindari N+1 (Rule 13).
	ListMembershipsForUsers(ctx context.Context, userIds []int64) ([]ListMembershipsForUsersRow, error)
	// Keyset pagination (pola ListUsers) — cast ::timestamptz/::bigint WAJIB, tanpa
	// itu sqlc salah infer tipe cursor_id pada row-value comparison.
	//
	// `user_id = $1` BUKAN sekadar filter tampilan: notifications sengaja TANPA RLS
	// (lihat 00009), jadi klausa ini adalah SATU-SATUNYA penjaga isolasi antar-user.
	// Jangan pernah menghapusnya "karena sudah difilter di Go".
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListOAuthAccountsByUser(ctx context.Context, userID int64) ([]OauthAccount, error)
	// Undangan yang ditujukan ke SATU ORANG (halaman notifikasi). Dicari per-email,
	// bukan user_id: saat diundang penerima belum tentu punya akun.
	//
	// lower(email) = $1 — pemanggil WAJIB mengirim email yang sudah di-lowercase
	// (pola auth.go/invite.go). Ditopang index partial idx_invites_email.
	ListPendingInvitesByEmail(ctx context.Context, email string) ([]ListPendingInvitesByEmailRow, error)
	// plans.sql — katalog master (plans), dibaca untuk Quote Builder (Modul 4 Sales).
	// Isolasi WORKSPACE ditegakkan RLS (GUC app.tenant_id di WithTenant); tak ada
	// filter tenant_id manual. plans TANPA soft-delete: is_active=false = pensiun
	// (harga historis di quote memakai SNAPSHOT quote_items.unit_price, bukan referensi
	// hidup ke sini). Query ini menopang picker plan + baca base_price saat add item.
	// Plan aktif untuk picker item quote, urut nama. Hanya is_active=true: plan pensiun
	// tak boleh dijual baru (tapi quote lama tetap sah lewat snapshot). Bounded katalog
	// master per-workspace → tanpa keyset.
	ListPlans(ctx context.Context) ([]Plan, error)
	// ── Katalog master CRUD (M5-2) — kelola plan di /plans ───────────────────────
	// plans TANPA soft-delete: is_active=false = pensiun (harga historis aman via
	// snapshot quote_items). SetPlanActive = pensiunkan/aktifkan; UpdatePlan menyunting
	// profil (is_active punya jalur sendiri agar pensiun terlihat sebagai aksi khusus).
	// Seluruh katalog untuk tampilan kelola (TERMASUK yang pensiun) — beda dari
	// ListPlans (hanya aktif, untuk picker quote). Aktif dulu lalu urut nama. Bounded
	// katalog master per-workspace → tanpa keyset.
	ListPlansAll(ctx context.Context) ([]Plan, error)
	ListPlatformStaff(ctx context.Context) ([]PlatformStaff, error)
	// Baris item satu quote, urut tampil (line_no lalu id). Menopang detail quote &
	// rekalkulasi total. Bounded per-quote (bukan daftar global) → tanpa keyset.
	ListQuoteItems(ctx context.Context, quoteID int64) ([]QuoteItem, error)
	// Daftar quote LINTAS-deal (menu Quotes global), keyset (created_at DESC, id DESC)
	// + filter ownership F3 DIWARISI dari deal induk (JOIN deals → deal_owner). Dua flag
	// sama dengan ListDeals: scope_all → semua; is_own → deal_owner = uid; keduanya
	// false → NOL baris (fail-closed). INNER JOIN deals: quote selalu menempel ke deal
	// (deal_id di-set saat create); quote tanpa deal hidup TAK tampil di daftar global
	// (tak punya owner untuk disaring). deal_name dibawa untuk kolom "Deal".
	ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error)
	// Daftar quote milik satu deal (detail deal → daftar quote-nya), keyset
	// (created_at DESC, id DESC). Deal sudah ter-scope ownership di handler; di sini
	// cukup filter deal_id + baris hidup. First page: cursor = (now(), max bigint).
	ListQuotesForDeal(ctx context.Context, arg ListQuotesForDealParams) ([]Quote, error)
	// Riwayat renewal (M5-4): telusuri rantai MUNDUR dari satu langganan lewat
	// previous_subscription_id (self-FK) sampai periode paling awal, lalu urut kronologis
	// (lama→baru). Rekursif via self-FK (bukan filter account+plan) karena renewal
	// Upsell/Downgrade bisa berganti plan — hanya self-FK yang otoritatif sbg tautan
	// rantai. Termasuk baris ter-soft-delete (riwayat tak boleh berlubang).
	ListRenewalChain(ctx context.Context, id int64) ([]ListRenewalChainRow, error)
	// Dasbor Renewals (Menu 5.2, READ-ONLY — aksi perpanjangan ada di detail langganan,
	// bukan di sini). Langganan yang punya dimensi renewal (end_date terisi), di-scope
	// ownership (F3) dengan flag yang SAMA dgn ListSubscriptions. Empat JENDELA lewat
	// window_filter (today dioper handler agar mengikuti zona waktu app & bisa
	// dideterministikkan test):
	//   • 'due'     : Active/PendingApproval, end_date ∈ [today, today+30] — jatuh tempo.
	//   • 'grace'   : Active, end_date < today — lewat tempo tapi masih berjalan.
	//   • 'renewed' : renewal_status = 'Renewed' — sudah diperpanjang.
	//   • lainnya   : semua langganan ber-end_date (jendela 'Semua').
	// Urut created_at DESC + keyset SAMA dgn ListSubscriptions (reuse pageCursor/
	// splitPage); pengurutan "paling dekat jatuh tempo" ditunda ke slice KPI/agregasi.
	// previous_value dibawa di s.* untuk kolom "Prev→Current" (tanpa JOIN tambahan).
	ListRenewals(ctx context.Context, arg ListRenewalsParams) ([]ListRenewalsRow, error)
	// Semua pengaturan sekaligus — dipakai halaman /dev/settings dan pemuatan cache
	// saat boot. Jumlahnya sedikit, jadi tak dipaginasi (beda dari daftar user).
	ListSettings(ctx context.Context) ([]PlatformSetting, error)
	// Daftar langganan (menu /subscriptions), keyset (created_at DESC, id DESC) + filter
	// ownership F3 + filter status opsional. Dua flag ownership (sumber SATU dgn
	// SubscriptionsListFilter): scope_all → semua; is_own → subscription_owner = uid;
	// keduanya false → NOL baris (fail-closed). status_filter '' → semua status.
	// JOIN accounts+plans membawa nama untuk kolom (hindari N+1, rule 13); INNER JOIN
	// aman karena account_id/plan_id NOT NULL. accounts di-filter baris hidup.
	ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error)
	// Daftar langganan satu desa (detail account → langganannya), keyset. Account sudah
	// ter-scope ownership di handler; di sini cukup filter account_id + baris hidup.
	// plan_name dibawa untuk kolom "Paket".
	ListSubscriptionsForAccount(ctx context.Context, arg ListSubscriptionsForAccountParams) ([]ListSubscriptionsForAccountRow, error)
	// Daftar workspace untuk panel /dev (lintas-workspace — route platform). Termasuk
	// yang suspended/archived: justru itu yang perlu dilihat operator. Yang TERHAPUS
	// ikut tampil agar restore masih mungkin selama masa tenggang.
	ListTenantsForPlatform(ctx context.Context, arg ListTenantsForPlatformParams) ([]ListTenantsForPlatformRow, error)
	// Panel /dev: keyset pagination, hanya user aktif (belum soft-delete).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Tautkan hasil konversi ke lead + kunci statusnya. Dipanggil DALAM tx konversi
	// (bersama INSERT account/contact/deal) → gagal-sebagian rollback penuh. Guard
	// "hanya Qualified & belum converted" ada di WHERE agar konversi ganda idempotent-
	// aman: baris yang sudah converted tak ter-update lagi.
	MarkLeadConverted(ctx context.Context, arg MarkLeadConvertedParams) error
	// Auto-read saat halaman dibuka. Undangan TIDAK tersentuh di sini — memang tak
	// disimpan di tabel ini (sumber kebenarannya tetap `invites`), sehingga undangan
	// pending tetap terhitung di badge sampai benar-benar ditindak.
	MarkNotificationsRead(ctx context.Context, userID int64) error
	// Alokasi nomor urut BERIKUTNYA untuk (tenant, entity), ATOMIK.
	//
	// Kenapa satu pernyataan INSERT..ON CONFLICT dan bukan SELECT max+1 di Go: ON
	// CONFLICT DO UPDATE mengambil ROW LOCK pada baris counter, jadi dua create
	// bersamaan diserialkan oleh Postgres — mustahil dapat nomor sama. Menghitung di
	// aplikasi (baca lalu tulis) justru race yang paling sering lolos sampai dua
	// baris bertabrakan di produksi.
	//
	// next_val = "nomor yang akan DIPAKAI berikutnya" (mulai 1). Kita menyimpan hasil
	// SESUDAH dinaikkan lalu pemanggil mengurangi 1 (lihat GenerateEntityCode):
	//   • baris belum ada → INSERT next_val=2, RETURNING 2 → alokasi 2-1=1
	//   • baris next_val=N → UPDATE jadi N+1, RETURNING N+1 → alokasi (N+1)-1=N
	// RETURNING kolom mentah (BIGINT NOT NULL) supaya sqlc mengetiknya int64, bukan
	// pointer nullable (ekspresi aritmetika di RETURNING akan ditebak nullable).
	NextEntityCodeSeq(ctx context.Context, arg NextEntityCodeSeqParams) (int64, error)
	// Tren per HARI-LOKAL untuk rentang mingguan/bulanan (line chart).
	PresenceByDay(ctx context.Context, arg PresenceByDayParams) ([]PresenceByDayRow, error)
	// Distribusi aktivitas per JAM-LOKAL untuk satu rentang (bar "aktivitas per jam").
	// AT TIME ZONE mengonversi bucket UTC ke jam lokal. Handler mengisi jam kosong
	// jadi 0 (sumbu X ECharts butuh 0..23 lengkap). COALESCE+cast: SUM/COUNT nullable
	// → paksa int64 (bukan pgtype.Numeric).
	PresenceByHour(ctx context.Context, arg PresenceByHourParams) ([]PresenceByHourRow, error)
	// KPI ringkas untuk stat cards pada rentang aktif.
	PresenceKPIs(ctx context.Context, arg PresenceKPIsParams) (PresenceKPIsRow, error)
	// "User aktif jam berapa s/d jam berapa" untuk rentang: first/last seen per user +
	// total hit. JOIN users untuk email TAMPILAN panel (dev-only UI, bukan log — tabel
	// activity_presence sendiri hanya simpan user_id). first/last dikembalikan sebagai
	// timestamptz UTC; handler memformatnya ke jam lokal (appTZ) — lebih bersih dari
	// AT TIME ZONE di SQL (yang bikin sqlc emit interface{}).
	PresenceUserSpans(ctx context.Context, arg PresenceUserSpansParams) ([]PresenceUserSpansRow, error)
	// Retensi: buang jejak yang lebih tua dari batas. Dipanggil pemeliharaan
	// terjadwal, TAK PERNAH di jalur request.
	//
	// Tabel ini append-only dan dulu tumbuh selamanya. Selama tak pernah dibaca itu
	// cuma soal disk; begitu ia jadi halaman yang aktif dibuka, biayanya ikut ke
	// setiap query. Yang dibayar: peristiwa lebih lama dari batas TAK BISA
	// diselidiki lagi — karena itu batasnya hidup di platform_settings (bisa
	// dinaikkan operator sebelum sesuatu telanjur hilang), bukan dipaku di kode.
	//
	// Mengembalikan JUMLAH baris terhapus supaya pemeliharaan bisa mencatat apa yang
	// sebenarnya terjadi: pekerjaan pembersihan yang diam tak bisa dibedakan dari
	// pekerjaan yang tak pernah jalan.
	PurgeAuditLogsBefore(ctx context.Context, before pgtype.Timestamptz) (int64, error)
	// Hapus PERMANEN. memberships/invites/notifications ikut CASCADE (data
	// operasional); audit_logs TIDAK — FK-nya ON DELETE SET NULL sejak migrasi 00010,
	// sebab bukti tak boleh lenyap bersama yang dibuktikan (0005 §6).
	PurgeTenant(ctx context.Context, id int64) error
	// Jumlah subtotal seluruh item satu quote dalam satu round-trip (untuk rekalkulasi
	// grand_total tanpa memuat semua baris ke Go). COALESCE(...)::numeric membungkus
	// agregat agar sqlc tak meng-emit interface{} (gotcha #14).
	QuoteItemsSubtotal(ctx context.Context, quoteID int64) (pgtype.Numeric, error)
	// Presence bucket 15-menit. bucket_at di-floor SERVER-SIDE ke kelipatan 900 dtk
	// (jangan hitung di Go — hindari drift clock). Agregasi di level baris: request
	// berulang dalam bucket sama hanya menaikkan hits, bukan insert baris baru.
	RecordPresence(ctx context.Context, arg RecordPresenceParams) error
	// Tolak renewal Upsell yang menunggu (M5-3c): baris 'PendingApproval' → 'Cancelled'.
	// Baris lama TAK disentuh — ia tetap 'Active' (renewal batal, langganan berjalan).
	// Filter status='PendingApproval' = penjaga transisi (idem ApproveRenewal).
	RejectRenewal(ctx context.Context, arg RejectRenewalParams) (Subscription, error)
	RemovePlatformStaff(ctx context.Context, email string) error
	// Batalkan penghapusan dalam masa tenggang. Status dikembalikan ke 'active':
	// workspace yang dihapus saat ter-arsip pun kembali sebagai aktif — pemulihan
	// harus meninggalkan keadaan yang bisa langsung dipakai, bukan setengah jalan.
	RestoreTenant(ctx context.Context, id int64) error
	// Tautkan deal ke langganan hasil create-from-deal (deals.created_subscription_id;
	// FK ditutup di migrasi 00012). Dipanggil dalam tx yang SAMA dgn CreateSubscription
	// agar deal Closed Won selalu menunjuk langganan yang lahir darinya (atomik).
	SetDealCreatedSubscription(ctx context.Context, arg SetDealCreatedSubscriptionParams) error
	// Pensiunkan (false) atau aktifkan kembali (true) plan. Plan pensiun hilang dari
	// ListPlans (picker) tapi quote/langganan lama tetap sah (snapshot harga).
	SetPlanActive(ctx context.Context, arg SetPlanActiveParams) error
	// Angkat SATU kontak jadi utama. Pemanggil WAJIB memanggil ClearAccountPrimaryContact
	// lebih dulu (satu tx) — index memblokir dua utama. account_id ikut di WHERE sebagai
	// sabuk pengaman: kontak yang bukan milik desa itu tak bisa diangkat lewat jalurnya.
	SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
	// entitas lain — deal/tiket — tak putus). Idempotent: hanya baris hidup.
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak aktivitas
	// bertahan). Idempotent: hanya baris hidup.
	SoftDeleteActivity(ctx context.Context, arg SoftDeleteActivityParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
	// entitas lain tak putus). Idempotent: hanya baris hidup. Kontak utama yang dihapus
	// membebaskan slot primary (index-nya partial WHERE deleted_at IS NULL).
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK dari
	// leads.converted_deal_id tak putus). Idempotent: hanya baris hidup.
	SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (jejak & FK
	// converted_* tak putus). Idempotent: hanya baris hidup.
	SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) error
	// Soft-delete: quote disembunyikan dari list/get tapi tetap ada. quote_items
	// anaknya di-hard-delete oleh CASCADE hanya bila quote benar-benar di-DROP —
	// di sini baris quote hanya ditandai, item tetap tersimpan.
	SoftDeleteQuote(ctx context.Context, arg SoftDeleteQuoteParams) error
	// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (rantai renewal &
	// FK dari deals.created_subscription_id tak putus). Idempotent: hanya baris hidup.
	SoftDeleteSubscription(ctx context.Context, arg SoftDeleteSubscriptionParams) error
	// Owner ATAU platform. Masa tenggang: baris tetap ada, slug TIDAK dilepas.
	//
	// `NOT is_primary`: rumah aplikasi tak bisa dihapus dari dalam aplikasi itu
	// sendiri. Di mode single ia satu-satunya workspace — menghapusnya berarti
	// menghapus aplikasinya, lewat tombol yang di workspace lain berarti "hapus
	// salah satu dari beberapa".
	SoftDeleteTenant(ctx context.Context, id int64) error
	SoftDeleteUser(ctx context.Context, id int64) error
	// PLATFORM-ONLY (super_admin/staff). Owner tak bisa membatalkannya sendiri —
	// kalau bisa, gunanya hilang (0005 §1). Alasan disimpan agar pertanyaan support
	// pertama ("kenapa workspace saya mati") terjawab tanpa menggali audit log.
	SuspendTenant(ctx context.Context, arg SuspendTenantParams) error
	// Cek ketersediaan slug (untuk auto-suffix unik: acme -> acme-2 -> ...). Ikut
	// menghitung workspace TERHAPUS: slug tak dilepas selama masa tenggang, kalau
	// dilepas orang lain bisa mengambilnya & restore jadi mustahil (0005 §5).
	TenantSlugExists(ctx context.Context, slug string) (bool, error)
	// OWNER. Hanya dari 'archived' — tak bisa dipakai membatalkan suspensi platform.
	UnarchiveTenant(ctx context.Context, id int64) error
	// Cabut satu business_role dari SEMUA anggota workspace yang memegangnya —
	// dipanggil SEBELUM menghapus perannya, agar penghapusan peran meng-unassign
	// orang alih-alih (lewat FK) menghapus keanggotaannya. Idempoten.
	UnassignBusinessRole(ctx context.Context, arg UnassignBusinessRoleParams) error
	// PLATFORM-ONLY. Membersihkan jejak suspensi agar kolomnya tak jadi sisa yang
	// menyesatkan saat suspensi berikutnya.
	UnsuspendTenant(ctx context.Context, id int64) error
	// Sunting profil desa. entity_code & village_code tak diubah di sini (kode identitas
	// yang dikutip; village_code punya jalur khusus bila kelak perlu). Penugasan
	// (owner/CSM) juga TERPISAH (AssignAccountCSM) agar perubahan wewenang terlihat
	// sebagai aksi tersendiri, bukan efek samping edit profil.
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	// Sunting aktivitas. kind & target TAK di sini: kind menentukan bentuk form
	// (immutable saat edit), target ditetapkan saat create. status punya jalur
	// khusus (UpdateActivityStatus) agar perpindahan terlihat sebagai aksi tersendiri.
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	// Ubah status (aksi tersendiri, cermin UpdateDealStage). Validasi enum di handler
	// (allowlist) + CHECK DB sebagai jaring terakhir.
	UpdateActivityStatus(ctx context.Context, arg UpdateActivityStatusParams) error
	// Sunting label, deskripsi & cakupan peran. name (subject Casbin) TAK diubah di
	// sini — mengganti nama peran memutus assign yang sudah ada; kalau perlu, buat
	// peran baru. is_system tak bisa disunting (dijaga di handler, bukan di query).
	UpdateBusinessRole(ctx context.Context, arg UpdateBusinessRoleParams) error
	// Sunting kontak. is_primary_contact di-set pemanggil setelah mengosongkan primary
	// lama (ClearAccountPrimaryContact) bila dinaikkan jadi utama. account_id TIDAK
	// diubah di sini — memindahkan kontak antar-desa adalah aksi lain (belum ada).
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	// Sunting profil deal. entity_code, stage, dan hasil (win_loss_reason/closed_date)
	// TAK di sini: stage punya jalur khusus (UpdateDealStage) agar perpindahan pipeline
	// terlihat sebagai aksi tersendiri, bukan efek samping edit.
	UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error)
	// Pindah stage pipeline (aksi tersendiri). closed_date/win_loss_reason/loss_notes
	// diisi saat Closed Won/Lost — validasi "Closed Lost wajib win_loss_reason" di
	// handler (bukan constraint DB agar pesan bisa diperbaiki user). closed_date =
	// CURRENT_DATE bila stage terminal, NULL bila dibuka kembali ke stage aktif.
	UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) error
	// Sunting profil & kualifikasi lead. entity_code tak diubah (kode identitas yang
	// dikutip). converted_* TAK disentuh di sini — itu efek konversi (ConvertLead),
	// bukan edit biasa.
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
	// Set/ganti business_role (sumbu CRM F2) satu anggota. Nilai divalidasi tenant-
	// aware di handler (ada di business_roles workspace ini) SEBELUM query — kolom
	// tak lagi punya CHECK sejak 00007. NULL = cabut peran CRM (mis. saat perannya
	// dihapus) — pgtype/pointer NULL diteruskan apa adanya.
	UpdateMemberBusinessRole(ctx context.Context, arg UpdateMemberBusinessRoleParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	// Sunting profil plan. is_active TAK di sini (SetPlanActive) — pensiun/aktifkan
	// adalah aksi tersendiri, bukan efek samping edit. plan_code boleh diubah (tetap
	// tunduk idx_plans_code unik).
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	// Sunting profil quote. quote_status punya jalur khusus (UpdateQuoteStatus) dan
	// total punya jalur khusus (UpdateQuoteTotals) — keduanya TAK di sini agar
	// perubahan status & rekalkulasi harga terlihat sebagai aksi tersendiri.
	UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (Quote, error)
	// Sunting qty/diskon satu item; subtotal (snapshot) dihitung ulang app dan ditulis
	// di sini. unit_price TAK diubah (tetap snapshot harga saat item dibuat).
	UpdateQuoteItem(ctx context.Context, arg UpdateQuoteItemParams) (QuoteItem, error)
	// Transisi status (Draft→Sent→…). Aturan transisi valid divalidasi handler (bukan
	// constraint DB) agar pesan bisa diperbaiki user; CHECK di DB hanya membatasi
	// himpunan nilai legal.
	UpdateQuoteStatus(ctx context.Context, arg UpdateQuoteStatusParams) error
	// Rekalkulasi total quote (snapshot) setelah item berubah. grand_total & tax_amount
	// dihitung app dari quote_items lalu ditulis di sini — bukan agregat live saat baca.
	UpdateQuoteTotals(ctx context.Context, arg UpdateQuoteTotalsParams) error
	// Sunting profil langganan. status, renewal-action (6.6), dan churn (5.4) punya
	// jalur sendiri (UpdateSubscriptionStatus/ChurnSubscription) agar transisi status &
	// churn terlihat sebagai aksi tersendiri, bukan efek samping edit.
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	// Transisi status (Trial→Active, Active→Expired saat renewal, dst). Aturan transisi
	// valid divalidasi handler (bukan constraint DB) agar pesan bisa diperbaiki user;
	// subs_status_chk hanya membatasi himpunan nilai legal. INVARIAN renewal: Expired
	// baris lama HARUS mendahului CreateSubscription baris aktif dalam tx yang sama.
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	// Ganti NAMA tampilan workspace (owner-only, di-guard di handler). Slug SENGAJA
	// tak diubah — immutable setelah dibuat (stabilitas URL; ganti display != ganti URL).
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	// Profil dari provider (avatar + nama tampilan) di-refresh TIAP LOGIN: keduanya
	// berubah di sisi Google tanpa memberi tahu kita, dan login adalah satu-satunya
	// saat kita mendengar kabar terbaru.
	//
	// COALESCE, bukan penimpaan lugas: argumen NULL berarti "provider tak
	// mengirimkan apa pun kali ini", BUKAN "hapus yang tersimpan". Tanpa ini, satu
	// respons Google tanpa `picture` (boleh terjadi walau scope diminta) akan
	// menghapus avatar yang sudah benar. Nilai lama lebih baik daripada tak ada.
	//
	// Konsekuensi yang disengaja: user yang MENGHAPUS fotonya di Google tetap
	// memakai foto lamanya di sini. Ditukar sadar dengan menghindari penghapusan
	// palsu, yang jauh lebih sering terjadi.
	//
	// CATATAN untuk kelak: begitu ada fitur "edit profil" di aplikasi ini, refresh
	// otomatis ini akan MENIMPA nama yang disunting user tiap kali ia login. Saat
	// itu tiba, nama pilihan sendiri harus jadi kolom terpisah yang diutamakan —
	// jangan sekadar mematikan refresh, sebab avatar tetap perlu ikut berubah.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// Kuota workspace per user. NULL = IKUT DEFAULT GLOBAL (platform_settings), angka
	// = hak khusus milik user itu yang kebal perubahan global. Membedakan keduanya
	// adalah alasan kolom ini nullable — dgn NOT NULL, "kebetulan 3" tak bisa
	// dibedakan dari "sengaja diberi 3".
	UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	// Simpan/ubah format satu entitas. UPSERT: baris mungkin belum ada (default masih
	// dipakai) — operator hanya menyentuh baris saat ingin MENGUBAH default. created_by
	// diisi saat pertama dibuat; updated_by/updated_at tiap kali diubah.
	UpsertCodeFormat(ctx context.Context, arg UpsertCodeFormatParams) error
	// Simpan pengaturan. UPSERT karena baris mungkin belum ada (deployment baru yang
	// tak menjalankan seed): pemanggil tak perlu tahu bedanya.
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
