// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seeddemo_purge.sql

package db

import (
	"context"
)

const purgeSeedAccounts = `-- name: PurgeSeedAccounts :exec
DELETE FROM accounts WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedAccounts(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedAccounts, tenantID)
	return err
}

const purgeSeedActivities = `-- name: PurgeSeedActivities :exec

DELETE FROM activities WHERE tenant_id = $1
`

// seeddemo_purge.sql — DELETE per-tabel ber-tenant untuk `seeddemo -reset`
// (BL-79). Bukan jalur produksi: dipakai HANYA oleh cmd/seeddemo untuk
// membersihkan data demo sebelum isi ulang, dijalankan di dalam db.WithTenant
// (RLS mengikat, app_rw punya hak DELETE). Preseden pola Purge* di package db:
// PurgeTenant (tenants.sql) & PurgeAuditLogsBefore (audit.sql).
//
// Semua saring `WHERE tenant_id = $1` — jadi tak pernah menyentuh workspace lain
// bahkan seandainya RLS dilepas. Pemanggil (cmd/seeddemo/purge.go) mengurutkan
// pemanggilan anak→induk sebab beberapa FK ber-ON DELETE RESTRICT (cs_impl_tasks,
// cs_trainings, engagements, success_plans, tickets) menolak hapus induk selagi
// anak ada; urutan di SATU query tak menjamin itu.
func (q *Queries) PurgeSeedActivities(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedActivities, tenantID)
	return err
}

const purgeSeedCSImplTasks = `-- name: PurgeSeedCSImplTasks :exec
DELETE FROM cs_impl_tasks WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedCSImplTasks(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedCSImplTasks, tenantID)
	return err
}

const purgeSeedCSTrainings = `-- name: PurgeSeedCSTrainings :exec
DELETE FROM cs_trainings WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedCSTrainings(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedCSTrainings, tenantID)
	return err
}

const purgeSeedContacts = `-- name: PurgeSeedContacts :exec
DELETE FROM contacts WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedContacts(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedContacts, tenantID)
	return err
}

const purgeSeedCustomerSuccess = `-- name: PurgeSeedCustomerSuccess :exec
DELETE FROM customer_success WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedCustomerSuccess(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedCustomerSuccess, tenantID)
	return err
}

const purgeSeedDeals = `-- name: PurgeSeedDeals :exec
DELETE FROM deals WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedDeals(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedDeals, tenantID)
	return err
}

const purgeSeedEngagements = `-- name: PurgeSeedEngagements :exec
DELETE FROM engagements WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedEngagements(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedEngagements, tenantID)
	return err
}

const purgeSeedKBArticles = `-- name: PurgeSeedKBArticles :exec
DELETE FROM kb_articles WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedKBArticles(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedKBArticles, tenantID)
	return err
}

const purgeSeedLeads = `-- name: PurgeSeedLeads :exec
DELETE FROM leads WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedLeads(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedLeads, tenantID)
	return err
}

const purgeSeedPlans = `-- name: PurgeSeedPlans :exec
DELETE FROM plans WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedPlans(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedPlans, tenantID)
	return err
}

const purgeSeedPlaybooks = `-- name: PurgeSeedPlaybooks :exec
DELETE FROM playbooks WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedPlaybooks(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedPlaybooks, tenantID)
	return err
}

const purgeSeedQuoteItems = `-- name: PurgeSeedQuoteItems :exec
DELETE FROM quote_items WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedQuoteItems(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedQuoteItems, tenantID)
	return err
}

const purgeSeedQuotes = `-- name: PurgeSeedQuotes :exec
DELETE FROM quotes WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedQuotes(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedQuotes, tenantID)
	return err
}

const purgeSeedSLAPolicies = `-- name: PurgeSeedSLAPolicies :exec
DELETE FROM sla_policies WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedSLAPolicies(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedSLAPolicies, tenantID)
	return err
}

const purgeSeedSubscriptions = `-- name: PurgeSeedSubscriptions :exec
DELETE FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedSubscriptions(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedSubscriptions, tenantID)
	return err
}

const purgeSeedSuccessPlans = `-- name: PurgeSeedSuccessPlans :exec
DELETE FROM success_plans WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedSuccessPlans(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedSuccessPlans, tenantID)
	return err
}

const purgeSeedTickets = `-- name: PurgeSeedTickets :exec
DELETE FROM tickets WHERE tenant_id = $1
`

func (q *Queries) PurgeSeedTickets(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, purgeSeedTickets, tenantID)
	return err
}
