// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sla_policies.sql

package db

import (
	"context"
)

const createSLAPolicy = `-- name: CreateSLAPolicy :one
INSERT INTO sla_policies (
    tenant_id, sla_name, applies_to_priority,
    first_response_target_minutes, resolution_target_minutes,
    business_hours, escalation_rule, is_active, created_by
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9
)
RETURNING id, tenant_id, sla_name, applies_to_priority, first_response_target_minutes, resolution_target_minutes, business_hours, escalation_rule, is_active, created_by, created_at, updated_by, updated_at
`

type CreateSLAPolicyParams struct {
	TenantID                   int64   `json:"tenant_id"`
	SlaName                    string  `json:"sla_name"`
	AppliesToPriority          *string `json:"applies_to_priority"`
	FirstResponseTargetMinutes *int32  `json:"first_response_target_minutes"`
	ResolutionTargetMinutes    *int32  `json:"resolution_target_minutes"`
	BusinessHours              *string `json:"business_hours"`
	EscalationRule             *string `json:"escalation_rule"`
	IsActive                   bool    `json:"is_active"`
	CreatedBy                  *int64  `json:"created_by"`
}

// Buat kebijakan SLA. tenant_id eksplisit (RLS WITH CHECK memverifikasinya =
// GUC). is_active default true di skema tapi di-set eksplisit agar handler
// bisa membuat draft pensiun bila diperlukan nanti.
func (q *Queries) CreateSLAPolicy(ctx context.Context, arg CreateSLAPolicyParams) (SlaPolicy, error) {
	row := q.db.QueryRow(ctx, createSLAPolicy,
		arg.TenantID,
		arg.SlaName,
		arg.AppliesToPriority,
		arg.FirstResponseTargetMinutes,
		arg.ResolutionTargetMinutes,
		arg.BusinessHours,
		arg.EscalationRule,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SlaName,
		&i.AppliesToPriority,
		&i.FirstResponseTargetMinutes,
		&i.ResolutionTargetMinutes,
		&i.BusinessHours,
		&i.EscalationRule,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSLAPolicy = `-- name: GetSLAPolicy :one
SELECT id, tenant_id, sla_name, applies_to_priority, first_response_target_minutes, resolution_target_minutes, business_hours, escalation_rule, is_active, created_by, created_at, updated_by, updated_at FROM sla_policies
WHERE id = $1
`

// Satu kebijakan (untuk baca target saat dipakai D1/D2). RLS menjamin
// tenant_id. Tak filter is_active: handler memutuskan.
func (q *Queries) GetSLAPolicy(ctx context.Context, id int64) (SlaPolicy, error) {
	row := q.db.QueryRow(ctx, getSLAPolicy, id)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SlaName,
		&i.AppliesToPriority,
		&i.FirstResponseTargetMinutes,
		&i.ResolutionTargetMinutes,
		&i.BusinessHours,
		&i.EscalationRule,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listSLAPolicies = `-- name: ListSLAPolicies :many

SELECT id, tenant_id, sla_name, applies_to_priority, first_response_target_minutes, resolution_target_minutes, business_hours, escalation_rule, is_active, created_by, created_at, updated_by, updated_at FROM sla_policies
WHERE is_active = true
ORDER BY sla_name ASC, id ASC
`

// sla_policies.sql — katalog master (SLA Policies), Modul 6 Customer Success
// slice A1. Isolasi WORKSPACE ditegakkan RLS (GUC app.tenant_id di WithTenant);
// tak ada filter tenant_id manual. sla_policies TANPA soft-delete: is_active=
// false = pensiun (kebijakan lama tak dipakai lagi, tapi riwayat tiket lama
// yang sudah memakainya tetap sah — D1/D2 menyalin target saat tiket dibuat,
// bukan referensi hidup ke sini). Target respon/selesai satuan MENIT (migrasi
// 00016). Meniru pola plans.sql.
// Kebijakan aktif untuk picker (dipakai D1/D2 saat menentukan target tiket
// baru per prioritas). Hanya is_active=true. Bounded katalog master
// per-workspace → tanpa keyset.
func (q *Queries) ListSLAPolicies(ctx context.Context) ([]SlaPolicy, error) {
	rows, err := q.db.Query(ctx, listSLAPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlaPolicy{}
	for rows.Next() {
		var i SlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SlaName,
			&i.AppliesToPriority,
			&i.FirstResponseTargetMinutes,
			&i.ResolutionTargetMinutes,
			&i.BusinessHours,
			&i.EscalationRule,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLAPoliciesAll = `-- name: ListSLAPoliciesAll :many
SELECT id, tenant_id, sla_name, applies_to_priority, first_response_target_minutes, resolution_target_minutes, business_hours, escalation_rule, is_active, created_by, created_at, updated_by, updated_at FROM sla_policies
ORDER BY is_active DESC, sla_name ASC, id ASC
`

// Seluruh katalog untuk tampilan kelola (TERMASUK yang pensiun) — beda dari
// ListSLAPolicies (hanya aktif). Aktif dulu lalu urut nama. Bounded katalog
// master per-workspace → tanpa keyset.
func (q *Queries) ListSLAPoliciesAll(ctx context.Context) ([]SlaPolicy, error) {
	rows, err := q.db.Query(ctx, listSLAPoliciesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlaPolicy{}
	for rows.Next() {
		var i SlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SlaName,
			&i.AppliesToPriority,
			&i.FirstResponseTargetMinutes,
			&i.ResolutionTargetMinutes,
			&i.BusinessHours,
			&i.EscalationRule,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSLAPolicyActive = `-- name: SetSLAPolicyActive :exec
UPDATE sla_policies SET
    is_active  = $1,
    updated_by = $2,
    updated_at = now()
WHERE id = $3
`

type SetSLAPolicyActiveParams struct {
	IsActive  bool   `json:"is_active"`
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Pensiunkan (false) atau aktifkan kembali (true) kebijakan. Kebijakan
// pensiun hilang dari ListSLAPolicies (picker) tapi tetap tampil di kelola.
func (q *Queries) SetSLAPolicyActive(ctx context.Context, arg SetSLAPolicyActiveParams) error {
	_, err := q.db.Exec(ctx, setSLAPolicyActive, arg.IsActive, arg.UpdatedBy, arg.ID)
	return err
}

const updateSLAPolicy = `-- name: UpdateSLAPolicy :one
UPDATE sla_policies SET
    sla_name                       = $1,
    applies_to_priority            = $2,
    first_response_target_minutes  = $3,
    resolution_target_minutes      = $4,
    business_hours                 = $5,
    escalation_rule                = $6,
    updated_by                     = $7,
    updated_at                     = now()
WHERE id = $8
RETURNING id, tenant_id, sla_name, applies_to_priority, first_response_target_minutes, resolution_target_minutes, business_hours, escalation_rule, is_active, created_by, created_at, updated_by, updated_at
`

type UpdateSLAPolicyParams struct {
	SlaName                    string  `json:"sla_name"`
	AppliesToPriority          *string `json:"applies_to_priority"`
	FirstResponseTargetMinutes *int32  `json:"first_response_target_minutes"`
	ResolutionTargetMinutes    *int32  `json:"resolution_target_minutes"`
	BusinessHours              *string `json:"business_hours"`
	EscalationRule             *string `json:"escalation_rule"`
	UpdatedBy                  *int64  `json:"updated_by"`
	ID                         int64   `json:"id"`
}

// Sunting profil kebijakan. is_active TAK di sini (SetSLAPolicyActive) —
// pensiun/aktifkan adalah aksi tersendiri, bukan efek samping edit.
func (q *Queries) UpdateSLAPolicy(ctx context.Context, arg UpdateSLAPolicyParams) (SlaPolicy, error) {
	row := q.db.QueryRow(ctx, updateSLAPolicy,
		arg.SlaName,
		arg.AppliesToPriority,
		arg.FirstResponseTargetMinutes,
		arg.ResolutionTargetMinutes,
		arg.BusinessHours,
		arg.EscalationRule,
		arg.UpdatedBy,
		arg.ID,
	)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SlaName,
		&i.AppliesToPriority,
		&i.FirstResponseTargetMinutes,
		&i.ResolutionTargetMinutes,
		&i.BusinessHours,
		&i.EscalationRule,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
