// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountHasLiveSubscription = `-- name: AccountHasLiveSubscription :one
SELECT EXISTS (
    SELECT 1 FROM subscriptions s
    WHERE s.account_id = $1
      AND s.deleted_at IS NULL
      AND s.status IN ('Trial','Active','Suspended')
)
`

// BL-114: apakah desa adalah PELANGGAN aktif — punya ≥1 langganan hidup
// (Trial/Active/Suspended). Menggerbang tulis Customer Success (A8): desa tanpa
// langganan hidup (prospek / churned) → Customer Success read-only. Terminal
// (Expired/Cancelled/Churned) TIDAK dihitung hidup. RLS menyaring tenant.
func (q *Queries) AccountHasLiveSubscription(ctx context.Context, accountID int64) (bool, error) {
	row := q.db.QueryRow(ctx, accountHasLiveSubscription, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const addSubscriptionItem = `-- name: AddSubscriptionItem :one

INSERT INTO subscription_items (
    subscription_id, tenant_id, plan_id, quantity, unit_price, discount_pct,
    subtotal, mrr, arr, line_no
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, subscription_id, tenant_id, plan_id, quantity, unit_price, discount_pct, subtotal, mrr, arr, line_no, account_id, parent_active
`

type AddSubscriptionItemParams struct {
	SubscriptionID int64          `json:"subscription_id"`
	TenantID       int64          `json:"tenant_id"`
	PlanID         *int64         `json:"plan_id"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountPct    pgtype.Numeric `json:"discount_pct"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	Mrr            pgtype.Numeric `json:"mrr"`
	Arr            pgtype.Numeric `json:"arr"`
	LineNo         *int16         `json:"line_no"`
}

// ── subscription_items — baris langganan (BL-88 PR2a; hard-delete, mirror quote_items) ──
// Tambah baris item langganan. tenant_id eksplisit (RLS WITH CHECK). unit_price &
// subtotal = SNAPSHOT komersial disalin dari quote_items saat Closed Won; mrr/arr
// per-item diturunkan app (subtotal/bulan-termin). Beku sesudahnya.
func (q *Queries) AddSubscriptionItem(ctx context.Context, arg AddSubscriptionItemParams) (SubscriptionItem, error) {
	row := q.db.QueryRow(ctx, addSubscriptionItem,
		arg.SubscriptionID,
		arg.TenantID,
		arg.PlanID,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountPct,
		arg.Subtotal,
		arg.Mrr,
		arg.Arr,
		arg.LineNo,
	)
	var i SubscriptionItem
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.TenantID,
		&i.PlanID,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountPct,
		&i.Subtotal,
		&i.Mrr,
		&i.Arr,
		&i.LineNo,
		&i.AccountID,
		&i.ParentActive,
	)
	return i, err
}

const approveRenewal = `-- name: ApproveRenewal :one
UPDATE subscriptions SET
    status          = 'Active',
    approval_status = 'Approved',
    approved_by     = $1,
    approved_at     = now(),
    updated_by      = $2,
    updated_at      = now()
WHERE id = $3 AND status = 'PendingApproval' AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, subscription_owner, account_id, plan_id, source_deal_id, previous_subscription_id, status, start_date, end_date, billing_cycle, auto_renew, contract_term_months, mrr, arr, quantity_seats, discount_pct, payment_status, renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value, renewal_stage, renewal_risk, renewal_action_plan, renewal_next_action_date, cancellation_date, churn_reason, churn_type, churn_notes, lost_value_mrr, win_back_eligible, deleted_at, created_by, created_at, updated_by, updated_at, approval_status, approved_by, approved_at
`

type ApproveRenewalParams struct {
	ApprovedBy *int64 `json:"approved_by"`
	UpdatedBy  *int64 `json:"updated_by"`
	ID         int64  `json:"id"`
}

// Setujui renewal Upsell yang menunggu (M5-3c): baris 'PendingApproval' → 'Active'.
// Handler WAJIB meng-Expired baris lama (previous_subscription_id) SEBELUM query ini
// dalam tx yang sama — invarian idx_subs_one_active (1 Active per account+plan).
// Filter status='PendingApproval' = penjaga transisi: baris yang sudah diputus tak
// bisa disetujui dua kali (0 baris ter-update → handler kabari "tak lagi pending").
func (q *Queries) ApproveRenewal(ctx context.Context, arg ApproveRenewalParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, approveRenewal, arg.ApprovedBy, arg.UpdatedBy, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.SubscriptionOwner,
		&i.AccountID,
		&i.PlanID,
		&i.SourceDealID,
		&i.PreviousSubscriptionID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.BillingCycle,
		&i.AutoRenew,
		&i.ContractTermMonths,
		&i.Mrr,
		&i.Arr,
		&i.QuantitySeats,
		&i.DiscountPct,
		&i.PaymentStatus,
		&i.RenewalStatus,
		&i.RenewalType,
		&i.RenewalOwner,
		&i.RenewalQuoteID,
		&i.PreviousValue,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.CancellationDate,
		&i.ChurnReason,
		&i.ChurnType,
		&i.ChurnNotes,
		&i.LostValueMrr,
		&i.WinBackEligible,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const churnSubscription = `-- name: ChurnSubscription :exec
UPDATE subscriptions SET
    status            = $1,
    cancellation_date = $2,
    churn_reason      = $3,
    churn_type        = $4,
    churn_notes       = $5,
    lost_value_mrr    = $6,
    win_back_eligible = $7,
    updated_by        = $8,
    updated_at        = now()
WHERE id = $9 AND deleted_at IS NULL
`

type ChurnSubscriptionParams struct {
	Status           string         `json:"status"`
	CancellationDate pgtype.Date    `json:"cancellation_date"`
	ChurnReason      *string        `json:"churn_reason"`
	ChurnType        *string        `json:"churn_type"`
	ChurnNotes       *string        `json:"churn_notes"`
	LostValueMrr     pgtype.Numeric `json:"lost_value_mrr"`
	WinBackEligible  *bool          `json:"win_back_eligible"`
	UpdatedBy        *int64         `json:"updated_by"`
	ID               int64          `json:"id"`
}

// Churn (5.4): satu aksi bisnis — set status (Cancelled/Churned) + seluruh kolom
// churn sekaligus. Domain churn_reason/churn_type dijaga subs_churn_*_chk.
func (q *Queries) ChurnSubscription(ctx context.Context, arg ChurnSubscriptionParams) error {
	_, err := q.db.Exec(ctx, churnSubscription,
		arg.Status,
		arg.CancellationDate,
		arg.ChurnReason,
		arg.ChurnType,
		arg.ChurnNotes,
		arg.LostValueMrr,
		arg.WinBackEligible,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const createSubscription = `-- name: CreateSubscription :one

INSERT INTO subscriptions (
    tenant_id, entity_code, subscription_owner, account_id, plan_id,
    source_deal_id, previous_subscription_id,
    status, approval_status, start_date, end_date, billing_cycle, auto_renew, contract_term_months,
    mrr, arr, quantity_seats, discount_pct, payment_status,
    renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value,
    created_by
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18,
    $19,
    $20, $21, $22,
    $23, $24,
    $25
)
RETURNING id, tenant_id, entity_code, subscription_owner, account_id, plan_id, source_deal_id, previous_subscription_id, status, start_date, end_date, billing_cycle, auto_renew, contract_term_months, mrr, arr, quantity_seats, discount_pct, payment_status, renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value, renewal_stage, renewal_risk, renewal_action_plan, renewal_next_action_date, cancellation_date, churn_reason, churn_type, churn_notes, lost_value_mrr, win_back_eligible, deleted_at, created_by, created_at, updated_by, updated_at, approval_status, approved_by, approved_at
`

type CreateSubscriptionParams struct {
	TenantID               int64          `json:"tenant_id"`
	EntityCode             *string        `json:"entity_code"`
	SubscriptionOwner      *int64         `json:"subscription_owner"`
	AccountID              int64          `json:"account_id"`
	PlanID                 *int64         `json:"plan_id"`
	SourceDealID           *int64         `json:"source_deal_id"`
	PreviousSubscriptionID *int64         `json:"previous_subscription_id"`
	Status                 string         `json:"status"`
	ApprovalStatus         *string        `json:"approval_status"`
	StartDate              pgtype.Date    `json:"start_date"`
	EndDate                pgtype.Date    `json:"end_date"`
	BillingCycle           *string        `json:"billing_cycle"`
	AutoRenew              bool           `json:"auto_renew"`
	ContractTermMonths     *int32         `json:"contract_term_months"`
	Mrr                    pgtype.Numeric `json:"mrr"`
	Arr                    pgtype.Numeric `json:"arr"`
	QuantitySeats          *int32         `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric `json:"discount_pct"`
	PaymentStatus          *string        `json:"payment_status"`
	RenewalStatus          *string        `json:"renewal_status"`
	RenewalType            *string        `json:"renewal_type"`
	RenewalOwner           *int64         `json:"renewal_owner"`
	RenewalQuoteID         *int64         `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric `json:"previous_value"`
	CreatedBy              *int64         `json:"created_by"`
}

// subscriptions.sql — langganan (Subscription), Modul 5 slice 2. Isolasi WORKSPACE
// ditegakkan RLS (GUC app.tenant_id di WithTenant); isolasi ANTAR-DESA (F3)
// ditegakkan di layer query lewat flag ownership di ListSubscriptions (kolom
// subscription_owner) — pola sama dgn deals (lihat ownership.go).
//
// KEPUTUSAN inti (docs/crm/skema.md §5, migrasi 00012):
//   - Renewal = INSERT baris BARU (CreateSubscription dgn previous_subscription_id
//   - previous_value), BUKAN update. Handler WAJIB meng-Expired baris lama
//     (UpdateSubscriptionStatus 'Expired') SEBELUM CreateSubscription baris aktif,
//     dalam SATU tx — kalau tidak, idx_subs_one_active (1 Active per account+plan)
//     menolak INSERT kedua. Urutan itu = invarian, ditegakkan test M5-5.
//   - Create-from-deal = CreateSubscription (source_deal_id) lalu
//     SetDealCreatedSubscription (deals.sql) dalam tx yang sama → tautan dua-arah.
//   - Churn = ChurnSubscription (status Cancelled/Churned + kolom churn 5.4 sekali
//     tulis; churn adalah SATU aksi bisnis, bukan edit profil).
//   - ARR DISIMPAN (bukan MRR×12); field-level masking ARR utk non-manager = urusan
//     handler/view (F4), bukan query.
//
// entity_code (SUB-0001) dialokasikan GenerateEntityCode DALAM tx create.
// Buat langganan. tenant_id eksplisit (RLS WITH CHECK memverifikasinya = GUC).
// Dipakai DUA jalur: (a) create-from-deal (source_deal_id terisi, previous_* NULL);
// (b) renewal (previous_subscription_id + previous_value terisi, source_deal_id
// opsional). status default 'Trial' di skema tapi di-set eksplisit (renewal lahir
// 'Active'). Kolom renewal-action (6.6) & churn (5.4) TIDAK di-set di sini — punya
// jalur sendiri.
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.EntityCode,
		arg.SubscriptionOwner,
		arg.AccountID,
		arg.PlanID,
		arg.SourceDealID,
		arg.PreviousSubscriptionID,
		arg.Status,
		arg.ApprovalStatus,
		arg.StartDate,
		arg.EndDate,
		arg.BillingCycle,
		arg.AutoRenew,
		arg.ContractTermMonths,
		arg.Mrr,
		arg.Arr,
		arg.QuantitySeats,
		arg.DiscountPct,
		arg.PaymentStatus,
		arg.RenewalStatus,
		arg.RenewalType,
		arg.RenewalOwner,
		arg.RenewalQuoteID,
		arg.PreviousValue,
		arg.CreatedBy,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.SubscriptionOwner,
		&i.AccountID,
		&i.PlanID,
		&i.SourceDealID,
		&i.PreviousSubscriptionID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.BillingCycle,
		&i.AutoRenew,
		&i.ContractTermMonths,
		&i.Mrr,
		&i.Arr,
		&i.QuantitySeats,
		&i.DiscountPct,
		&i.PaymentStatus,
		&i.RenewalStatus,
		&i.RenewalType,
		&i.RenewalOwner,
		&i.RenewalQuoteID,
		&i.PreviousValue,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.CancellationDate,
		&i.ChurnReason,
		&i.ChurnType,
		&i.ChurnNotes,
		&i.LostValueMrr,
		&i.WinBackEligible,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const getLatestSubscriptionForAccount = `-- name: GetLatestSubscriptionForAccount :one
SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at, p.plan_name,
    (SELECT COUNT(*) FROM subscription_items si WHERE si.subscription_id = s.id)::bigint AS item_count
FROM subscriptions s
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.account_id = $1 AND s.deleted_at IS NULL
ORDER BY s.created_at DESC, s.id DESC
LIMIT 1
`

type GetLatestSubscriptionForAccountRow struct {
	ID                     int64              `json:"id"`
	TenantID               int64              `json:"tenant_id"`
	EntityCode             *string            `json:"entity_code"`
	SubscriptionOwner      *int64             `json:"subscription_owner"`
	AccountID              int64              `json:"account_id"`
	PlanID                 *int64             `json:"plan_id"`
	SourceDealID           *int64             `json:"source_deal_id"`
	PreviousSubscriptionID *int64             `json:"previous_subscription_id"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	BillingCycle           *string            `json:"billing_cycle"`
	AutoRenew              bool               `json:"auto_renew"`
	ContractTermMonths     *int32             `json:"contract_term_months"`
	Mrr                    pgtype.Numeric     `json:"mrr"`
	Arr                    pgtype.Numeric     `json:"arr"`
	QuantitySeats          *int32             `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric     `json:"discount_pct"`
	PaymentStatus          *string            `json:"payment_status"`
	RenewalStatus          *string            `json:"renewal_status"`
	RenewalType            *string            `json:"renewal_type"`
	RenewalOwner           *int64             `json:"renewal_owner"`
	RenewalQuoteID         *int64             `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric     `json:"previous_value"`
	RenewalStage           *string            `json:"renewal_stage"`
	RenewalRisk            *string            `json:"renewal_risk"`
	RenewalActionPlan      *string            `json:"renewal_action_plan"`
	RenewalNextActionDate  pgtype.Date        `json:"renewal_next_action_date"`
	CancellationDate       pgtype.Date        `json:"cancellation_date"`
	ChurnReason            *string            `json:"churn_reason"`
	ChurnType              *string            `json:"churn_type"`
	ChurnNotes             *string            `json:"churn_notes"`
	LostValueMrr           pgtype.Numeric     `json:"lost_value_mrr"`
	WinBackEligible        *bool              `json:"win_back_eligible"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              *int64             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *int64             `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ApprovalStatus         *string            `json:"approval_status"`
	ApprovedBy             *int64             `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	PlanName               *string            `json:"plan_name"`
	ItemCount              int64              `json:"item_count"`
}

// Langganan TERBARU satu desa (kartu "Ringkasan Langganan" di detail Account) —
// satu baris tanpa keyset, beda kebutuhan dari ListSubscriptionsForAccount (daftar
// berhalaman). plan_name ikut lewat JOIN plans yang sama. pgx.ErrNoRows = desa
// belum pernah berlangganan (empty-state di handler, bukan error).
func (q *Queries) GetLatestSubscriptionForAccount(ctx context.Context, accountID int64) (GetLatestSubscriptionForAccountRow, error) {
	row := q.db.QueryRow(ctx, getLatestSubscriptionForAccount, accountID)
	var i GetLatestSubscriptionForAccountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.SubscriptionOwner,
		&i.AccountID,
		&i.PlanID,
		&i.SourceDealID,
		&i.PreviousSubscriptionID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.BillingCycle,
		&i.AutoRenew,
		&i.ContractTermMonths,
		&i.Mrr,
		&i.Arr,
		&i.QuantitySeats,
		&i.DiscountPct,
		&i.PaymentStatus,
		&i.RenewalStatus,
		&i.RenewalType,
		&i.RenewalOwner,
		&i.RenewalQuoteID,
		&i.PreviousValue,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.CancellationDate,
		&i.ChurnReason,
		&i.ChurnType,
		&i.ChurnNotes,
		&i.LostValueMrr,
		&i.WinBackEligible,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PlanName,
		&i.ItemCount,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, entity_code, subscription_owner, account_id, plan_id, source_deal_id, previous_subscription_id, status, start_date, end_date, billing_cycle, auto_renew, contract_term_months, mrr, arr, quantity_seats, discount_pct, payment_status, renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value, renewal_stage, renewal_risk, renewal_action_plan, renewal_next_action_date, cancellation_date, churn_reason, churn_type, churn_notes, lost_value_mrr, win_back_eligible, deleted_at, created_by, created_at, updated_by, updated_at, approval_status, approved_by, approved_at FROM subscriptions
WHERE id = $1 AND deleted_at IS NULL
`

// Satu langganan hidup. RLS menjamin tenant_id; ownership (F3) diputuskan handler
// atas baris (SubscriptionsListFilter.Allows), bukan di sini.
func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.SubscriptionOwner,
		&i.AccountID,
		&i.PlanID,
		&i.SourceDealID,
		&i.PreviousSubscriptionID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.BillingCycle,
		&i.AutoRenew,
		&i.ContractTermMonths,
		&i.Mrr,
		&i.Arr,
		&i.QuantitySeats,
		&i.DiscountPct,
		&i.PaymentStatus,
		&i.RenewalStatus,
		&i.RenewalType,
		&i.RenewalOwner,
		&i.RenewalQuoteID,
		&i.PreviousValue,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.CancellationDate,
		&i.ChurnReason,
		&i.ChurnType,
		&i.ChurnNotes,
		&i.LostValueMrr,
		&i.WinBackEligible,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const hasActiveItemConflictForSubscription = `-- name: HasActiveItemConflictForSubscription :one
SELECT EXISTS (
    SELECT 1
    FROM subscription_items si
    JOIN subscription_items other
      ON other.account_id = si.account_id
     AND other.plan_id    = si.plan_id
     AND other.subscription_id <> si.subscription_id
     AND other.parent_active
    WHERE si.subscription_id = $1
      AND si.plan_id IS NOT NULL
)
`

// Pre-check aktivasi Trial→Active (BL-88 PR2b): benar bila SALAH SATU paket langganan
// yang hendak diaktifkan sudah punya item Active di langganan LAIN untuk desa yang sama.
// Langganan yg diaktifkan masih Trial (parent_active=false pada item-nya) → sisi `other`
// (parent_active) mengecualikannya dgn sendirinya. RLS jamin tenant.
func (q *Queries) HasActiveItemConflictForSubscription(ctx context.Context, subscriptionID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveItemConflictForSubscription, subscriptionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActiveItemForQuotePlans = `-- name: HasActiveItemForQuotePlans :one
SELECT EXISTS (
    SELECT 1
    FROM subscription_items si
    JOIN quote_items qi ON qi.plan_id = si.plan_id
    WHERE si.account_id = $1
      AND si.parent_active
      AND qi.quote_id = $2
      AND qi.plan_id IS NOT NULL
)
`

type HasActiveItemForQuotePlansParams struct {
	AccountID int64 `json:"account_id"`
	QuoteID   int64 `json:"quote_id"`
}

// Pre-check Won (BL-88 PR2b): benar bila SALAH SATU paket di quote yang di-Accept sudah
// punya item Active untuk desa ini. Menggantikan HasActiveSubscriptionForPlan berbasis
// deals.plan_requested_id (single-plan) — kini invarian ada di subscription_items
// (parent_active = status Active & belum terhapus). Pesan ramah SEBELUM buat langganan;
// idx_subscription_items_one_active tetap penjaga keras bila balapan. RLS jamin tenant.
func (q *Queries) HasActiveItemForQuotePlans(ctx context.Context, arg HasActiveItemForQuotePlansParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveItemForQuotePlans, arg.AccountID, arg.QuoteID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCSRenewals = `-- name: ListCSRenewals :many
SELECT
    s.id,
    s.account_id,
    s.status,
    s.end_date,
    s.renewal_status,
    s.renewal_stage,
    s.renewal_risk,
    s.renewal_action_plan,
    s.renewal_next_action_date,
    s.renewal_owner,
    s.created_at,
    a.village_name,
    p.plan_name,
    u.name AS renewal_owner_name,
    (SELECT COUNT(*) FROM subscription_items si WHERE si.subscription_id = s.id)::bigint AS item_count
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id AND a.deleted_at IS NULL
LEFT JOIN plans p ON p.id = s.plan_id
LEFT JOIN users u ON u.id = s.renewal_owner
WHERE s.deleted_at IS NULL
  AND s.end_date IS NOT NULL
  AND (s.created_at, s.id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND (
          a.account_owner = $5
          OR a.assigned_csm = $5
          OR a.backup_csm  = $5
      ))
  )
  AND ($6::text = '' OR s.renewal_stage = $6::text)
ORDER BY s.created_at DESC, s.id DESC
LIMIT $7
`

type ListCSRenewalsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	FilterStage     string             `json:"filter_stage"`
	PageSize        int32              `json:"page_size"`
}

type ListCSRenewalsRow struct {
	ID                    int64              `json:"id"`
	AccountID             int64              `json:"account_id"`
	Status                string             `json:"status"`
	EndDate               pgtype.Date        `json:"end_date"`
	RenewalStatus         *string            `json:"renewal_status"`
	RenewalStage          *string            `json:"renewal_stage"`
	RenewalRisk           *string            `json:"renewal_risk"`
	RenewalActionPlan     *string            `json:"renewal_action_plan"`
	RenewalNextActionDate pgtype.Date        `json:"renewal_next_action_date"`
	RenewalOwner          *int64             `json:"renewal_owner"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	VillageName           string             `json:"village_name"`
	PlanName              *string            `json:"plan_name"`
	RenewalOwnerName      *string            `json:"renewal_owner_name"`
	ItemCount             int64              `json:"item_count"`
}

// Daftar Renewal Management CS (Menu 6.6). Menampilkan langganan yang punya
// dimensi renewal (end_date terisi), berikut field AKSI CS (renewal_stage,
// renewal_risk, renewal_action_plan, renewal_next_action_date, renewal_owner).
// Data sumber tetap di subscriptions (keputusan "Renewal Dua-Rumah").
//
// F3 ownership via akun (assigned_csm/backup_csm/account_owner = uid) — identik
// dengan TicketsListFilter/EngagementsListFilter, BUKAN subscription_owner,
// karena CS melihat semua desa binaan terlepas siapa sales-owner langganannya.
//
// filter_stage ” → semua stage; non-” → cocokkan persis.
// Keyset (created_at DESC, id DESC) — reuse pageCursor/splitPage standar.
func (q *Queries) ListCSRenewals(ctx context.Context, arg ListCSRenewalsParams) ([]ListCSRenewalsRow, error) {
	rows, err := q.db.Query(ctx, listCSRenewals,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.FilterStage,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCSRenewalsRow{}
	for rows.Next() {
		var i ListCSRenewalsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Status,
			&i.EndDate,
			&i.RenewalStatus,
			&i.RenewalStage,
			&i.RenewalRisk,
			&i.RenewalActionPlan,
			&i.RenewalNextActionDate,
			&i.RenewalOwner,
			&i.CreatedAt,
			&i.VillageName,
			&i.PlanName,
			&i.RenewalOwnerName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurned = `-- name: ListChurned :many
SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at, a.village_name, p.plan_name,
    (SELECT COUNT(*) FROM subscription_items si WHERE si.subscription_id = s.id)::bigint AS item_count
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.deleted_at IS NULL
  AND a.deleted_at IS NULL
  AND s.status IN ('Cancelled', 'Churned')
  AND (s.created_at, s.id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND s.subscription_owner = $5)
  )
  AND ($6::text = '' OR s.churn_type = $6::text)
ORDER BY s.created_at DESC, s.id DESC
LIMIT $7
`

type ListChurnedParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	TypeFilter      string             `json:"type_filter"`
	PageSize        int32              `json:"page_size"`
}

type ListChurnedRow struct {
	ID                     int64              `json:"id"`
	TenantID               int64              `json:"tenant_id"`
	EntityCode             *string            `json:"entity_code"`
	SubscriptionOwner      *int64             `json:"subscription_owner"`
	AccountID              int64              `json:"account_id"`
	PlanID                 *int64             `json:"plan_id"`
	SourceDealID           *int64             `json:"source_deal_id"`
	PreviousSubscriptionID *int64             `json:"previous_subscription_id"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	BillingCycle           *string            `json:"billing_cycle"`
	AutoRenew              bool               `json:"auto_renew"`
	ContractTermMonths     *int32             `json:"contract_term_months"`
	Mrr                    pgtype.Numeric     `json:"mrr"`
	Arr                    pgtype.Numeric     `json:"arr"`
	QuantitySeats          *int32             `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric     `json:"discount_pct"`
	PaymentStatus          *string            `json:"payment_status"`
	RenewalStatus          *string            `json:"renewal_status"`
	RenewalType            *string            `json:"renewal_type"`
	RenewalOwner           *int64             `json:"renewal_owner"`
	RenewalQuoteID         *int64             `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric     `json:"previous_value"`
	RenewalStage           *string            `json:"renewal_stage"`
	RenewalRisk            *string            `json:"renewal_risk"`
	RenewalActionPlan      *string            `json:"renewal_action_plan"`
	RenewalNextActionDate  pgtype.Date        `json:"renewal_next_action_date"`
	CancellationDate       pgtype.Date        `json:"cancellation_date"`
	ChurnReason            *string            `json:"churn_reason"`
	ChurnType              *string            `json:"churn_type"`
	ChurnNotes             *string            `json:"churn_notes"`
	LostValueMrr           pgtype.Numeric     `json:"lost_value_mrr"`
	WinBackEligible        *bool              `json:"win_back_eligible"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              *int64             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *int64             `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ApprovalStatus         *string            `json:"approval_status"`
	ApprovedBy             *int64             `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	VillageName            string             `json:"village_name"`
	PlanName               *string            `json:"plan_name"`
	ItemCount              int64              `json:"item_count"`
}

// Dasbor Churn (Menu 5.2/5.4, READ-ONLY). Langganan yang telah berhenti
// (status Cancelled/Churned), di-scope ownership (F3) dengan flag yang SAMA dgn
// ListSubscriptions (scope_all → semua; is_own → subscription_owner = uid; keduanya
// false → NOL baris, fail-closed). Filter tipe churn opsional lewat type_filter
// (Voluntary/Involuntary); ” → semua tipe. Kolom churn (lost_value_mrr, churn_reason,
// cancellation_date) dibawa di s.* → tanpa JOIN tambahan. Urut created_at DESC +
// keyset SAMA dgn ListSubscriptions (reuse pageCursor/splitPage).
func (q *Queries) ListChurned(ctx context.Context, arg ListChurnedParams) ([]ListChurnedRow, error) {
	rows, err := q.db.Query(ctx, listChurned,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.TypeFilter,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChurnedRow{}
	for rows.Next() {
		var i ListChurnedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.SubscriptionOwner,
			&i.AccountID,
			&i.PlanID,
			&i.SourceDealID,
			&i.PreviousSubscriptionID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.BillingCycle,
			&i.AutoRenew,
			&i.ContractTermMonths,
			&i.Mrr,
			&i.Arr,
			&i.QuantitySeats,
			&i.DiscountPct,
			&i.PaymentStatus,
			&i.RenewalStatus,
			&i.RenewalType,
			&i.RenewalOwner,
			&i.RenewalQuoteID,
			&i.PreviousValue,
			&i.RenewalStage,
			&i.RenewalRisk,
			&i.RenewalActionPlan,
			&i.RenewalNextActionDate,
			&i.CancellationDate,
			&i.ChurnReason,
			&i.ChurnType,
			&i.ChurnNotes,
			&i.LostValueMrr,
			&i.WinBackEligible,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.VillageName,
			&i.PlanName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenewalChain = `-- name: ListRenewalChain :many
WITH RECURSIVE chain AS (
    SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at FROM subscriptions s WHERE s.id = $1
    UNION ALL
    SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at FROM subscriptions s
    JOIN chain c ON s.id = c.previous_subscription_id
)
SELECT id, tenant_id, entity_code, subscription_owner, account_id, plan_id, source_deal_id, previous_subscription_id, status, start_date, end_date, billing_cycle, auto_renew, contract_term_months, mrr, arr, quantity_seats, discount_pct, payment_status, renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value, renewal_stage, renewal_risk, renewal_action_plan, renewal_next_action_date, cancellation_date, churn_reason, churn_type, churn_notes, lost_value_mrr, win_back_eligible, deleted_at, created_by, created_at, updated_by, updated_at, approval_status, approved_by, approved_at FROM chain
ORDER BY created_at ASC, id ASC
`

type ListRenewalChainRow struct {
	ID                     int64              `json:"id"`
	TenantID               int64              `json:"tenant_id"`
	EntityCode             *string            `json:"entity_code"`
	SubscriptionOwner      *int64             `json:"subscription_owner"`
	AccountID              int64              `json:"account_id"`
	PlanID                 *int64             `json:"plan_id"`
	SourceDealID           *int64             `json:"source_deal_id"`
	PreviousSubscriptionID *int64             `json:"previous_subscription_id"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	BillingCycle           *string            `json:"billing_cycle"`
	AutoRenew              bool               `json:"auto_renew"`
	ContractTermMonths     *int32             `json:"contract_term_months"`
	Mrr                    pgtype.Numeric     `json:"mrr"`
	Arr                    pgtype.Numeric     `json:"arr"`
	QuantitySeats          *int32             `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric     `json:"discount_pct"`
	PaymentStatus          *string            `json:"payment_status"`
	RenewalStatus          *string            `json:"renewal_status"`
	RenewalType            *string            `json:"renewal_type"`
	RenewalOwner           *int64             `json:"renewal_owner"`
	RenewalQuoteID         *int64             `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric     `json:"previous_value"`
	RenewalStage           *string            `json:"renewal_stage"`
	RenewalRisk            *string            `json:"renewal_risk"`
	RenewalActionPlan      *string            `json:"renewal_action_plan"`
	RenewalNextActionDate  pgtype.Date        `json:"renewal_next_action_date"`
	CancellationDate       pgtype.Date        `json:"cancellation_date"`
	ChurnReason            *string            `json:"churn_reason"`
	ChurnType              *string            `json:"churn_type"`
	ChurnNotes             *string            `json:"churn_notes"`
	LostValueMrr           pgtype.Numeric     `json:"lost_value_mrr"`
	WinBackEligible        *bool              `json:"win_back_eligible"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              *int64             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *int64             `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ApprovalStatus         *string            `json:"approval_status"`
	ApprovedBy             *int64             `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
}

// Riwayat renewal (M5-4): telusuri rantai MUNDUR dari satu langganan lewat
// previous_subscription_id (self-FK) sampai periode paling awal, lalu urut kronologis
// (lama→baru). Rekursif via self-FK (bukan filter account+plan) karena renewal
// Upsell/Downgrade bisa berganti plan — hanya self-FK yang otoritatif sbg tautan
// rantai. Termasuk baris ter-soft-delete (riwayat tak boleh berlubang).
func (q *Queries) ListRenewalChain(ctx context.Context, id int64) ([]ListRenewalChainRow, error) {
	rows, err := q.db.Query(ctx, listRenewalChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenewalChainRow{}
	for rows.Next() {
		var i ListRenewalChainRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.SubscriptionOwner,
			&i.AccountID,
			&i.PlanID,
			&i.SourceDealID,
			&i.PreviousSubscriptionID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.BillingCycle,
			&i.AutoRenew,
			&i.ContractTermMonths,
			&i.Mrr,
			&i.Arr,
			&i.QuantitySeats,
			&i.DiscountPct,
			&i.PaymentStatus,
			&i.RenewalStatus,
			&i.RenewalType,
			&i.RenewalOwner,
			&i.RenewalQuoteID,
			&i.PreviousValue,
			&i.RenewalStage,
			&i.RenewalRisk,
			&i.RenewalActionPlan,
			&i.RenewalNextActionDate,
			&i.CancellationDate,
			&i.ChurnReason,
			&i.ChurnType,
			&i.ChurnNotes,
			&i.LostValueMrr,
			&i.WinBackEligible,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenewals = `-- name: ListRenewals :many
SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at, a.village_name, p.plan_name,
    (SELECT COUNT(*) FROM subscription_items si WHERE si.subscription_id = s.id)::bigint AS item_count
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.deleted_at IS NULL
  AND a.deleted_at IS NULL
  AND s.end_date IS NOT NULL
  AND (s.created_at, s.id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND s.subscription_owner = $5)
  )
  AND (
      CASE $6::text
        WHEN 'due'     THEN s.status IN ('Active','PendingApproval')
                            AND s.end_date >= $7::date
                            AND s.end_date <= ($7::date + 30)
                            AND s.renewal_status IS DISTINCT FROM 'Renewed'
        WHEN 'grace'   THEN s.status = 'Active' AND s.end_date < $7::date
        WHEN 'renewed' THEN s.renewal_status = 'Renewed'
        ELSE TRUE
      END
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $8
`

type ListRenewalsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	WindowFilter    string             `json:"window_filter"`
	Today           pgtype.Date        `json:"today"`
	PageSize        int32              `json:"page_size"`
}

type ListRenewalsRow struct {
	ID                     int64              `json:"id"`
	TenantID               int64              `json:"tenant_id"`
	EntityCode             *string            `json:"entity_code"`
	SubscriptionOwner      *int64             `json:"subscription_owner"`
	AccountID              int64              `json:"account_id"`
	PlanID                 *int64             `json:"plan_id"`
	SourceDealID           *int64             `json:"source_deal_id"`
	PreviousSubscriptionID *int64             `json:"previous_subscription_id"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	BillingCycle           *string            `json:"billing_cycle"`
	AutoRenew              bool               `json:"auto_renew"`
	ContractTermMonths     *int32             `json:"contract_term_months"`
	Mrr                    pgtype.Numeric     `json:"mrr"`
	Arr                    pgtype.Numeric     `json:"arr"`
	QuantitySeats          *int32             `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric     `json:"discount_pct"`
	PaymentStatus          *string            `json:"payment_status"`
	RenewalStatus          *string            `json:"renewal_status"`
	RenewalType            *string            `json:"renewal_type"`
	RenewalOwner           *int64             `json:"renewal_owner"`
	RenewalQuoteID         *int64             `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric     `json:"previous_value"`
	RenewalStage           *string            `json:"renewal_stage"`
	RenewalRisk            *string            `json:"renewal_risk"`
	RenewalActionPlan      *string            `json:"renewal_action_plan"`
	RenewalNextActionDate  pgtype.Date        `json:"renewal_next_action_date"`
	CancellationDate       pgtype.Date        `json:"cancellation_date"`
	ChurnReason            *string            `json:"churn_reason"`
	ChurnType              *string            `json:"churn_type"`
	ChurnNotes             *string            `json:"churn_notes"`
	LostValueMrr           pgtype.Numeric     `json:"lost_value_mrr"`
	WinBackEligible        *bool              `json:"win_back_eligible"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              *int64             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *int64             `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ApprovalStatus         *string            `json:"approval_status"`
	ApprovedBy             *int64             `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	VillageName            string             `json:"village_name"`
	PlanName               *string            `json:"plan_name"`
	ItemCount              int64              `json:"item_count"`
}

// Dasbor Renewals (Menu 5.2, READ-ONLY — aksi perpanjangan ada di detail langganan,
// bukan di sini). Langganan yang punya dimensi renewal (end_date terisi), di-scope
// ownership (F3) dengan flag yang SAMA dgn ListSubscriptions. Empat JENDELA lewat
// window_filter (today dioper handler agar mengikuti zona waktu app & bisa
// dideterministikkan test):
//   - 'due'     : Active/PendingApproval, end_date ∈ [today, today+30], BELUM Renewed
//     — jatuh tempo (BL-152: yang sudah Renewed eksklusif ke tab 'renewed'
//     agar tak dobel-hitung & badge Diperpanjang menang).
//   - 'grace'   : Active, end_date < today — lewat tempo tapi masih berjalan.
//   - 'renewed' : renewal_status = 'Renewed' — sudah diperpanjang.
//   - lainnya   : semua langganan ber-end_date (jendela 'Semua').
//
// Urut created_at DESC + keyset SAMA dgn ListSubscriptions (reuse pageCursor/
// splitPage); pengurutan "paling dekat jatuh tempo" ditunda ke slice KPI/agregasi.
// previous_value dibawa di s.* untuk kolom "Prev→Current" (tanpa JOIN tambahan).
func (q *Queries) ListRenewals(ctx context.Context, arg ListRenewalsParams) ([]ListRenewalsRow, error) {
	rows, err := q.db.Query(ctx, listRenewals,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.WindowFilter,
		arg.Today,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenewalsRow{}
	for rows.Next() {
		var i ListRenewalsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.SubscriptionOwner,
			&i.AccountID,
			&i.PlanID,
			&i.SourceDealID,
			&i.PreviousSubscriptionID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.BillingCycle,
			&i.AutoRenew,
			&i.ContractTermMonths,
			&i.Mrr,
			&i.Arr,
			&i.QuantitySeats,
			&i.DiscountPct,
			&i.PaymentStatus,
			&i.RenewalStatus,
			&i.RenewalType,
			&i.RenewalOwner,
			&i.RenewalQuoteID,
			&i.PreviousValue,
			&i.RenewalStage,
			&i.RenewalRisk,
			&i.RenewalActionPlan,
			&i.RenewalNextActionDate,
			&i.CancellationDate,
			&i.ChurnReason,
			&i.ChurnType,
			&i.ChurnNotes,
			&i.LostValueMrr,
			&i.WinBackEligible,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.VillageName,
			&i.PlanName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionItems = `-- name: ListSubscriptionItems :many
SELECT id, subscription_id, tenant_id, plan_id, quantity, unit_price, discount_pct, subtotal, mrr, arr, line_no, account_id, parent_active FROM subscription_items
WHERE subscription_id = $1
ORDER BY line_no ASC NULLS LAST, id ASC
`

// Baris item satu langganan, urut tampil (line_no lalu id). Menopang tabel item di
// detail langganan & agregasi per-produk. Bounded per-langganan → tanpa keyset.
func (q *Queries) ListSubscriptionItems(ctx context.Context, subscriptionID int64) ([]SubscriptionItem, error) {
	rows, err := q.db.Query(ctx, listSubscriptionItems, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionItem{}
	for rows.Next() {
		var i SubscriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.TenantID,
			&i.PlanID,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountPct,
			&i.Subtotal,
			&i.Mrr,
			&i.Arr,
			&i.LineNo,
			&i.AccountID,
			&i.ParentActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionItemsWithPlan = `-- name: ListSubscriptionItemsWithPlan :many
SELECT si.id, si.subscription_id, si.tenant_id, si.plan_id, si.quantity,
       si.unit_price, si.discount_pct, si.subtotal, si.mrr, si.arr, si.line_no,
       si.account_id, si.parent_active,
       p.plan_name AS plan_name
FROM subscription_items si
LEFT JOIN plans p ON p.id = si.plan_id
WHERE si.subscription_id = $1
ORDER BY si.line_no ASC NULLS LAST, si.id ASC
`

type ListSubscriptionItemsWithPlanRow struct {
	ID             int64          `json:"id"`
	SubscriptionID int64          `json:"subscription_id"`
	TenantID       int64          `json:"tenant_id"`
	PlanID         *int64         `json:"plan_id"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountPct    pgtype.Numeric `json:"discount_pct"`
	Subtotal       pgtype.Numeric `json:"subtotal"`
	Mrr            pgtype.Numeric `json:"mrr"`
	Arr            pgtype.Numeric `json:"arr"`
	LineNo         *int16         `json:"line_no"`
	AccountID      int64          `json:"account_id"`
	ParentActive   bool           `json:"parent_active"`
	PlanName       *string        `json:"plan_name"`
}

// Sama seperti ListSubscriptionItems + nama paket (LEFT JOIN plans agar baris item
// ber-plan_id NULL / plan terhapus tetap muncul, nama → NULL). Menopang tabel item di
// detail langganan (BL-88 PR2b). Bounded per-langganan → tanpa keyset.
func (q *Queries) ListSubscriptionItemsWithPlan(ctx context.Context, subscriptionID int64) ([]ListSubscriptionItemsWithPlanRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionItemsWithPlan, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionItemsWithPlanRow{}
	for rows.Next() {
		var i ListSubscriptionItemsWithPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.TenantID,
			&i.PlanID,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountPct,
			&i.Subtotal,
			&i.Mrr,
			&i.Arr,
			&i.LineNo,
			&i.AccountID,
			&i.ParentActive,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at, a.village_name, p.plan_name,
    (SELECT COUNT(*) FROM subscription_items si WHERE si.subscription_id = s.id)::bigint AS item_count
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.deleted_at IS NULL
  AND a.deleted_at IS NULL
  AND (s.created_at, s.id) < ($1::timestamptz, $2::bigint)
  AND (
      $3::boolean
      OR ($4::boolean AND s.subscription_owner = $5)
  )
  AND ($6::text = '' OR s.status = $6::text)
  AND (
      $7::text = ''
      OR a.village_name ILIKE '%' || $7 || '%'
      OR p.plan_name ILIKE '%' || $7 || '%'
      OR s.entity_code ILIKE '%' || $7 || '%'
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $8
`

type ListSubscriptionsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	ScopeAll        bool               `json:"scope_all"`
	IsOwn           bool               `json:"is_own"`
	Uid             *int64             `json:"uid"`
	StatusFilter    string             `json:"status_filter"`
	Search          string             `json:"search"`
	PageSize        int32              `json:"page_size"`
}

type ListSubscriptionsRow struct {
	ID                     int64              `json:"id"`
	TenantID               int64              `json:"tenant_id"`
	EntityCode             *string            `json:"entity_code"`
	SubscriptionOwner      *int64             `json:"subscription_owner"`
	AccountID              int64              `json:"account_id"`
	PlanID                 *int64             `json:"plan_id"`
	SourceDealID           *int64             `json:"source_deal_id"`
	PreviousSubscriptionID *int64             `json:"previous_subscription_id"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	BillingCycle           *string            `json:"billing_cycle"`
	AutoRenew              bool               `json:"auto_renew"`
	ContractTermMonths     *int32             `json:"contract_term_months"`
	Mrr                    pgtype.Numeric     `json:"mrr"`
	Arr                    pgtype.Numeric     `json:"arr"`
	QuantitySeats          *int32             `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric     `json:"discount_pct"`
	PaymentStatus          *string            `json:"payment_status"`
	RenewalStatus          *string            `json:"renewal_status"`
	RenewalType            *string            `json:"renewal_type"`
	RenewalOwner           *int64             `json:"renewal_owner"`
	RenewalQuoteID         *int64             `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric     `json:"previous_value"`
	RenewalStage           *string            `json:"renewal_stage"`
	RenewalRisk            *string            `json:"renewal_risk"`
	RenewalActionPlan      *string            `json:"renewal_action_plan"`
	RenewalNextActionDate  pgtype.Date        `json:"renewal_next_action_date"`
	CancellationDate       pgtype.Date        `json:"cancellation_date"`
	ChurnReason            *string            `json:"churn_reason"`
	ChurnType              *string            `json:"churn_type"`
	ChurnNotes             *string            `json:"churn_notes"`
	LostValueMrr           pgtype.Numeric     `json:"lost_value_mrr"`
	WinBackEligible        *bool              `json:"win_back_eligible"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              *int64             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *int64             `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ApprovalStatus         *string            `json:"approval_status"`
	ApprovedBy             *int64             `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	VillageName            string             `json:"village_name"`
	PlanName               *string            `json:"plan_name"`
	ItemCount              int64              `json:"item_count"`
}

// Daftar langganan (menu /subscriptions), keyset (created_at DESC, id DESC) + filter
// ownership F3 + filter status opsional. Dua flag ownership (sumber SATU dgn
// SubscriptionsListFilter): scope_all → semua; is_own → subscription_owner = uid;
// keduanya false → NOL baris (fail-closed). status_filter ” → semua status.
// JOIN accounts membawa nama desa (INNER — account_id NOT NULL). plans di-LEFT JOIN:
// BL-88 PR2b plan_id NULLABLE (langganan multi-paket → identitas di subscription_items,
// plan_name parent NULL). accounts di-filter baris hidup. Kolom "Paket" dirakit handler
// ("N paket" bila >1 item) — plan_name di sini hanya label cepat single-plan.
//
// search ” → tak menyaring; selain itu MEMPERSEMPIT (ILIKE substring, case-
// insensitive) di ATAS ownership+status — tak pernah melebarkan baris. Hanya
// kolom tak-tersamar yang TAMPIL di tabel jadi kunci cari (desa, paket, kode
// entitas); nilai MRR/ARR tersamar TIDAK dijadikan kunci cari (BL-6).
func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
		arg.StatusFilter,
		arg.Search,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsRow{}
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.SubscriptionOwner,
			&i.AccountID,
			&i.PlanID,
			&i.SourceDealID,
			&i.PreviousSubscriptionID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.BillingCycle,
			&i.AutoRenew,
			&i.ContractTermMonths,
			&i.Mrr,
			&i.Arr,
			&i.QuantitySeats,
			&i.DiscountPct,
			&i.PaymentStatus,
			&i.RenewalStatus,
			&i.RenewalType,
			&i.RenewalOwner,
			&i.RenewalQuoteID,
			&i.PreviousValue,
			&i.RenewalStage,
			&i.RenewalRisk,
			&i.RenewalActionPlan,
			&i.RenewalNextActionDate,
			&i.CancellationDate,
			&i.ChurnReason,
			&i.ChurnType,
			&i.ChurnNotes,
			&i.LostValueMrr,
			&i.WinBackEligible,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.VillageName,
			&i.PlanName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForAccount = `-- name: ListSubscriptionsForAccount :many
SELECT s.id, s.tenant_id, s.entity_code, s.subscription_owner, s.account_id, s.plan_id, s.source_deal_id, s.previous_subscription_id, s.status, s.start_date, s.end_date, s.billing_cycle, s.auto_renew, s.contract_term_months, s.mrr, s.arr, s.quantity_seats, s.discount_pct, s.payment_status, s.renewal_status, s.renewal_type, s.renewal_owner, s.renewal_quote_id, s.previous_value, s.renewal_stage, s.renewal_risk, s.renewal_action_plan, s.renewal_next_action_date, s.cancellation_date, s.churn_reason, s.churn_type, s.churn_notes, s.lost_value_mrr, s.win_back_eligible, s.deleted_at, s.created_by, s.created_at, s.updated_by, s.updated_at, s.approval_status, s.approved_by, s.approved_at, p.plan_name,
    (SELECT COUNT(*) FROM subscription_items si WHERE si.subscription_id = s.id)::bigint AS item_count
FROM subscriptions s
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.deleted_at IS NULL
  AND s.account_id = $1
  AND (s.created_at, s.id) < ($2::timestamptz, $3::bigint)
ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListSubscriptionsForAccountParams struct {
	AccountID       int64              `json:"account_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListSubscriptionsForAccountRow struct {
	ID                     int64              `json:"id"`
	TenantID               int64              `json:"tenant_id"`
	EntityCode             *string            `json:"entity_code"`
	SubscriptionOwner      *int64             `json:"subscription_owner"`
	AccountID              int64              `json:"account_id"`
	PlanID                 *int64             `json:"plan_id"`
	SourceDealID           *int64             `json:"source_deal_id"`
	PreviousSubscriptionID *int64             `json:"previous_subscription_id"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	BillingCycle           *string            `json:"billing_cycle"`
	AutoRenew              bool               `json:"auto_renew"`
	ContractTermMonths     *int32             `json:"contract_term_months"`
	Mrr                    pgtype.Numeric     `json:"mrr"`
	Arr                    pgtype.Numeric     `json:"arr"`
	QuantitySeats          *int32             `json:"quantity_seats"`
	DiscountPct            pgtype.Numeric     `json:"discount_pct"`
	PaymentStatus          *string            `json:"payment_status"`
	RenewalStatus          *string            `json:"renewal_status"`
	RenewalType            *string            `json:"renewal_type"`
	RenewalOwner           *int64             `json:"renewal_owner"`
	RenewalQuoteID         *int64             `json:"renewal_quote_id"`
	PreviousValue          pgtype.Numeric     `json:"previous_value"`
	RenewalStage           *string            `json:"renewal_stage"`
	RenewalRisk            *string            `json:"renewal_risk"`
	RenewalActionPlan      *string            `json:"renewal_action_plan"`
	RenewalNextActionDate  pgtype.Date        `json:"renewal_next_action_date"`
	CancellationDate       pgtype.Date        `json:"cancellation_date"`
	ChurnReason            *string            `json:"churn_reason"`
	ChurnType              *string            `json:"churn_type"`
	ChurnNotes             *string            `json:"churn_notes"`
	LostValueMrr           pgtype.Numeric     `json:"lost_value_mrr"`
	WinBackEligible        *bool              `json:"win_back_eligible"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy              *int64             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedBy              *int64             `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ApprovalStatus         *string            `json:"approval_status"`
	ApprovedBy             *int64             `json:"approved_by"`
	ApprovedAt             pgtype.Timestamptz `json:"approved_at"`
	PlanName               *string            `json:"plan_name"`
	ItemCount              int64              `json:"item_count"`
}

// Daftar langganan satu desa (detail account → langganannya), keyset. Account sudah
// ter-scope ownership di handler; di sini cukup filter account_id + baris hidup.
// plan_name dibawa untuk kolom "Paket".
func (q *Queries) ListSubscriptionsForAccount(ctx context.Context, arg ListSubscriptionsForAccountParams) ([]ListSubscriptionsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForAccount,
		arg.AccountID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsForAccountRow{}
	for rows.Next() {
		var i ListSubscriptionsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityCode,
			&i.SubscriptionOwner,
			&i.AccountID,
			&i.PlanID,
			&i.SourceDealID,
			&i.PreviousSubscriptionID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.BillingCycle,
			&i.AutoRenew,
			&i.ContractTermMonths,
			&i.Mrr,
			&i.Arr,
			&i.QuantitySeats,
			&i.DiscountPct,
			&i.PaymentStatus,
			&i.RenewalStatus,
			&i.RenewalType,
			&i.RenewalOwner,
			&i.RenewalQuoteID,
			&i.PreviousValue,
			&i.RenewalStage,
			&i.RenewalRisk,
			&i.RenewalActionPlan,
			&i.RenewalNextActionDate,
			&i.CancellationDate,
			&i.ChurnReason,
			&i.ChurnType,
			&i.ChurnNotes,
			&i.LostValueMrr,
			&i.WinBackEligible,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.PlanName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRenewal = `-- name: RejectRenewal :one
UPDATE subscriptions SET
    status          = 'Cancelled',
    approval_status = 'Rejected',
    approved_by     = $1,
    approved_at     = now(),
    updated_by      = $2,
    updated_at      = now()
WHERE id = $3 AND status = 'PendingApproval' AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, subscription_owner, account_id, plan_id, source_deal_id, previous_subscription_id, status, start_date, end_date, billing_cycle, auto_renew, contract_term_months, mrr, arr, quantity_seats, discount_pct, payment_status, renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value, renewal_stage, renewal_risk, renewal_action_plan, renewal_next_action_date, cancellation_date, churn_reason, churn_type, churn_notes, lost_value_mrr, win_back_eligible, deleted_at, created_by, created_at, updated_by, updated_at, approval_status, approved_by, approved_at
`

type RejectRenewalParams struct {
	ApprovedBy *int64 `json:"approved_by"`
	UpdatedBy  *int64 `json:"updated_by"`
	ID         int64  `json:"id"`
}

// Tolak renewal Upsell yang menunggu (M5-3c): baris 'PendingApproval' → 'Cancelled'.
// Baris lama TAK disentuh — ia tetap 'Active' (renewal batal, langganan berjalan).
// Filter status='PendingApproval' = penjaga transisi (idem ApproveRenewal).
func (q *Queries) RejectRenewal(ctx context.Context, arg RejectRenewalParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, rejectRenewal, arg.ApprovedBy, arg.UpdatedBy, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.SubscriptionOwner,
		&i.AccountID,
		&i.PlanID,
		&i.SourceDealID,
		&i.PreviousSubscriptionID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.BillingCycle,
		&i.AutoRenew,
		&i.ContractTermMonths,
		&i.Mrr,
		&i.Arr,
		&i.QuantitySeats,
		&i.DiscountPct,
		&i.PaymentStatus,
		&i.RenewalStatus,
		&i.RenewalType,
		&i.RenewalOwner,
		&i.RenewalQuoteID,
		&i.PreviousValue,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.CancellationDate,
		&i.ChurnReason,
		&i.ChurnType,
		&i.ChurnNotes,
		&i.LostValueMrr,
		&i.WinBackEligible,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const renewalKPIs = `-- name: RenewalKPIs :one
SELECT
    COUNT(*) FILTER (
        WHERE s.status IN ('Active','PendingApproval')
          AND s.end_date >= $1::date
          AND s.end_date <= ($1::date + 30)
          AND s.renewal_status IS DISTINCT FROM 'Renewed'
    )::bigint AS due_30,
    COUNT(*) FILTER (
        WHERE s.status = 'Active' AND s.end_date < $1::date
    )::bigint AS grace,
    COUNT(*) FILTER (
        WHERE s.renewal_status = 'Renewed'
    )::bigint AS renewed_count,
    COUNT(*) FILTER (
        WHERE s.end_date < $1::date
          AND s.end_date >= ($1::date - INTERVAL '12 months')::date
    )::bigint AS due_past_12m,
    COUNT(*) FILTER (
        WHERE s.end_date < $1::date
          AND s.end_date >= ($1::date - INTERVAL '12 months')::date
          AND EXISTS (
              SELECT 1 FROM subscriptions r
              WHERE r.previous_subscription_id = s.id AND r.deleted_at IS NULL
          )
    )::bigint AS renewed_past_12m
FROM subscriptions s
WHERE s.deleted_at IS NULL
  AND s.end_date IS NOT NULL
  AND (
      $2::boolean
      OR ($3::boolean AND s.subscription_owner = $4)
  )
`

type RenewalKPIsParams struct {
	Today    pgtype.Date `json:"today"`
	ScopeAll bool        `json:"scope_all"`
	IsOwn    bool        `json:"is_own"`
	Uid      *int64      `json:"uid"`
}

type RenewalKPIsRow struct {
	Due30          int64 `json:"due_30"`
	Grace          int64 `json:"grace"`
	RenewedCount   int64 `json:"renewed_count"`
	DuePast12m     int64 `json:"due_past_12m"`
	RenewedPast12m int64 `json:"renewed_past_12m"`
}

// KPI dasbor Renewals (BL-94) dalam SATU round-trip, di-scope ownership (flag
// SAMA dgn ListRenewals/ListSubscriptions: scope_all → semua; is_own →
// subscription_owner = uid; keduanya false → NOL, fail-closed). Predikat cacah
// MENGIKUTI jendela ListRenewals agar KPI konsisten dgn tab:
//   - due_30      : Active/PendingApproval, end_date in [today, today+30], BELUM Renewed
//     (= window 'due'; BL-152: Renewed eksklusif ke renewed_count, tak dobel).
//   - grace       : Active, end_date < today (= window 'grace').
//   - renewed     : renewal_status = 'Renewed' (= window 'renewed', sudah diperpanjang).
//   - Renewal Rate 12 bln (BL-94, definisi SAMA dgn ReportRenewalSummary): renewed_past
//     / due_past atas kohort jatuh tempo (end_date < today) DALAM 12 bln terakhir;
//     "diperpanjang" = ada baris renewal anak (previous_subscription_id menunjuk balik).
//
// today dioper handler (zona waktu app, deterministik utk test). Nilai Rp tak di sini
// (KPI ini murni cacah + rasio); scope RLS menegakkan tenant (tanpa filter manual).
func (q *Queries) RenewalKPIs(ctx context.Context, arg RenewalKPIsParams) (RenewalKPIsRow, error) {
	row := q.db.QueryRow(ctx, renewalKPIs,
		arg.Today,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
	)
	var i RenewalKPIsRow
	err := row.Scan(
		&i.Due30,
		&i.Grace,
		&i.RenewedCount,
		&i.DuePast12m,
		&i.RenewedPast12m,
	)
	return i, err
}

const softDeleteSubscription = `-- name: SoftDeleteSubscription :exec
UPDATE subscriptions SET deleted_at = now(), updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteSubscriptionParams struct {
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Soft-delete: baris disembunyikan dari list/get tapi tetap ada (rantai renewal &
// FK dari deals.created_subscription_id tak putus). Idempotent: hanya baris hidup.
func (q *Queries) SoftDeleteSubscription(ctx context.Context, arg SoftDeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, softDeleteSubscription, arg.UpdatedBy, arg.ID)
	return err
}

const subscriptionListKPIs = `-- name: SubscriptionListKPIs :one
SELECT
    COALESCE(SUM(s.mrr) FILTER (WHERE s.status = 'Active'), 0)::numeric AS total_mrr,
    (COALESCE(SUM(s.mrr) FILTER (WHERE s.status = 'Active'), 0) * 12)::numeric AS total_arr,
    COALESCE(SUM(s.mrr) FILTER (
        WHERE s.status = 'Active'
          AND s.previous_subscription_id IS NULL
          AND s.start_date >= date_trunc('month', $1::date)::date
          AND s.start_date <  (date_trunc('month', $1::date) + INTERVAL '1 month')::date
    ), 0)::numeric AS new_mrr,
    COUNT(*) FILTER (WHERE s.status = 'Active')::bigint AS active_count,
    COUNT(*) FILTER (
        WHERE s.status IN ('Cancelled', 'Churned')
          AND s.cancellation_date >= ($1::date - 30)
          AND s.cancellation_date <= $1::date
    )::bigint AS churned_30,
    (SELECT COUNT(*) FROM accounts a WHERE a.deleted_at IS NULL)::bigint AS total_accounts
FROM subscriptions s
WHERE s.deleted_at IS NULL
  AND (
      $2::boolean
      OR ($3::boolean AND s.subscription_owner = $4)
  )
`

type SubscriptionListKPIsParams struct {
	Today    pgtype.Date `json:"today"`
	ScopeAll bool        `json:"scope_all"`
	IsOwn    bool        `json:"is_own"`
	Uid      *int64      `json:"uid"`
}

type SubscriptionListKPIsRow struct {
	TotalMrr      pgtype.Numeric `json:"total_mrr"`
	TotalArr      pgtype.Numeric `json:"total_arr"`
	NewMrr        pgtype.Numeric `json:"new_mrr"`
	ActiveCount   int64          `json:"active_count"`
	Churned30     int64          `json:"churned_30"`
	TotalAccounts int64          `json:"total_accounts"`
}

// KPI header halaman Subscription Lists (BL-95) dalam SATU round-trip, di-scope
// ownership SAMA dgn ListSubscriptions (scope_all → semua; is_own →
// subscription_owner = uid; keduanya false → NOL, fail-closed). RLS mengurung tenant.
//   - total_mrr    : SUM(mrr) langganan Active (nilai berulang berjalan).
//   - total_arr    : total_mrr × 12 (proyeksi 12 bln, keputusan user — bukan kolom
//     arr yg bisa diskon tahunan; label kartu "proyeksi 12 bln" persis).
//   - new_mrr      : SUM(mrr) langganan BARU (tanpa previous_subscription_id — logo
//     baru, bukan perpanjangan) yang mulai BULAN berjalan. Definisi
//     "MRR baru bln ini" (keputusan user) selaras ReportSubMRR.new_mrr
//     (renewal punya previous_subscription_id → sengaja tak dihitung
//     agar delta = pertumbuhan bersih, bukan sekadar start_date baru).
//   - active_count : COUNT langganan Active (kartu "Active Subs").
//   - churned_30   : COUNT Cancelled/Churned dgn cancellation_date dalam 30 hari
//     terakhir → pembilang Churn Rate (definisi churn% app: churned /
//     (active + churned), jendela 30 hari untuk churned).
//   - total_accounts : COUNT semua akun (desa) hidup di tenant — denominator "dari
//     N desa" (keputusan user: total akun, bukan hanya yg berlangganan).
//     Subquery SENGAJA di luar filter ownership: denominator = basis
//     desa penuh, bukan yg dimiliki pemanggil.
//
// today dioper handler (zona waktu app, deterministik utk test).
func (q *Queries) SubscriptionListKPIs(ctx context.Context, arg SubscriptionListKPIsParams) (SubscriptionListKPIsRow, error) {
	row := q.db.QueryRow(ctx, subscriptionListKPIs,
		arg.Today,
		arg.ScopeAll,
		arg.IsOwn,
		arg.Uid,
	)
	var i SubscriptionListKPIsRow
	err := row.Scan(
		&i.TotalMrr,
		&i.TotalArr,
		&i.NewMrr,
		&i.ActiveCount,
		&i.Churned30,
		&i.TotalAccounts,
	)
	return i, err
}

const updateCSRenewalAction = `-- name: UpdateCSRenewalAction :one
UPDATE subscriptions SET
    renewal_stage            = $1,
    renewal_risk             = $2,
    renewal_action_plan      = $3,
    renewal_next_action_date = $4,
    renewal_owner            = $5,
    updated_by               = $6,
    updated_at               = now()
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, renewal_stage, renewal_risk, renewal_action_plan,
          renewal_next_action_date, renewal_owner, updated_at
`

type UpdateCSRenewalActionParams struct {
	RenewalStage          *string     `json:"renewal_stage"`
	RenewalRisk           *string     `json:"renewal_risk"`
	RenewalActionPlan     *string     `json:"renewal_action_plan"`
	RenewalNextActionDate pgtype.Date `json:"renewal_next_action_date"`
	RenewalOwner          *int64      `json:"renewal_owner"`
	UpdatedBy             *int64      `json:"updated_by"`
	ID                    int64       `json:"id"`
}

type UpdateCSRenewalActionRow struct {
	ID                    int64              `json:"id"`
	RenewalStage          *string            `json:"renewal_stage"`
	RenewalRisk           *string            `json:"renewal_risk"`
	RenewalActionPlan     *string            `json:"renewal_action_plan"`
	RenewalNextActionDate pgtype.Date        `json:"renewal_next_action_date"`
	RenewalOwner          *int64             `json:"renewal_owner"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Perbarui field AKSI CS renewal (6.6 "Renewal Dua-Rumah"). Hanya empat field
// milik CS yang disentuh; field inti langganan (status, MRR, dsb.) tidak berubah.
// Handler menegakkan F3 (loadCSRenewal) sebelum memanggil query ini.
func (q *Queries) UpdateCSRenewalAction(ctx context.Context, arg UpdateCSRenewalActionParams) (UpdateCSRenewalActionRow, error) {
	row := q.db.QueryRow(ctx, updateCSRenewalAction,
		arg.RenewalStage,
		arg.RenewalRisk,
		arg.RenewalActionPlan,
		arg.RenewalNextActionDate,
		arg.RenewalOwner,
		arg.UpdatedBy,
		arg.ID,
	)
	var i UpdateCSRenewalActionRow
	err := row.Scan(
		&i.ID,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.RenewalOwner,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions SET
    subscription_owner   = $1,
    plan_id              = $2,
    start_date           = $3,
    end_date             = $4,
    billing_cycle        = $5,
    auto_renew           = $6,
    contract_term_months = $7,
    mrr                  = $8,
    arr                  = $9,
    quantity_seats       = $10,
    discount_pct         = $11,
    payment_status       = $12,
    renewal_status       = $13,
    renewal_type         = $14,
    renewal_owner        = $15,
    renewal_quote_id     = $16,
    updated_by           = $17,
    updated_at           = now()
WHERE id = $18 AND deleted_at IS NULL
RETURNING id, tenant_id, entity_code, subscription_owner, account_id, plan_id, source_deal_id, previous_subscription_id, status, start_date, end_date, billing_cycle, auto_renew, contract_term_months, mrr, arr, quantity_seats, discount_pct, payment_status, renewal_status, renewal_type, renewal_owner, renewal_quote_id, previous_value, renewal_stage, renewal_risk, renewal_action_plan, renewal_next_action_date, cancellation_date, churn_reason, churn_type, churn_notes, lost_value_mrr, win_back_eligible, deleted_at, created_by, created_at, updated_by, updated_at, approval_status, approved_by, approved_at
`

type UpdateSubscriptionParams struct {
	SubscriptionOwner  *int64         `json:"subscription_owner"`
	PlanID             *int64         `json:"plan_id"`
	StartDate          pgtype.Date    `json:"start_date"`
	EndDate            pgtype.Date    `json:"end_date"`
	BillingCycle       *string        `json:"billing_cycle"`
	AutoRenew          bool           `json:"auto_renew"`
	ContractTermMonths *int32         `json:"contract_term_months"`
	Mrr                pgtype.Numeric `json:"mrr"`
	Arr                pgtype.Numeric `json:"arr"`
	QuantitySeats      *int32         `json:"quantity_seats"`
	DiscountPct        pgtype.Numeric `json:"discount_pct"`
	PaymentStatus      *string        `json:"payment_status"`
	RenewalStatus      *string        `json:"renewal_status"`
	RenewalType        *string        `json:"renewal_type"`
	RenewalOwner       *int64         `json:"renewal_owner"`
	RenewalQuoteID     *int64         `json:"renewal_quote_id"`
	UpdatedBy          *int64         `json:"updated_by"`
	ID                 int64          `json:"id"`
}

// Sunting profil langganan. status, renewal-action (6.6), dan churn (5.4) punya
// jalur sendiri (UpdateSubscriptionStatus/ChurnSubscription) agar transisi status &
// churn terlihat sebagai aksi tersendiri, bukan efek samping edit.
func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.SubscriptionOwner,
		arg.PlanID,
		arg.StartDate,
		arg.EndDate,
		arg.BillingCycle,
		arg.AutoRenew,
		arg.ContractTermMonths,
		arg.Mrr,
		arg.Arr,
		arg.QuantitySeats,
		arg.DiscountPct,
		arg.PaymentStatus,
		arg.RenewalStatus,
		arg.RenewalType,
		arg.RenewalOwner,
		arg.RenewalQuoteID,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityCode,
		&i.SubscriptionOwner,
		&i.AccountID,
		&i.PlanID,
		&i.SourceDealID,
		&i.PreviousSubscriptionID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.BillingCycle,
		&i.AutoRenew,
		&i.ContractTermMonths,
		&i.Mrr,
		&i.Arr,
		&i.QuantitySeats,
		&i.DiscountPct,
		&i.PaymentStatus,
		&i.RenewalStatus,
		&i.RenewalType,
		&i.RenewalOwner,
		&i.RenewalQuoteID,
		&i.PreviousValue,
		&i.RenewalStage,
		&i.RenewalRisk,
		&i.RenewalActionPlan,
		&i.RenewalNextActionDate,
		&i.CancellationDate,
		&i.ChurnReason,
		&i.ChurnType,
		&i.ChurnNotes,
		&i.LostValueMrr,
		&i.WinBackEligible,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions SET
    status     = $1,
    updated_by = $2,
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateSubscriptionStatusParams struct {
	Status    string `json:"status"`
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

// Transisi status (Trial→Active, Active→Expired saat renewal, dst). Aturan transisi
// valid divalidasi handler (bukan constraint DB) agar pesan bisa diperbaiki user;
// subs_status_chk hanya membatasi himpunan nilai legal. INVARIAN renewal: Expired
// baris lama HARUS mendahului CreateSubscription baris aktif dalam tx yang sama.
func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.Status, arg.UpdatedBy, arg.ID)
	return err
}
